<DOC>
<DOCNO.valor=FSP940701-052>
<DOCID.valor=FSP940701-052>
<DATE.valor=940701>
<TEXT>
<s>
$(	 [$(] PU
continuação	 [continuação] N F S @NPHR
$)	 [$)] PU
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @PRED>
3º.	 [3º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O	 [o] <artd> DET M S @>N
presidente	 [presidente] N M S @SUBJ>
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Conselho	 [conselho] <prop> N M S @P<
poderá	 [poder] <fmc> V FUT 3S IND VFIN @FAUX
convidar	 [convidar] V INF @IMV @#ICL-AUX<
ministros	 [ministro] N M P @<ACC
de	 [de] PRP @N<
Estado	 [estado] <prop> N M S @P<
$,
bem=como	 [bem=como] <rel> ADV @ADVL @#AS-<ADVL
representantes	 [representante] N M/F P @AS<
de	 [de] PRP @N<
entidades	 [entidade] N F P @P<
públicas	 [público] ADJ F P @N<
ou	 [ou] <co-postnom> KC @CO
privadas	 [privado] ADJ F P @N<
$,
para	 [para] PRP @ADVL>
participar	 [participar] V INF @IMV @#ICL-P<
de	 [de] <sam-> PRP @<PIV
as	 [o] <artd> <-sam> DET F P @>N
reuniões	 [reunião] N F P @P<
$,
não	 [não] ADV @ADVL>
lhes	 [eles] PERS M/F 3P DAT @DAT>
sendo	 [ser] V GER @IAUX @#ICL-<ADVL
permitido	 [permitir] V PCP M S @IMV @#ICL-AUX<
o	 [o] <artd> DET M S @>N
direito	 [direito] N M S @<SUBJ
de	 [de] PRP @N<
voto	 [voto] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
4º.	 [4º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O=Conselho	 [O=Conselho] PROP M S @SUBJ>
reunirá-	 [reunir] <hyfen> <fmc> V FUT 3S IND VFIN @FMV
se-	 [se] <refl> <hyfen> PERS M 3S ACC @<ACC
$,
ordinariamente	 [ordinariamente] ADV @<ADVL
$,
uma=vez	 [uma=vez] ADV @<ADVL
por	 [por] PRP @<ADVL
mês	 [mês] N M S @P<
$,
e	 [e] <co-vfin> KC @CO
$,
extraordinariamente	 [extraordinariamente] ADV @<ADVL
$,
sempre=que	 [sempre=que] <ks> <rel> ADV @ADVL> @#FS-<ADVL @#FS-N<
for	 [ser] V FUT 3S SUBJ VFIN @FAUX
convocado	 [convocar] V PCP M S @IMV @#ICL-AUX<
por	 [por] PRP @<PASS
seu	 [seu] <poss 3S> DET M S @>N
presidente	 [presidente] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
5º.	 [5º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O=Banco=Central=do=Brasil	 [O=Banco=Central=do=Brasil] PROP M S @SUBJ>
funcionará	 [funcionar] <fmc> V FUT 3S IND VFIN @FMV
como	 [como] <rel> <prp> ADV @COM @#AS-<ADVL
secretaria-executiva	 [secretaria-executiva] N F S @AS<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Conselho	 [conselho] <prop> N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
6º.	 [6º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O=Regimento=Interno	 [O=Regimento=Interno] PROP M S @SUBJ>
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Conselho=Monetário=Nacional	 [Conselho=Monetário=Nacional] PROP M S @P<
será	 [ser] <fmc> V FUT 3S IND VFIN @FAUX
aprovado	 [aprovar] V PCP M S @IMV @#ICL-AUX<
por	 [por] PRP @<PASS
Decreto	 [decreto] <prop> N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
presidente	 [presidente] N M S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
República	 [república] <prop> N F S @P<
$,
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
prazo	 [prazo] N M S @P<
máximo	 [grande] <SUP> ADJ M S @N<
de	 [de] PRP @N<
30	 [30] <card> NUM M/F P @>N
$(	 [$(] PU
trinta	 [trinta] <card> NUM M/F P @P<
$)	 [$)] PU
dias	 [dia] N M P @N<PRED
$,
contados	 [contar] V PCP M P @N<PRED
de	 [de] <sam-> PRP @N<PRED
a	 [o] <artd> <-sam> DET F S @>N
publicação	 [publicação] N F S @P<
de	 [de] <sam-> PRP @N<
esta	 [este] <dem> <-sam> DET F S @>N
medida	 [medida] N F S @P<
provisória	 [provisório] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
7º.	 [7º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
A=partir=de	 [a=partir=de] <sam-> PRP @ADVL>
a	 [o] <-sam> <artd> DET F S @>N
publicação	 [publicação] N F S @P<
de	 [de] <sam-> PRP @N<
esta	 [este] <dem> <-sam> DET F S @>N
medida	 [medida] N F S @P<
provisória	 [provisório] ADJ F S @N<
$,
ficam	 [ficar] <fmc> V PR 3P IND VFIN @FMV
extintos	 [extinguir] V PCP M P @<SC
os	 [o] <artd> DET M P @>N
atuais	 [atual] ADJ M P @>N
mandatos	 [mandato] N M P @PRED>
de	 [de] PRP @N<
membros	 [membro] N M P @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Conselho=Monetário=Nacional	 [Conselho=Monetário=Nacional] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
9º.	 [9º.] <NUM-ord> ADJ F S @SUBJ>
$	 [$] PU
É	 [ser] <fmc> V PR 3S IND VFIN @FMV
criada	 [criado] ADJ F S @<SC	 [criada] N F S @<SC
junto	 [junto] ADV @<ADVL
a	 [a] <sam-> PRP @A<
o	 [o] <-sam> <artd> DET M S @>N
Conselho=Monetário=Nacional	 [Conselho=Monetário=Nacional] PROP M S @P<
a	 [o] <artd> DET F S @>N
Comissão=Técnica=da=Moeda	 [Comissão=Técnica=da=Moeda] PROP F S @APP
e	 [e] KC @CO
de	 [de] <sam-> PRP @A<
o	 [o] <artd> <-sam> DET M S @>N
Crédito	 [crédito] <prop> N M S @P<
$,
composta	 [compor] V PCP F S @IMV @#ICL-<SC 
de	 [de] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
seguintes	 [seguinte] ADJ M P @>N
membros	 [membro] N M P @P<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
I	 [i] N M S @NPHR
$	 [$] PU
presidente	 [presidente] N M/F S @NPHR
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Banco=Central=do=Brasil	 [Banco=Central=do=Brasil] PROP M S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
II	 [II] <NUM-ord> ADJ M/F S @NPHR
$	 [$] PU
presidente	 [presidente] N M/F S @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Comissão=de=Valores=Mobiliários	 [Comissão=de=Valores=Mobiliários] PROP F S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
III	 [III] <NUM-ord> ADJ M/F S @NPHR
$	 [$] PU
Os	 [o] <artd> DET M P @>N
secretários	 [secretário] N M P @NPHR
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Tesouro=Nacional	 [Tesouro=Nacional] PROP M S @P<
e	 [e] <co-postnom> KC @CO
de	 [de] PRP @N<
Política=Econômica	 [Política=Econômica] PROP F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Ministério=da=Fazenda	 [Ministério=da=Fazenda] PROP M S @P<
$;	 [$;] PU <<<
e	 [e] KC @CO
$¶	 [$¶] PU <<<
</s>
<s>
IV	 [IV] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Os	 [o] <artd> DET M P @>N
diretores	 [diretor] N M P @NPHR
de	 [de] PRP @N<
Política=Monetária	 [Política=Monetária] PROP F S @P<
$,
de	 [de] PRP @N<PRED
Assuntos=Internacionais	 [Assuntos=Internacionais] PROP M/F S @P<
e	 [e] KC @CO
de	 [de] PRP @ADVL
Normas	 [norma] <prop> N F P @P<
e	 [e] <co-prparg> KC @CO
Organização=do=Sistema=Financeiro	 [Organização=do=Sistema=Financeiro] PROP F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Banco=Central	 [Banco=Central] PROP M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Brasil	 [Brasil] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
As	 [o] <artd> DET F P @>N
reuniões	 [reunião] N F P @SUBJ>
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Comissão	 [comissão] PROP F S @P<
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
coordenadas	 [coordenar] V PCP F P @IMV @#ICL-AUX<
por	 [por] <sam-> PRP @<PASS
o	 [o] <artd> <-sam> DET M S @>N
presidente	 [presidente] N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Banco=Central=do=Brasil	 [Banco=Central=do=Brasil] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
2º.	 [2º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O=Regimento=da=Comissão=Técnica=da=Moeda	 [O=Regimento=da=Comissão=Técnica=da=Moeda] PROP M S @SUBJ>
e	 [e] KC @CO
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Crédito	 [crédito] <prop> N M S @P<
será	 [ser] <fmc> V FUT 3S IND VFIN @FAUX
aprovado	 [aprovar] V PCP M S @IMV @#ICL-AUX<
por	 [por] <sam-> PRP @<PASS
o	 [o] <artd> <-sam> DET M S @>N
presidente	 [presidente] N M S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
República	 [república] <prop> N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
10º.	 [10º.] <NUM-ord> ADJ M/F S @SUBJ>
$	 [$] PU
Compete	 [competir] <fmc> V PR 3S IND VFIN @FMV
a	 [a] <sam-> PRP @<PIV
a	 [o] <-sam> <artd> DET F S @>N
Comissão=Técnica=da=Moeda	 [Comissão=Técnica=da=Moeda] PROP F S @P<
e	 [e] KC @CO
de	 [de] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
Crédito	 [crédito] <prop> N M S @P<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
a	 [a] PRP @ADVL
$)	 [$)] PU
propor	 [propor] V INF @IMV @#ICL-P<
a	 [o] <artd> DET F S @>N
regulamentação	 [regulamentação] N F S @<ACC
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
matérias	 [matéria] N F P @P<
tratadas	 [tratar] V PCP F P @IMV @#ICL-N<
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
presente	 [presente] ADJ F S @>N
medida	 [medida] N F S @P<
provisória	 [provisório] ADJ F S @N<
$,
de	 [de] PRP @N<PRED
competência	 [competência] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Conselho=Monetário=Nacional	 [Conselho=Monetário=Nacional] PROP M S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
b	 [b] N M S @SUBJ>
$)	 [$)] PU
manifestar-	 [manifestar] <hyfen> V INF 3S @IMV
se	 [se] PERS M 3S/P ACC @<ACC-PASS
$,
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
prevista	 [prever] V PCP F S @IMV @#ICL-N<
em	 [em] PRP @<ADVL
seu	 [seu] <si> <poss 3S> DET M S @>N
Regimento	 [regimento] <prop> N M S @P<
$,
previamente	 [previamente] ADV @<ADVL
$,
sobre	 [sobre] PRP @<ADVL
as	 [o] <artd> DET F P @>N
matérias	 [matéria] N F P @P<
de	 [de] PRP @N<
competência	 [competência] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Conselho=Monetário=Nacional	 [Conselho=Monetário=Nacional] PROP M S @P<
$,
especialmente	 [especialmente] ADV @<ADVL
aquelas	 [aquele] <dem> DET F P @>N
constantes	 [constante] N F P @<ACC @APP
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
lei	 [lei] N F S @P<
nº	 [nº] N M S @PRED>
$.	 [$.] PU <<<
4.595	 [4.595] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
31	 [31] <card> NUM M/F P @P<
de	 [de] PRP @N<
dezembro	 [dezembro] N M S @P<
de	 [de] PRP @N<
1964	 [1964] <card> NUM M/F P @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
c	 [c] N M S @NPHR
$)	 [$)] PU
outras	 [outro] <KOMP> <diff> DET F P @>N
atribuições	 [atribuição] N F P @NPHR
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
lhe	 [ele] PERS M/F 3S DAT @DAT>
forem	 [ser] V FUT 3P SUBJ VFIN @FAUX
cometidas	 [cometer] V PCP F P @IMV @#ICL-AUX<
por	 [por] <sam-> PRP @<PASS
o	 [o] <artd> <-sam> DET M S @>N
Conselho=Monetário=Nacional	 [Conselho=Monetário=Nacional] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
11º.	 [11º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Funcionarão	 [funcionar] <fmc> V FUT 3P IND VFIN @FMV
também	 [também] ADV @>A
junto	 [junto] ADV @<ADVL
a	 [a] <sam-> PRP @A<
o	 [o] <-sam> <artd> DET M S @>N
Conselho=Monetário=Nacional	 [Conselho=Monetário=Nacional] PROP M S @P<
as	 [o] <artd> DET F P @>N
seguintes	 [seguinte] <n> ADJ F P @<SUBJ
Comissões=Consultivas	 [Comissões=Consultivas] PROP F S/P @APP
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
I	 [i] N M S @NPHR
$	 [$] PU
de	 [de] PRP @ADVL
Normas	 [norma] <prop> N F P @P<
e	 [e] <co-prparg> KC @CO
Organização=do=Sistema=Financeiro	 [Organização=do=Sistema=Financeiro] PROP F S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
II	 [II] <NUM-ord> ADJ M/F S @NPHR
$	 [$] PU
de	 [de] PRP @ADVL
Mercado=de=Valores=Mobiliários	 [Mercado=de=Valores=Mobiliários] PROP M S @P<
e	 [e] KC @CO
de	 [de] PRP @ADVL
Futuros	 [Futuros] PROP M/F S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
III	 [III] <NUM-ord> ADJ M/F S @NPHR
$	 [$] PU
de	 [de] PRP @ADVL
Crédito=Rural	 [Crédito=Rural] PROP M S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
IV	 [IV] <NUM-ord> ADJ M/F S @NPHR
$	 [$] PU
de	 [de] PRP @ADVL
Crédito=Industrial	 [Crédito=Industrial] PROP M S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
V	 [v] N M S @NPHR
$--	 [$--] PU
de	 [de] PRP @ADVL
Endividamento=Público	 [Endividamento=Público] PROP M S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
VI	 [VI] <NUM-ord> ADJ M/F S @NPHR
$	 [$] PU
de	 [de] PRP @ADVL
Política=Monetária	 [Política=Monetária] PROP F S @P<
e	 [e] <co-prparg> KC @CO
Cambial	 [Cambial] PROP M/F S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
VII	 [VII] <NUM-ord> ADJ M/F S @NPHR
$	 [$] PU
de	 [de] PRP @ADVL
Processos=Administrativos	 [Processos=Administrativos] PROP M/F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
A	 [o] <artd> DET F S @>N
organização	 [organização] N F S @SUBJ>
$,
a	 [o] <artd> DET F S @>N
composição	 [composição] N F S @SUBJ>
e	 [e] <co-subj> KC @CO
o	 [o] <artd> DET M S @>N
funcionamento	 [funcionamento] N M S @SUBJ>
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
Comissões=Consultivas	 [Comissões=Consultivas] PROP F P @P<
serão	 [ser] <fmc> V FUT 3P IND VFIN @FMV
objeto	 [objeto] N M S @<SC
de	 [de] PRP @N<
Regimento=Interno	 [Regimento=Interno] PROP M S @P<
$,
a	 [a] PRP @ADVL>
ser	 [ser] V INF @IAUX @#ICL-P<
aprovado	 [aprovar] V PCP M S @IMV @#ICL-AUX<
por	 [por] PRP @<PASS
decreto	 [decreto] N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
presidente	 [presidente] N M S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
República	 [república] <prop> N F S @P<
$,
em	 [em] <sam-> PRP @<ADVL
ele	 [ele] <-sam> PERS M 3S NOM/PIV @P<
incluídas	 [incluir] V PCP F P @>N
normas	 [norma] N F P @<PRED
que	 [que] <rel> SPEC M S @ACC> @#FS-N<
regulem	 [regular] V PR 3P SUBJ VFIN @FMV
a	 [o] <artd> DET F S @>N
audiência	 [audiência] N F S @<SUBJ
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
Comissões=Consultivas	 [Comissões=Consultivas] PROP F P @P<
$,
por	 [por] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
Conselho=Monetário=Nacional	 [Conselho=Monetário=Nacional] PROP M S @P<
$,
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
trato	 [trato] N M S @P<
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
matérias	 [matéria] N F P @P<
atinentes	 [atinente] ADJ F P @N<
a	 [a] <sam-> PRP @N<
as	 [o] <-sam> <artd> DET F P @>N
finalidades	 [finalidade] N F P @P<
específicas	 [específico] ADJ F P @N<
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
referidas	 [referir] V PCP F P @>N
Comissões	 [comissão] <prop> N F P @P<
$,
ressalvados	 [ressalvar] V PCP M P @IMV @#ICL-<ADVL
os	 [o] <artd> DET M P @>N
casos	 [caso] N M P @<SUBJ
em	 [em] PRP @<ADVL
que	 [que] KS @SUB @#FS-<ACC
se	 [se] PERS M/F 3S/P ACC @SUBJ>
impuser	 [impor] V FUT 3S SUBJ VFIN @FMV
sigilo	 [sigilo] N M S @<ACC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
2º.	 [2º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Os	 [o] <artd> DET M P @>N
atuais	 [atual] ADJ M P @>N
mandatos	 [mandato] N M P @SUBJ>
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
membros	 [membro] N M P @P<
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
Comissões=Consultivas	 [Comissões=Consultivas] PROP F P @P<
ficam	 [ficar] <fmc> V PR 3P IND VFIN @FMV
extintos	 [extinguir] V PCP M P @<SC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Capítulo=III	 [Capítulo=III] PROP M S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
De	 [de] <sam-> PRP @ADVL
as	 [o] <artd> <-sam> DET F P @>N
Conversões	 [conversão] <prop> N F P @P<
para	 [para] PRP @ADVL>
real	 [real] N M S @P<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
12º.	 [12º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Em	 [em] <sam-> PRP @ADVL>
a	 [o] <artd> <-sam> DET F S @>N
operação	 [operação] N F S @P<
de	 [de] PRP @N<
conversão	 [conversão] N F S @P<
de	 [de] PRP @N<
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
para	 [para] PRP @N<
real	 [real] N M S @P<
$,
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
adotadas	 [adotar] V PCP F P @IMV @#ICL-AUX<
quatro	 [quatro] <card> NUM F P @>N
casas	 [casa] N F P @<SUBJ
decimais	 [decimal] ADJ F P @N<
em	 [em] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
quociente	 [quociente] N M S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
divisão	 [divisão] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Em	 [em] PRP @ADVL>
todos=os	 [todo=o] <quant> DET M P @>N
pagamentos	 [pagamento] N M P @P<
ou	 [ou] <co-prparg> KC @CO
liquidações	 [liquidação] N F P @SUBJ> @P<
de	 [de] PRP @N<
soma	 [soma] N F S @P<
a	 [a] PRP @ADVL>
receber	 [receber] V INF @IMV @#ICL-P<
ou	 [ou] <co-inf> KC @CO
a	 [a] N M S @SUBJ> @<ACC
pagar	 [pagar] V INF 3S @IMV @#ICL-P<
e	 [e] KC @CO
registros	 [registro] N M P @<ACC
contábeis	 [contábil] ADJ M P @N<
$,
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
desprezados	 [desprezar] V PCP M P @IMV @#ICL-AUX<
$,
para	 [para] PRP @<ADVL
todos=os	 [todo=o] <quant> DET M P @>N
efeitos	 [efeito] N M P @P<
legais	 [legal] ADJ M P @N<
$,
os	 [o] <artd> DET M P @>N
valores	 [valor] N M P @<SUBJ
inferiores	 [inferior] <KOMP> <SUP> ADJ M P @N<
ou	 [ou] <co-subj> KC @CO
correspondente	 [correspondente] N M/F S @<SUBJ
a	 [a] PRP @<ADVL @N<
um	 [um] <card> NUM M S @>N
centavo	 [centavo] N M S @P<
de	 [de] PRP @N<
real	 [real] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
2º.	 [2º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Em	 [em] <sam-> PRP @ADVL>
as	 [o] <artd> <-sam> DET F P @>N
instituições	 [instituição] N F P @P<
financeiras	 [financeiro] ADJ F P @N<
e	 [e] <co-advl> KC @CO
em	 [em] <sam-> PRP @ADVL>
as	 [o] <artd> <-sam> DET F P @>N
demais	 [demais] DET F P @>N
entidades	 [entidade] N F P @P<
autorizadas	 [autorizar] V PCP F P @IMV @#ICL-N<
a	 [a] PRP @<PIV
funcionar	 [funcionar] V INF @IMV @#ICL-P<
por	 [por] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
Banco=Central=do=Brasil	 [Banco=Central=do=Brasil] PROP M S @P<
a	 [o] <artd> DET F S @>N
soma	 [soma] N F S @<SUBJ
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
parcelas	 [parcela] N F P @P<
desprezadas	 [desprezar] V PCP F P @N<
$,
em	 [em] <sam-> PRP @ADVL>
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
parágrafo	 [parágrafo] N M S @P<
anterior	 [anterior] ADJ M S @N<
$,
será	 [ser] <fmc> V FUT 3S IND VFIN @FAUX
recolhida	 [recolher] V PCP F S @IMV @#ICL-AUX<
e	 [e] <co-pcv> KC @CO
creditada	 [creditar] V PCP F S @<SUBJ @IMV @#ICL-AUX<
a	 [a] <sam-> PRP @<PIV
o	 [o] <-sam> <artd> DET M S @>N
Tesouro=Nacional	 [Tesouro=Nacional] PROP M S @P<
$,
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
prazo	 [prazo] N M S @P<
máximo	 [grande] <SUP> ADJ M S @N<
de	 [de] PRP @N<
trinta	 [trinta] <card> NUM M P @>N
dias	 [dia] N M P @P<
$,
contados	 [contar] V PCP M P @N<PRED
a=partir=de	 [a=partir=de] PRP @<ADVL
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
para	 [para] PRP @ADVL>
serem	 [ser] V INF 3P @IAUX @#ICL-P<
utilizados	 [utilizar] V PCP M P @IMV @#ICL-AUX<
em	 [em] PRP @<ADVL
programas	 [programa] N M P @P<
emergenciais	 [emergencial] ADJ M P @N<
contra	 [contra] PRP @N<
a	 [o] <artd> DET F S @>N
fome	 [fome] N F S @P<
e	 [e] <co-prparg> KC @CO
a	 [o] <artd> DET F S @>N
miséria	 [miséria] N F S @<SUBJ @P<
$,
conforme	 [conforme] ADJ F S @>N	 [conforme] <prp> <rel> ADV @COM @#AS-<ADVL
regulamentação	 [regulamentação] N F S @AS<
a	 [a] PRP @<ADVL
ser	 [ser] V INF @IAUX @#ICL-P<
baixada	 [baixar] V PCP F S @IMV @#ICL-AUX<
por	 [por] <sam-> PRP @<PASS
o	 [o] <artd> <-sam> DET M S @>N
Poder=Executivo	 [Poder=Executivo] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
13º.	 [13º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
A=partir=de	 [a=partir=de] PRP @ADVL>
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
todos=os	 [todo=o] <quant> DET M P @>N
valores	 [valor] N M P @SUBJ>
expressos	 [esprimir] V PCP M P @IMV @#ICL-N<
em	 [em] PRP @<ADVL
URV	 [uRV] <prop> N F S @P<
passam	 [passar] <fmc> V PR 3P IND VFIN @FAUX
a	 [a] PRP @PRT-AUX<
ser	 [ser] V INF @IAUX @#ICL-AUX<
expressos	 [esprimir] V PCP M P @IMV @#ICL-AUX<
$,
de	 [de] PRP @<PRED
pleno	 [pleno] ADJ M S @>N
direito	 [direito] N M S @P<
$,
em	 [em] PRP @<ADVL
igual	 [igual] ADJ M S @>N
número	 [número] N M S @P<
de	 [de] PRP @N<
reais	 [real] N M P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
14º.	 [14º.] <NUM-ord> ADJ M/F S @SUBJ>
$	 [$] PU
As	 [o] <artd> DET F P @>N
obrigações	 [obrigação] N F P @SUBJ>
pecuniárias	 [pecuniário] ADJ F P @N<
expressas	 [esprimir] V PCP F P @IMV @#ICL-N<
em	 [em] PRP @<ADVL
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
não	 [não] ADV @ADVL>
tenham	 [ter] V PR 3P SUBJ VFIN @FAUX
sido	 [ser] V PCP @IAUX @#ICL-AUX<
convertidas	 [converter] V PCP F P @IMV @#ICL-AUX<
em	 [em] PRP @<PIV
URV	 [uRV] <prop> N F S @P<
até	 [até] PRP @<ADVL
30	 [30] <card> NUM M/F S @P<
de	 [de] PRP @N<
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
inclusive	 [inclusive] ADV @<ADVL
$,
serão	 [ser] <fmc> V FUT 3P IND VFIN @FMV
$,
em	 [em] PRP @<ADVL
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
obrigatoriamente	 [obrigatório] ADV @<ADVL @>A
convertidas	 [converter] V PCP F P @IMV @#ICL-<SC @#ICL-N<
em	 [em] PRP @<PIV
real	 [real] N M S @P<
$,
de=acordo	 [de=acordo] ADV @<ADVL
com	 [com] PRP @A<
as	 [o] <artd> DET F P @>N
normas	 [norma] N F P @P<
de	 [de] <sam-> PRP @N<
esta	 [este] <dem> <-sam> DET F S @>N
medida	 [medida] N F S @P<
provisória	 [provisório] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
único	 [único] ADJ M S @N<
$	 [$] PU
O	 [o] <artd> DET M S @>N
disposto	 [dispor] <n> V PCP M S @ACC>
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
caput ALT xxx	 [caput] N M S @P<
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
aplica-	 [aplicar] <hyfen> <fmc> V PR 3S IND VFIN @FMV
se	 [se] <refl> PERS M 3S ACC @<ACC-PASS
a	 [a] <sam-> PRP @<PIV
as	 [o] <-sam> <artd> DET F P @>N
obrigações	 [obrigação] N F P @P<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
tenham	 [ter] V PR 3P SUBJ VFIN @FAUX
sido	 [ser] V PCP @IAUX @#ICL-AUX<
mantidas	 [manter] V PCP F P @IMV @#ICL-AUX<
em	 [em] PRP @<ADVL
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
por=força=de	 [por=força=de] <sam-> PRP @N<
o	 [o] <-sam> <artd> DET M S @>N
contido	 [conter] <n> V PCP M S @IMV @#ICL-P<
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
lei	 [lei] N F S @P<
nº	 [nº] N M S @<ACC
$.	 [$.] PU <<<
8.880	 [8.880] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
27	 [27] <card> NUM M/F P @P<
de	 [de] PRP @N<
maio	 [maio] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
inclusive	 [inclusive] ADV @>P
em	 [em] PRP @ADVL
seu	 [seu] <poss 3S> DET M S @>N
art.	 [art.] N M S @P<
16º	 [16º] <card> NUM M/F P @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
15º.	 [15º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
convertidos	 [converter] V PCP M P @IMV @#ICL-AUX<
em	 [em] PRP @<PIV
real	 [real] N M S @P<
$,
em	 [em] PRP @<PIV
1º	 [1º] <n> <NUM-ord> ADJ M S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
segundo	 [segundo] <prp> <rel> ADV @COM @#AS-<ADVL
a	 [o] <artd> DET F S @>N
paridade	 [paridade] N F S @AS<
fixada	 [fixar] V PCP F S @N<
para	 [para] PRP @N<
aquela	 [aquele] <dem> DET F S @>N
data	 [data] N F S @P<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
a	 [a] PRP @ADVL
$)	 [$)] PU
as	 [o] <artd> DET F P @>N
contas	 [conta] N F P @P<
correntes	 [corrente] ADJ F P @N<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
b	 [b] N M S @NPHR
$)	 [$)] PU
os	 [o] <artd> DET M P @>N
depósitos	 [depósito] N M P @NPHR
à=vista	 [à=vista] ADV @ADVL
em	 [em] <sam-> PRP @ADVL
as	 [o] <artd> <-sam> DET F P @>N
instituições	 [instituição] N F P @P<
financeiras	 [financeiro] ADJ F P @N<
$;	 [$;] PU <<<
e	 [e] KC @CO
$¶	 [$¶] PU <<<
</s>
<s>
c	 [c] N M S @NPHR
$)	 [$)] PU
os	 [o] <artd> DET M P @>N
depósitos	 [depósito] N M P @NPHR
compulsórios	 [compulsório] ADJ M P @N<
em	 [em] PRP @N<
espécie	 [espécie] N F S @P<
sobre	 [sobre] PRP @ADVL>
depósitos	 [depósito] N M P @P<
à=vista	 [à=vista] ADV @ADVL
$,
mantidos	 [manter] V PCP M P @IMV @#ICL-N<PRED @#ICL-P<
por	 [por] <sam-> PRP @<PASS
o	 [o] <artd> <-sam> DET M S @>N
sistema	 [sistema] N M S @P<
bancário	 [bancário] ADJ M S @N<
junto	 [junto] ADV @ADVL
a	 [a] <sam-> PRP @A<
o	 [o] <-sam> <artd> DET M S @>N
Banco=Central=do=Brasil	 [Banco=Central=do=Brasil] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
16º.	 [16º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Observado	 [observar] V PCP M S @SUBJ>
o	 [o] <artd> DET M S @>N
disposto	 [dispor] V PCP M S @IMV @#ICL-<PRED
em	 [em] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
parágrafos	 [parágrafo] N M P @P<
1º.	 [1º.] <NUM-ord> ADJ M S @N<
a	 [o] <artd> DET F S @>N
4º.	 [4º.] <n> <n> <NUM-ord> ADJ F S @SUBJ>
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$,
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
igualmente	 [igualmente] <quant> ADV @>A
convertidos	 [converter] V PCP M P @IMV @#ICL-AUX<
em	 [em] PRP @<PIV
real	 [real] N M S @P<
$,
em	 [em] PRP @<PIV
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
de=acordo	 [de=acordo] ADV @<ADVL
com	 [com] PRP @A<
a	 [o] <artd> DET F S @>N
paridade	 [paridade] N F S @P<
fixada	 [fixar] V PCP F S @N<PRED
para	 [para] PRP @N<
aquela	 [aquele] <dem> DET F S @>N
data	 [data] N F S @P<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
a	 [a] PRP @ADVL
$)	 [$)] PU
os	 [o] <artd> DET M P @>N
saldos	 [saldo] N M P @P<
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
cadernetas	 [caderneta] N F P @P<
de	 [de] PRP @N<
poupança	 [poupança] N F S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
b	 [b] N M S @NPHR
$)	 [$)] PU
os	 [o] <artd> DET M P @>N
depósitos	 [depósito] N M P @NPHR
compulsórios	 [compulsório] ADJ M P @N<
e	 [e] <co-postnom> KC @CO
voluntários	 [voluntário] ADJ M P @N<
mantidos	 [manter] V PCP M P @N<
junto	 [junto] ADV @ADVL
a	 [a] <sam-> PRP @A<
o	 [o] <-sam> <artd> DET M S @>N
Banco=Central=do=Brasil	 [Banco=Central=do=Brasil] PROP M S @P<
$,
com	 [com] PRP @N<PRED
recursos	 [recurso] N M P @P<
originários	 [originário] ADJ M P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
captação	 [captação] N F S @P<
de	 [de] PRP @N<
cadernetas	 [caderneta] N F P @P<
de	 [de] PRP @N<
poupança	 [poupança] N F S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
c	 [c] N M S @NPHR
$)	 [$)] PU
os	 [o] <artd> DET M P @>N
saldos	 [saldo] N M P @NPHR
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
contas	 [conta] N F P @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Fundo=de=Garantia=de=Tempo=de=Serviço	 [Fundo=de=Garantia=de=Tempo=de=Serviço] PROP M S @P<
$,
de	 [de] <sam-> PRP @N<PRED
o	 [o] <artd> <-sam> DET M S @>N
Fundo=de=Participação=Pis	 [Fundo=de=Participação=Pis] PROP M S @P<
$/	 [$/] PU	 [$/] <co-prparg> KC @CO
Pasep	 [Pasep] PROP M/F S @P<
e	 [e] <co-pred> KC @CO
de	 [de] <sam-> PRP @<PRED
o	 [o] <artd> <-sam> DET M S @>N
Fundo=de=Amparo	 [Fundo=de=Amparo] PROP M S @P<
a	 [a] <sam-> PRP @ADVL
o	 [o] <-sam> <artd> DET M S @>N
Trabalhador	 [trabalhador] <prop> N M S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
d	 [d] N M S @NPHR
$)	 [$)] PU
as	 [o] <artd> DET F P @>N
operações	 [operação] N F P @NPHR
de	 [de] PRP @N<
crédito	 [crédito] N M S @P<
rural	 [rural] ADJ M S @N<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
e	 [e] KC @CO
$)	 [$)] PU
as	 [o] <artd> DET F P @>N
operações	 [operação] N F P @NPHR
ativas	 [ativo] ADJ F P @N<
e	 [e] <co-postnom> KC @CO
passivas	 [passivo] ADJ F P @N<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
Sistemas=Financeiro=da=Habitação	 [Sistemas=Financeiro=da=Habitação] PROP M P @P<
e	 [e] <co-postnom> KC @CO
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Saneamento	 [saneamento] <prop> N M S @P<
$(	 [$(] PU
SFH	 [SFH] PROP M/F S @NPHR
e	 [e] <co-pcv> KC @CO
SFS	 [SFS] PROP M/F S @NPHR
$)	 [$)] PU
$,
observado	 [observar] V PCP M S @IMV
o	 [o] <artd> DET M S @>N
disposto	 [dispor] <n> V PCP M S @<ACC
em	 [em] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
arts ALT xxxs	 [art] N M P @P<
$.	 [$.] PU <<<
20º	 [20º] <NUM-ord> ADJ M S @NPHR
e	 [e] KC @CO
21º	 [21º] <n> <NUM-ord> ADJ M S @NPHR
de	 [de] <sam-> PRP @N<
esta	 [este] <dem> <-sam> DET F S @>N
medida	 [medida] N F S @P<
provisória	 [provisório] ADJ F S @N<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
f	 [f] N M S @NPHR
$)	 [$)] PU
as	 [o] <artd> DET F P @>N
operações	 [operação] N F P @NPHR
de	 [de] PRP @N<
seguro	 [seguro] N M S @P<
$,
de	 [de] PRP @N<
previdência	 [previdência] N F S @P<
privada	 [privado] ADJ F S @N<
e	 [e] <co-postnom> KC @CO
de	 [de] PRP @N<
capitalização	 [capitalização] N F S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
g	 [g] N M S @NPHR
$)	 [$)] PU
as=demais	 [os=demais] DET F P @>N
operações	 [operação] N F P @NPHR
contratadas	 [contratar] V PCP F P @N<
com	 [com] PRP @N<
base	 [base] N F S @P<
em	 [em] <sam-> PRP @ADVL>
a	 [o] <artd> <-sam> DET F S @>N
Taxa=Referencial	 [Taxa=Referencial] PROP F S @P<
$	 [$] PU
TR	 [TR] PROP M/F S @NPHR
$	 [$] PU
ou	 [ou] KC @CO
em	 [em] <sam-> PRP @ADVL
o	 [o] <artd> <-sam> DET M S @>N
índice	 [índice] N M S @P<
de	 [de] PRP @N<
remuneração	 [remuneração] N F S @P<
básica	 [básico] ADJ F S @N<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
depósitos	 [depósito] N M P @P<
de	 [de] PRP @N<
poupança	 [poupança] N F S @P<
$;	 [$;] PU <<<
e	 [e] KC @CO
$¶	 [$¶] PU <<<
</s>
<s>
h	 [h] N F S/P @NPHR
$)	 [$)] PU
as=demais	 [os=demais] DET F P @>N
operações	 [operação] N F P @NPHR
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
mesma	 [mesmo] <diff> <KOMP> DET F S @>N
natureza	 [natureza] N F S @P<
$,
não	 [não] ADV @>A
compreendidas	 [compreender] V PCP F P @IMV @#ICL-N<PRED
em	 [em] <sam-> PRP @<ADVL
as	 [o] <artd> <-sam> DET F P @>N
alíneas	 [alínea] N F P @P<
anteriores	 [anterior] ADJ F P @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
A	 [o] <artd> DET F S @>N
conversão	 [conversão] N F S @SUBJ>
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
trata	 [tratar] V PR 3S IND VFIN @FMV
este	 [este] <dem> DET M S @>N
artigo	 [artigo] N M S @<ACC
será	 [ser] <fmc> V FUT 3S IND VFIN @FMV
precedida	 [precedido] ADJ F S @<SC
de	 [de] PRP @A<
altualização	 [altualização] <DERS> <DERS> N F S @P<
para	 [para] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
rata	 [rato] ADJ F S @>N
tempore ALT xxxe	 [tempore] N F S @P<
$,
desde	 [desde] PRP @<ADVL
a	 [o] <artd> DET F S @>N
data	 [data] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
último	 [último] <NUM-ord> ADJ M S @>N
aniversário	 [aniversário] N M S @P<
até	 [até] PRP @<ADVL
30	 [30] <card> NUM M/F S @P<
de	 [de] PRP @N<
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
inclusive	 [inclusive] ADV @<ADVL
$,
mediante	 [mediante] PRP @<ADVL
a	 [o] <artd> DET F S @>N
aplicação	 [aplicação] N F S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Taxa=Referencial	 [Taxa=Referencial] PROP F S @P<
$	 [$] PU
TR	 [TR] PROP M/F S @APP
$	 [$] PU
ou	 [ou] <co-postnom> KC @CO
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
referencial	 [referencial] <n> <n> ADJ M S @P<
legal	 [legal] ADJ M S @N<
ou	 [ou] <co-postnom> KC @CO
contratual	 [contratual] ADJ M S @N<
pertinente	 [pertinente] ADJ M/F S @N<
$,
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
legislação	 [legislação] N F S @P<
vigente	 [vigente] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @PRED>
2º.	 [2º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Em	 [em] <sam-> PRP @ADVL>
a	 [o] <artd> <-sam> DET F S @>N
data	 [data] N F S @P<
de	 [de] PRP @N<
aniversário	 [aniversário] N M S @P<
em	 [em] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
mês	 [mês] N M S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
$,
incidirá	 [incidir] <fmc> V FUT 3S IND VFIN @FMV
$,
para	 [para] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
rata	 [rato] ADJ F S @>N
tempore ALT xxxe	 [tempore] N F S @P<
$,
desde	 [desde] PRP @<ADVL
a	 [o] <artd> DET F S @>N
data	 [data] N F S @P<
de	 [de] PRP @N<
conversão	 [conversão] N F S @P<
$,
sobre	 [sobre] PRP @<ADVL @<PIV
o	 [o] <artd> DET M S @>N
valor	 [valor] N M S @P<
convertido	 [converter] V PCP M S @N<
$,
a	 [o] <artd> DET F S @>N
Taxa=Referencial	 [Taxa=Referencial] PROP F S @P<
$	 [$] PU
TR	 [TR] PROP M/F S @APP
$	 [$] PU
ou	 [ou] KC @CO
o	 [o] <artd> DET M S @>N
referencial	 [referencial] <n> <n> ADJ M S @P<
legal	 [legal] ADJ M S @N<
ou	 [ou] <co-postnom> KC @CO
contratual	 [contratual] ADJ M S @N<
pertinente	 [pertinente] ADJ M/F S @N<
e	 [e] <co-prparg> KC @CO
juros	 [juro] N M P @P<
$,
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
legislação	 [legislação] N F S @P<
vigente	 [vigente] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @PRED>
3º.	 [3º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O	 [o] <artd> DET M S @>N
crédito	 [crédito] N M S @SUBJ>
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
remuneração	 [remuneração] N F S @P<
básica	 [básico] ADJ F S @N<
e	 [e] <co-postnom> KC @CO
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
juros	 [juro] N M P @P<
$,
no=que=diz=respeito	 [no=que=diz=respeito] ADV @ADVL>
a	 [a] <sam-> PRP @A<
as	 [o] <-sam> <artd> DET F P @>N
cadernetas	 [caderneta] N F P @P<
de	 [de] PRP @N<
poupança	 [poupança] N F S @P<
$,
ocorrerá	 [ocorrer] <fmc> V FUT 3S IND VFIN @FMV
somente	 [somente] ADV @>P
em	 [em] <sam-> PRP @<ADVL
as	 [o] <artd> <-sam> DET F P @>N
datas	 [data] N F P @P<
de	 [de] PRP @N<
aniversário	 [aniversário] N M S @P<
$,
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
são	 [ser] V PR 3P IND VFIN @FAUX
mantidas	 [manter] V PCP F P @IMV @#ICL-AUX<
para	 [para] PRP @<ADVL
todos=os	 [todo=o] <quant> DET M P @>N
efeitos	 [efeito] N M P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
4º.	 [4º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Observadas	 [observar] V PCP F P @IMV @#ICL-N< 
as	 [o] <artd> DET F P @>N
diretrizes	 [diretriz] N F P @SUBJ>
estabelecidas	 [estabelecer] V PCP F P @IMV @#ICL-N<
por	 [por] <sam-> PRP @<PASS
o	 [o] <artd> <-sam> DET M S @>N
presidente	 [presidente] N M S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
República	 [república] <prop> N F S @P<
$,
o	 [o] <artd> DET M S @>N
ministro=da=Fazenda	 [ministro=da=Fazenda] N M S @SUBJ>
$,
o	 [o] <artd> DET M S @>N
Conselho=Monetário=Nacional	 [Conselho=Monetário=Nacional] PROP M S @SUBJ>
$,
o	 [o] <artd> DET M S @>N
Conselho=de=Gestão=da=Previdência=Complementar	 [Conselho=de=Gestão=da=Previdência=Complementar] PROP M S @SUBJ>
e	 [e] <co-subj> KC @CO
o	 [o] <artd> DET M S @>N
Conselho=Nacional=de=Seguros=Privados	 [Conselho=Nacional=de=Seguros=Privados] PROP M S @SUBJ>
$,
dentro=de	 [dentro=de] PRP @ADVL>
suas	 [seu] <si> <poss 3S> DET F P @>N
respectivas	 [respectivo] ADJ F P @>N
competências	 [competência] N F P @P<
$,
regulamentarão	 [regulamentar] <fmc> V FUT 3P IND VFIN @FMV
o	 [o] <artd> DET M S @>N
disposto	 [dispor] <n> V PCP M S @<ACC
em	 [em] <sam-> PRP @<ADVL
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
17º.	 [17º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Os	 [o] <artd> DET M P @>N
valores	 [valor] N M P @SUBJ>
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
prestações	 [prestação] N F P @P<
de	 [de] PRP @N<
financiamentos	 [financiamento] N M P @P<
habitacionais	 [habitacional] ADJ M P @N<
firmados	 [firmar] V PCP M P @IMV @#ICL-N< 
com	 [com] PRP @N<
entidades	 [entidade] N F P @P<
integrantes	 [integrante] ADJ F P @N<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Sistema=Financeiro=da=Habitação	 [Sistema=Financeiro=da=Habitação] PROP M S @P<
$	 [$] PU
SHF	 [SHF] PROP M S @SUBJ>
$	 [$] PU
$,
expressos	 [esprimir] V PCP M P @IMV @#ICL-N<PRED
em	 [em] PRP @<ADVL
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
$,
em	 [em] <sam-> PRP @ADVL>
o	 [o] <artd> <-sam> DET M S @>N
mês	 [mês] N M S @P<
de	 [de] PRP @N<
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
convertidos	 [converter] V PCP M P @IMV @#ICL-AUX<
em	 [em] PRP @<PIV
real	 [real] N M S @P<
$,
em	 [em] <sam-> PRP @<PIV
o	 [o] <artd> <-sam> DET M S @>N
dia	 [dia] N M S @P<
1º	 [1º] <card> NUM M/F P @N<
$.	 [$.] PU <<<
de	 [de] PRP @ADVL>
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
observada	 [observar] V PCP F S @IMV
a	 [o] <artd> DET F S @>N
paridade	 [paridade] N F S @<ACC
entre	 [entre] PRP @<ADVL
o	 [o] <artd> DET M S @>N
cruzeiro	 [cruzeiro] N M S @P<
real	 [real] ADJ M S @N<
e	 [e] <co-prparg> KC @CO
o	 [o] <artd> DET M S @>N
real	 [real] N M S @P<
fixada	 [fixar] V PCP F S @N<
para	 [para] PRP @N<
aquela	 [aquele] <dem> DET F S @>N
data	 [data] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
único	 [único] ADJ M S @N<
$	 [$] PU
São	 [ser] <fmc> V PR 3P IND VFIN @FAUX
mantidos	 [manter] V PCP M P @IMV @#ICL-AUX<
o	 [o] <artd> DET M S @>N
índice	 [índice] N M S @<OC
de	 [de] PRP @N<
reajuste	 [reajuste] N M S @P<
e	 [e] <co-vfin> KC @CO
a	 [o] <artd> DET F S @>N
periodicidade	 [periodicidade] N F S @PRED>
contratualmente	 [contratualmente] ADV @>A
estabelecidos	 [estabelecer] V PCP M P @P<
para	 [para] PRP @<ADVL
atualização	 [atualização] N F S @P<
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
prestações	 [prestação] N F P @P<
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
trata	 [tratar] V PR 3S IND VFIN @FMV
este	 [este] <dem> DET M S @>N
artigo	 [artigo] N M S @<ACC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
18º.	 [18º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Os	 [o] <artd> DET M P @>N
depósitos	 [depósito] N M P @SUBJ>
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
União	 [união] <prop> N F S @P<
em	 [em] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Banco=Central=do=Brasil	 [Banco=Central=do=Brasil] PROP M S @P<
e	 [e] <co-postnom> KC @CO
em	 [em] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
instituições	 [instituição] N F P @P<
financeiras	 [financeiro] ADJ F P @N<
terão	 [ter] <fmc> V FUT 3P IND VFIN @FMV
seu	 [seu] <si> <poss 3S> DET M S @>N
saldo	 [saldo] N M S @<ACC
atualizado	 [atualizar] V PCP M S @N<
por	 [por] <sam-> PRP @<OC
a	 [o] <artd> <-sam> DET F S @>N
taxa	 [taxa] N F S @P<
média	 [médio] ADJ F S @N<
referencial	 [referencial] ADJ F S @N<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Sistema=Especial=de=Liquidação	 [Sistema=Especial=de=Liquidação] PROP M S @P<
e	 [e] <co-acc> KC @CO
de	 [de] PRP @<ADVL
Custódia	 [Custódia] PROP M/F S @P<
$	 [$] PU
Selic	 [Selic] PROP M/F S @<ACC
$	 [$] PU
$,
até	 [até] PRP @<ADVL
30	 [30] <card> NUM M/F S @P<
de	 [de] PRP @N<
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
e	 [e] <co-prparg> KC @CO
convertidos	 [converter] V PCP M P @IMV @#ICL-P<
para	 [para] PRP @<ADVL
real	 [real] N M S @P<
em	 [em] PRP @<ADVL
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
por	 [por] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
paridade	 [paridade] N F S @P<
fixada	 [fixar] V PCP F S @N<
para	 [para] PRP @N<
aquela	 [aquele] <dem> DET F S @>N
data	 [data] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
19º.	 [19º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
As	 [o] <artd> DET F P @>N
obrigações	 [obrigação] N F P @SUBJ>
pecuniárias	 [pecuniário] ADJ F P @N<
em	 [em] PRP @N<
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
$,
sem	 [sem] PRP @N<
cláusula	 [cláusula] N F S @P<
de	 [de] PRP @N<
correção	 [correção] N F S @P<
monetária	 [monetário] ADJ F S @N<
ou	 [ou] <co-postnom> KC @CO
com	 [com] PRP @N<
cláusula	 [cláusula] N F S @P<
de	 [de] PRP @N<
correção	 [correção] N F S @P<
monetária	 [monetário] ADJ F S @N<
prefixada	 [prefixado] ADJ F S @N<
$,
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
convertidas	 [converter] V PCP F P @IMV @#ICL-AUX<
em	 [em] PRP @<PIV
real	 [real] N M S @P<
$,
em	 [em] <sam-> PRP @<PIV
o	 [o] <artd> <-sam> DET M S @>N
dia	 [dia] N M S @P<
1º	 [1º] <card> NUM M/F P @N<
$.	 [$.] PU <<<
de	 [de] PRP @ADVL>
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
observada	 [observar] V PCP F S @IMV
a	 [o] <artd> DET F S @>N
paridade	 [paridade] N F S @<ACC
entre	 [entre] PRP @<ADVL
o	 [o] <artd> DET M S @>N
cruzeiro	 [cruzeiro] N M S @P<
real	 [real] ADJ M S @N<
e	 [e] <co-prparg> KC @CO
o	 [o] <artd> DET M S @>N
real	 [real] N M S @P<
fixada	 [fixar] V PCP F S @N<
para	 [para] PRP @N<
aquela	 [aquele] <dem> DET F S @>N
data	 [data] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
20º.	 [20º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
As	 [o] <artd> DET F P @>N
obrigações	 [obrigação] N F P @SUBJ>
pecuniárias	 [pecuniário] ADJ F P @N<
em	 [em] PRP @N<
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
$,
com	 [com] PRP @N<PRED @ADVL>
cláusula	 [cláusula] N F S @P<
de	 [de] PRP @N<
correção	 [correção] N F S @P<
monetária	 [monetário] ADJ F S @N<
baseada	 [baseado] ADJ F S @N<
em	 [em] PRP @A<
índices	 [índice] N M P @P<
de	 [de] PRP @N<
preços	 [preço] N M P @P<
$,
em	 [em] PRP @ADVL>
que	 [que] KS @SUB @#FS-<ACC
a	 [o] <artd> DET F S @>N
periodicidade	 [periodicidade] N F S @SUBJ>
de	 [de] PRP @N<
reajuste	 [reajuste] N M S @P<
pleno	 [pleno] ADJ M S @N<
é	 [ser] V PR 3S IND VFIN @FMV
igual	 [igual] ADJ F S @<SC
ou	 [ou] <co-sc> KC @CO
menor	 [pequeno] <KOMP> ADJ F S @<SC
que	 [que] KS @COM @#AS-KOMP<
a	 [o] <artd> DET F S @>N
periodicidade	 [periodicidade] N F S @AS<
de	 [de] PRP @N<
pagamento	 [pagamento] N M S @P<
$,
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
convertidas	 [converter] V PCP F P @IMV @#ICL-AUX<
em	 [em] PRP @<PIV
real	 [real] N M S @P<
$,
em	 [em] <sam-> PRP @<PIV
o	 [o] <artd> <-sam> DET M S @>N
dia	 [dia] N M S @P<
1º	 [1º] <card> NUM M/F P @N<
$.	 [$.] PU <<<
de	 [de] PRP @ADVL>
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
observada	 [observar] V PCP F S @IMV
a	 [o] <artd> DET F S @>N
paridade	 [paridade] N F S @<ACC
fixada	 [fixar] V PCP F S @IMV @#ICL-N< 
para	 [para] PRP @<ADVL
aquela	 [aquele] <dem> DET F S @>N
data	 [data] N F S @P<
$,
reajustando-	 [reajustar] <hyfen> V GER @IMV @#ICL-<ADVL
se	 [se] PERS M/F 3S/P ACC @<SUBJ
para	 [para] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
rata	 [rato] ADJ F S @>N
tempore ALT xxxe	 [tempore] N F S @P<
os	 [o] <artd> DET M P @>N
valores	 [valor] N M P @<ACC
contratuais	 [contratual] ADJ M P @N<
expressos	 [esprimir] V PCP M P @IMV @#ICL-N<
em	 [em] PRP @<ADVL
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
desde	 [desde] PRP @N<
o	 [o] <artd> DET M S @>N
último	 [último] <NUM-ord> ADJ M S @>N
aniversário	 [aniversário] N M S @P<
até	 [até] PRP @<ADVL
o	 [o] <artd> DET M S @>N
dia	 [dia] N M S @P<
30	 [30] <card> NUM M/F P @N<
de	 [de] PRP @N<
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
inclusive	 [inclusive] ADV @<ADVL
$,
de=acordo	 [de=acordo] ADV @<ADVL
com	 [com] PRP @A<
o	 [o] <artd> DET M S @>N
índice	 [índice] N M S @P<
constante	 [constante] ADJ M S @N<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
contrato	 [contrato] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
21º.	 [21º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
As	 [o] <artd> DET F P @>N
obrigações	 [obrigação] N F P @SUBJ>
pecuniárias	 [pecuniário] ADJ F P @N<
em	 [em] PRP @N<
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
$,
com	 [com] PRP @N<PRED @ADVL>
cláusula	 [cláusula] N F S @P<
de	 [de] PRP @N<
correção	 [correção] N F S @P<
monetária	 [monetário] ADJ F S @N<
baseada	 [baseado] ADJ F S @N<
em	 [em] PRP @A<
índices	 [índice] N M P @P<
de	 [de] PRP @N<
preços	 [preço] N M P @P<
$,
em	 [em] PRP @ADVL>
que	 [que] KS @SUB @#FS-<ACC
a	 [o] <artd> DET F S @>N
periodicidade	 [periodicidade] N F S @SUBJ>
de	 [de] PRP @N<
reajuste	 [reajuste] N M S @P<
pleno	 [pleno] ADJ M S @N<
é	 [ser] V PR 3S IND VFIN @FMV
maior	 [grande] <KOMP> ADJ F S @<SC
que	 [que] KS @COM @#AS-KOMP<
a	 [o] <artd> DET F S @>N
periodicidade	 [periodicidade] N F S @AS<
de	 [de] PRP @N<
pagamento	 [pagamento] N M S @P<
$,
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
convertidas	 [converter] V PCP F P @IMV @#ICL-AUX<
em	 [em] PRP @<PIV
real	 [real] N M S @P<
$,
em	 [em] <sam-> PRP @<PIV
o	 [o] <artd> <-sam> DET M S @>N
dia	 [dia] N M S @P<
1º	 [1º] <card> NUM M/F P @N<
$.	 [$.] PU <<<
de	 [de] PRP @ADVL
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
de=acordo	 [de=acordo] ADV @ADVL
com	 [com] PRP @A<
as	 [o] <artd> DET F P @>N
disposições	 [disposição] N F P @P<
abaixo	 [abaixo] ADV @N<PRED
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
I	 [i] N M S @SUBJ>
$	 [$] PU
dividindo-	 [dividir] <hyfen> V GER @IMV @#ICL-ADVL
se	 [se] PERS M 3S/P ACC @<ACC-PASS
o	 [o] <artd> DET M S @>N
valor	 [valor] N M S @NPHR
em	 [em] PRP @<PIV
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
obrigação	 [obrigação] N F S @P<
vigente	 [vigente] ADJ F S @N<
em	 [em] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
dia	 [dia] N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
aniversário	 [aniversário] N M S @P<
em	 [em] PRP @N<
cada=um	 [cada=um] SPEC M/F S @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
meses	 [mês] N M P @P<
imediatamente	 [imediatamente] ADV @<ADVL
anteriores	 [anterior] ADJ M/F P @NPHR
$,
em	 [em] PRP @<ADVL
número	 [número] N M S @P<
igual	 [igual] ADJ M S @N<
a	 [a] <sam-> PRP @A<
os	 [o] <dem> <-sam> DET M P @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
último	 [último] <NUM-ord> ADJ M S @>N
período	 [período] N M S @P<
de	 [de] PRP @N<
reajuste	 [reajuste] N M S @P<
pleno	 [pleno] ADJ M S @N<
$,
por	 [por] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
valor	 [valor] N M S @P<
em	 [em] PRP @<ADVL
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
equivalente	 [equivalente] N M S @P<
em	 [em] PRP @<ADVL
URV	 [uRV] <prop> N F S @P<
em	 [em] <sam-> PRP @<ADVL
esses	 [esse] <dem> <-sam> DET M P @>N
mesmos	 [mesmo] <diff> <KOMP> DET M P @>N
dias	 [dia] N M P @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
II	 [II] <NUM-ord> ADJ M/F S @SUBJ>
$	 [$] PU
extraindo-	 [extrair] <hyfen> V GER @IMV @#ICL-ADVL
se	 [se] PERS M/F 3S/P ACC @<ACC-PASS
a	 [o] <artd> DET F S @>N
média=aritmética	 [média=aritmética] N F S @NPHR
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
valores	 [valor] N M P @P<
resultantes	 [resultante] ADJ M P @N<
de	 [de] <sam-> PRP @A<
o	 [o] <artd> <-sam> DET M S @>N
inciso	 [inciso] N M S @P<
anterior	 [anterior] ADJ M S @N<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
III	 [III] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
reconvertendo-	 [reconverter] <hyfen> V GER @IMV @#ICL-ADVL
se	 [se] PERS M/F 3S/P ACC @<SUBJ @<ACC-PASS
$,
em	 [em] PRP @<ADVL
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
$,
o	 [o] <artd> DET M S @>N
valor	 [valor] N M S @<SUBJ @APP
encontrado	 [encontrar] V PCP M S @IMV @#ICL-N<
por	 [por] <sam-> PRP @<PASS
a	 [o] <artd> <-sam> DET F S @>N
URV	 [uRV] <prop> N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
dia	 [dia] N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
aniversário	 [aniversário] N M S @P<
em	 [em] PRP @<ADVL
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
IV	 [IV] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
aplicando-	 [aplicar] <hyfen> V GER @IMV @#ICL-ADVL
se	 [se] <refl> PERS M/F 3S/P ACC @<ACC
$,
para	 [para] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
rata	 [rato] ADJ F S @>N
tempore ALT xxxe	 [tempore] N F S @P<
$,
sobre	 [sobre] PRP @<ADVL @<PIV
o	 [o] <artd> DET M S @>N
valor	 [valor] N M S @P<
em	 [em] PRP @<ADVL
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
trata	 [tratar] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
inciso	 [inciso] N M S @<ACC
anterior	 [anterior] ADJ M S @N<
o	 [o] <artd> DET M S @>N
índice	 [índice] N M S @<ACC
contratual	 [contratual] ADJ M S @N<
ou	 [ou] <co-postnom> KC @CO
legal	 [legal] ADJ M S @N<
até	 [até] PRP @<ADVL
30	 [30] <card> NUM M/F S @P<
de	 [de] PRP @N<
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$;	 [$;] PU <<<
e	 [e] KC @CO
$¶	 [$¶] PU <<<
</s>
<s>
V	 [v] N M S @SUBJ>
$	 [$] PU
convertendo-	 [converter] <hyfen> V GER @IMV @#ICL-ADVL
se	 [se] PERS M 3S/P ACC @<ACC-PASS
em	 [em] PRP @<PIV
real	 [real] N M S @P<
o	 [o] <artd> DET M S @>N
valor	 [valor] N M S @NPHR
corrigido	 [corrigir] V PCP M S @IMV @#ICL-N<
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
inciso	 [inciso] N M S @P<
anterior	 [anterior] ADJ M S @N<
por	 [por] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
paridade	 [paridade] N F S @P<
fixada	 [fixar] V PCP F S @N<
para	 [para] PRP @N<
aquela	 [aquele] <dem> DET F S @>N
data	 [data] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O	 [o] <artd> DET M S @>N
cálculo	 [cálculo] N M S @SUBJ>
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
média	 [média] N F S @P<
a	 [a] PRP @PIV>
que	 [que] KS @SUB @#FS-<ACC
se	 [se] PERS M/F 3S/P ACC @SUBJ>
refere	 [referir] V PR 3S IND VFIN @FMV
este	 [este] <dem> DET M S @>N
artigo	 [artigo] N M S @<ACC
será	 [ser] <fmc> V FUT 3S IND VFIN @FAUX
feito	 [fazer] V PCP M S @IMV @#ICL-AUX<
com	 [com] PRP @<ADVL
base	 [base] N F S @P<
em	 [em] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
preços	 [preço] N M P @P<
unitários	 [unitário] ADJ M P @N<
$,
em	 [em] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
casos	 [caso] N M P @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
contratos	 [contrato] N M P @P<
para	 [para] PRP @<ADVL
aquisição	 [aquisição] N F S @P<
ou	 [ou] <co-prparg> KC @CO
produção	 [produção] N F S @<ACC @P<
de	 [de] PRP @N<
bens	 [bem] N M P @P<
para	 [para] PRP @<ADVL
entrega	 [entrega] N F S @P<
futura	 [futuro] ADJ F S @N<
$,
execução	 [execução] N F S @<ACC @P<
de	 [de] PRP @N<
obras	 [obra] N F P @P<
$,
prestação	 [prestação] N F S @<ACC @P<
de	 [de] PRP @N<
serviços	 [serviço] N M P @P<
$,
locação	 [locação] N F S @<ACC @P<
$,
uso	 [uso] N M S @<ACC @P<
e	 [e] <co-prparg> KC @CO
arrendamento	 [arrendamento] N M S @<ACC @P<
$,
quando	 [quando] <rel> ADV @ADVL> @#AS-<ADVL
as	 [o] <artd> DET F P @>N
quantidades	 [quantidade] N F P @AS<
de	 [de] PRP @N<
bens	 [bem] N M P @P<
e	 [e] <co-prparg> KC @CO
serviços	 [serviço] N M P @P<
$,
a	 [a] PRP @ADVL>
cada	 [cada] <quant> DET M S @>N
mês	 [mês] N M S @P<
$,
forem	 [ser] <fmc> V FUT 3P SUBJ VFIN @FMV
variáveis	 [variável] ADJ M/F P @<SC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
2º.	 [2º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
No=caso=de	 [no=caso=de] PRP @ADVL>
obrigações	 [obrigação] N F P @P<
em	 [em] PRP @ADVL>
que	 [que] KS @SUB @#FS-<ACC
tenha	 [ter] V PR 3S SUBJ VFIN @FAUX
transcorrido	 [transcorrer] V PCP @IMV @#ICL-AUX<
um	 [um] <arti> DET M S @>N
número	 [número] N M S @<SUBJ
de	 [de] PRP @N<
meses	 [mês] N M P @P<
menor	 [pequeno] <KOMP> ADJ M S @N<
que	 [que] KS @COM @#AS-KOMP<
o	 [o] <dem> DET M S @AS<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
periodicidade	 [periodicidade] N F S @P<
de	 [de] PRP @N<
reajuste	 [reajuste] N M S @P<
pleno	 [pleno] ADJ M S @N<
$,
a	 [o] <artd> DET F S @>N
conversão	 [conversão] N F S @SUBJ>
será	 [ser] <fmc> V FUT 3S IND VFIN @FAUX
feita	 [fazer] V PCP F S @IMV @#ICL-AUX<
$,
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
caput ALT xxx	 [caput] N M S @P<
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$,
levando-	 [levar] <hyfen> V GER @IMV @#ICL-<ADVL
se	 [se] PERS M/F 3S/P ACC @<SUBJ
em=conta	 [em=conta] ADJ @N<
apenas	 [apenas] ADV @>N
os	 [o] <artd> DET M P @>N
valores	 [valor] N M P @<ACC
referentes	 [referente] N M P @PRED>
a	 [a] <sam-> PRP @<PIV
os	 [o] <-sam> <artd> DET M P @>N
meses	 [mês] N M P @P<
a=partir=de	 [a=partir=de] <sam-> PRP @<ADVL
a	 [o] <-sam> <artd> DET F S @>N
contratação	 [contratação] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
3º.	 [3º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
No=caso=de	 [no=caso=de] <sam-> PRP @ADVL>
os	 [o] <-sam> <artd> DET M P @>N
contratos	 [contrato] N M P @P<
de	 [de] PRP @N<
locação	 [locação] N F S @P<
residencial	 [residencial] ADJ F S @N<
com	 [com] PRP @N<
cláusula	 [cláusula] N F S @P<
de	 [de] PRP @N<
reajuste	 [reajuste] N M S @P<
superior	 [alto] <SUP> <KOMP> ADJ M S @N<
a	 [a] PRP @A<
6	 [6] <card> NUM M/F P @>N
$(	 [$(] PU
seis	 [seis] <card> NUM M/F P @SUBJ>
$)	 [$)] PU
meses	 [mês] N M P @SUBJ>
$,
as	 [o] <artd> DET F P @>N
disposições	 [disposição] N F P @SUBJ>
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
caput ALT xxx	 [caput] N M S @P<
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
aplicadas	 [aplicar] V PCP F P @IMV @#ICL-AUX<
tomando	 [tomar] V GER @IMV @#ICL-<ADVL @#ICL-N<
em=conta	 [em=conta] ADV @<ADVL
apenas	 [apenas] ADV @>N
os	 [o] <artd> DET M P @>N
aluguéis	 [aluguel] N M P @<ACC
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
primeiros	 [primeiro] <NUM-ord> ADJ M P @>N
6	 [6] <card> NUM M P @>N
$(	 [$(] PU
seis	 [seis] <card> NUM M/F P @P<
$)	 [$)] PU
meses	 [mês] N M P @PRED>
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
último	 [último] <NUM-ord> ADJ M S @>N
período	 [período] N M S @P<
de	 [de] PRP @N<
reajuste	 [reajuste] N M S @P<
pleno	 [pleno] ADJ M S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
4º.	 [4º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Em	 [em] PRP @ADVL>
caso	 [caso] N M S @P<
de	 [de] PRP @N<
desequilíbrio	 [desequilíbrio] N M S @P<
econômico-financeiro	 [econômico-financeiro] ADJ M S @N<
$,
os	 [o] <artd> DET M P @>N
contratos	 [contrato] N M P @APP
de	 [de] PRP @N<
locação	 [locação] N F S @P<
residencial	 [residencial] ADJ F S @N<
$,
inclusive	 [inclusive] ADV @>N
os	 [o] <artd> DET M P @>N
convertidos	 [converter] <n> V PCP M P @APP
anteriormente	 [anteriormente] ADV @ADVL>
$,
poderão	 [poder] <fmc> V FUT 3P IND VFIN @FAUX
ser	 [ser] V INF @IAUX @#ICL-AUX<
revistos	 [rever] V PCP M P @IMV @#ICL-AUX<
$,
a=partir=de	 [a=partir=de] PRP @<ADVL
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
janeiro	 [janeiro] N M S @P<
de	 [de] PRP @N<
1995	 [1995] <card> NUM M/F P @P<
$,
através	 [através] ADV @<ADVL
de	 [de] PRP @A<
livre	 [livre] ADJ F S @>N
negociação	 [negociação] N F S @P<
entre	 [entre] PRP @N< @<ADVL
as	 [o] <artd> DET F P @>N
partes	 [parte] N F P @P<
$,
ou	 [ou] <co-advl> KC @CO
judicialmente	 [judicialmente] ADV @<ADVL
$,
a=fim=de	 [a=fim=de] PRP @<ADVL
adequar-	 [adequar] <hyfen> V INF @IMV @#ICL-P<
los	 [eles] PERS M 3P ACC @<ACC
a	 [a] <sam-> PRP @<PIV
os	 [o] <-sam> <artd> DET M P @>N
preços	 [preço] N M P @P<
de	 [de] PRP @N<
mercado	 [mercado] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @PRED>
5º.	 [5º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Efetivada	 [efetivar] V PCP F S @N<
a	 [o] <artd> DET F S @>N
revisão	 [revisão] N F S @SUBJ>
$,
o	 [o] <artd> DET M S @>N
novo	 [novo] ADJ M S @>N
valor	 [valor] N M S @SUBJ>
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
aluguel	 [aluguel] N M S @P<
residencial	 [residencial] ADJ M S @N<
vigorará	 [vigorar] <fmc> V FUT 3S IND VFIN @FMV
por	 [por] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
prazo	 [prazo] N M S @P<
mínimo	 [pequeno] <SUP> ADJ M S @N<
de	 [de] PRP @N<
um	 [um] <card> NUM M S @>N
ano	 [ano] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
22º.	 [22º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Para	 [para] PRP @ADVL>
os	 [o] <artd> DET M P @>N
efeitos	 [efeito] N M P @P<
de	 [de] <sam-> PRP @N<
esta	 [este] <dem> <-sam> DET F S @>N
medida	 [medida] N F S @P<
provisória	 [provisório] ADJ F S @N<
$,
dia	 [dia] <*1> N M S @SUBJ>
de	 [de] PRP @N<
aniversário	 [aniversário] <*2> N M S @P<
corresponde	 [corresponder] <fmc> V PR 3S IND VFIN @FMV
a	 [a] <sam-> PRP @<PIV
o	 [o] <-sam> <artd> DET M S @>N
dia	 [dia] N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
vencimento	 [vencimento] N M S @P<
$;	 [$;] PU <<<
em	 [em] <sam-> PRP @ADVL>
a	 [o] <artd> <-sam> DET F S @>N
falta	 [falta] N F S @P<
deste	 [dar] <fmc> V PS 2S IND VFIN @FMV
$,
o	 [o] <artd> DET M S @>N
dia	 [dia] N M S @PRED>
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
último	 [último] <NUM-ord> ADJ M S @>N
reajuste	 [reajuste] N M S @P<
$;	 [$;] PU <<<
e	 [e] KC @CO
$,
em	 [em] <sam-> PRP @ADVL>
a	 [o] <artd> <-sam> DET F S @>N
falta	 [falta] N F S @P<
deste	 [dar] <fmc> V PS 2S IND VFIN @FMV
$,
a	 [a] <sam-> PRP @<ADVL
o	 [o] <-sam> <artd> DET M S @>N
dia	 [dia] N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
surgimento	 [surgimento] N M S @P<
$,
em	 [em] PRP @<PIV
qualquer	 [qualquer] <quant> DET M S @>N
mês	 [mês] N M S @P<
$,
de	 [de] <sam-> PRP @N<PRED
a	 [o] <artd> <-sam> DET F S @>N
obrigação	 [obrigação] N F S @P<
$,
de	 [de] <sam-> PRP @N<PRED
o	 [o] <artd> <-sam> DET M S @>N
título	 [título] N M S @P<
$,
de	 [de] <sam-> PRP @N<PRED
o	 [o] <artd> <-sam> DET M S @>N
contrato	 [contrato] N M S @P<
ou	 [ou] <co-pred> KC @CO
de	 [de] <sam-> PRP @<PRED
a	 [o] <artd> <-sam> DET F S @>N
parcela	 [parcela] N F S @P<
contratual	 [contratual] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
23º.	 [23º.] <NUM-ord> ADJ M/F S @SUBJ>
$	 [$] PU
As	 [o] <artd> DET F P @>N
disposições	 [disposição] N F P @SUBJ>
de	 [de] <sam-> PRP @N<
esta	 [este] <dem> <-sam> DET F S @>N
medida	 [medida] N F S @P<
provisória	 [provisório] ADJ F S @N<
sobre	 [sobre] PRP @N<
conversões	 [conversão] N F P @P<
aplicam-	 [aplicar] <hyfen> <fmc> V PR 3P IND VFIN @FMV
se	 [se] <refl> PERS M/F 3P ACC @<ACC-PASS
a	 [a] <sam-> PRP @<PIV
os	 [o] <-sam> <artd> DET M P @>N
contratos	 [contrato] N M P @P<
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
trata	 [tratar] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
art.	 [art.] N M S @<ACC
15º	 [15º] <card> NUM M/F P @N< @<ACC
$.	 [$.] PU <<<
de	 [de] <sam-> PRP @ADVL
a	 [o] <artd> <-sam> DET F S @>N
lei	 [lei] N F S @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.880	 [8.880] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
27	 [27] <card> NUM M/F P @P<
de	 [de] PRP @N<
maio	 [maio] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
e	 [e] KC @CO
sua	 [seu] <poss 3S> DET F S @>N
regulamentação	 [regulamentação] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Em	 [em] <sam-> PRP @ADVL>
a	 [o] <artd> <-sam> DET F S @>N
conversão	 [conversão] N F S @P<
em	 [em] PRP @N<
real	 [real] N M S @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
contratos	 [contrato] N M P @P<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
não	 [não] ADV @ADVL>
contiverem	 [conter] V FUT 3P SUBJ VFIN @FMV
cláusula	 [cláusula] N F S @<ACC
de	 [de] PRP @N<
atualização	 [atualização] N F S @P<
monetária	 [monetário] ADJ F S @N<
entre	 [entre] PRP @N<
a	 [o] <artd> DET F S @>N
data	 [data] N F S @P<
final	 [final] ADJ F S @N<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
período	 [período] N M S @P<
de	 [de] PRP @N<
adimplemento	 [adimplemento] N M S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
obrigação	 [obrigação] N F S @P<
e	 [e] <co-prparg> KC @CO
a	 [o] <artd> DET F S @>N
data	 [data] N F S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
exigibilidade	 [exigibilidade] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
pagamento	 [pagamento] N M S @P<
será	 [ser] <fmc> V FUT 3S IND VFIN @FAUX
deduzida	 [deduzir] V PCP F S @IMV @#ICL-AUX<
a	 [o] <artd> DET F S @>N
expectativa	 [expectativa] N F S @<SUBJ
de	 [de] PRP @N<
inflação	 [inflação] N F S @P<
considerada	 [considerar] V PCP F S @IMV @#ICL-N<
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
contrato	 [contrato] N M S @P<
relativamente=a	 [relativamente=a] PRP @N< @<ADVL
este	 [este] <dem> DET M S @>N
prazo	 [prazo] N M S @P<
$,
devendo	 [dever] V GER @IMV @#ICL-<ADVL
$,
quando	 [quando] <rel> <ks> ADV @ADVL> @#FS-<ADVL
o	 [o] <artd> DET M S @>N
contrato	 [contrato] N M S @SUBJ>
não	 [não] ADV @ADVL>
mencionar	 [mencionar] V FUT 3S SUBJ VFIN @FMV
explicitamente	 [explícito] ADV @<ADVL
a	 [o] <artd> DET F S @>N
expectativa	 [expectativa] N F S @<ACC
inflacionária	 [inflacionário] ADJ F S @N<
$,
ser	 [ser] V INF @IMV
adotada	 [adotar] V PCP F S @IMV
para	 [para] PRP @<ADVL
a	 [o] <artd> DET F S @>N
dedução	 [dedução] N F S @P<
a	 [o] <artd> DET F S @>N
variação	 [variação] N F S @<SUBJ
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Índice=Geral=de=Preços	 [Índice=Geral=de=Preços] PROP M S @P<
$	 [$] PU
Disponibilidade=Interna	 [Disponibilidade=Interna] PROP F S @<ACC
$	 [$] PU
IGP	 [IGP] PROP M S @<SC
$/	 [$/] PU	 [$/] <co-sc> KC @CO
DI	 [DI] PROP M S @<SC
$,
de	 [de] <sam-> PRP @N<PRED
a	 [o] <artd> <-sam> DET F S @>N
Fundação=Getúlio=Vargas	 [Fundação=Getúlio=Vargas] PROP F S @P<
$	 [$] PU
FGV	 [FGV] PROP M S @<SC
$	 [$] PU
$,
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
mês	 [mês] N M S @P<
de	 [de] PRP @N<
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
aplicado	 [aplicar] V PCP M S @N<PRED @P<
para	 [para] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
rata	 [rato] ADJ F S @>N
tempore ALT xxxe	 [tempore] N F S @P<
relativamente=a	 [relativamente=a] <sam-> PRP @<ADVL
o	 [o] <-sam> <artd> DET M S @>N
prazo	 [prazo] N M S @P<
previsto	 [prever] V PCP M S @N<
para	 [para] PRP @N<
o	 [o] <artd> DET M S @>N
pagamento	 [pagamento] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
2º	 [2º] <NUM-ord> ADJ M S @N<
$	 [$] PU
Em	 [em] <sam-> PRP @ADVL>
os	 [o] <artd> <-sam> DET M P @>N
casos	 [caso] N M P @P<
em	 [em] PRP @ADVL>
que	 [que] KS @SUB @#FS-<ACC
houver	 [haver] V FUT 3S SUBJ VFIN @FMV
cláusula	 [cláusula] N F S @<ACC
de	 [de] PRP @N<
atualização	 [atualização] N F S @P<
monetária	 [monetário] ADJ F S @N<
decorrente	 [decorrente] ADJ F S @N<
de	 [de] PRP @A<
atraso	 [atraso] N M S @P<
de	 [de] PRP @N<
pagamento	 [pagamento] N M S @P<
$,
corrigido	 [corrigir] V PCP M S @SUBJ>
também	 [também] ADV @>N
o	 [o] <artd> DET M S @>N
período	 [período] N M S @SUBJ> @<ACC
decorrido	 [decorrer] V PCP M S @IMV
entre	 [entre] PRP @<ADVL
a	 [o] <artd> DET F S @>N
data	 [data] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
adimplemento	 [adimplemento] N M S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
obrigação	 [obrigação] N F S @P<
e	 [e] <co-postnom> KC @CO
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
exigibilidade	 [exigibilidade] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
pagamento	 [pagamento] N M S @P<
$,
aplica-	 [aplicar] <hyfen> <fmc> V PR 3S IND VFIN @FMV
se	 [se] <refl> PERS M 3S ACC @<ACC-PASS
a	 [a] PRP @<PIV
este	 [este] <dem> DET M S @>N
período	 [período] N M S @P<
a	 [o] <artd> DET F S @>N
dedução	 [dedução] N F S @<SUBJ
referida	 [referir] V PCP F S @IMV @#ICL-N<
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
parágrafo	 [parágrafo] N M S @P<
anterior	 [anterior] ADJ M S @N<
$,
segundo	 [segundo] <prp> <rel> ADV @COM @#AS-<ADVL
os	 [o] <artd> DET M P @>N
critérios	 [critério] N M P @AS<
em	 [em] <sam-> PRP @ADVL>
ele	 [ele] <-sam> PERS M 3S NOM/PIV @P<
estabelecidos	 [estabelecer] V PCP M P @IMV @#ICL-N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
3º.	 [3º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O=Poder=Executivo	 [O=Poder=Executivo] PROP M S @SUBJ>
regulamentará	 [regulamentar] <fmc> V FUT 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
disposto	 [dispor] <n> V PCP M S @<ACC
em	 [em] <sam-> PRP @<ADVL
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
4º.	 [4º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Em	 [em] <sam-> PRP @ADVL>
a	 [o] <artd> <-sam> DET F S @>N
regulamentação	 [regulamentação] N F S @P<
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
trata	 [tratar] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
parágrafo	 [parágrafo] N M S @<ACC
anterior	 [anterior] ADJ M S @N<
o	 [o] <artd> DET M S @>N
Poder=Executivo	 [Poder=Executivo] PROP M S @<ACC
aplicará	 [aplicar] <fmc> V FUT 3S IND VFIN @FMV
a	 [o] <artd> DET F S @>N
correção	 [correção] N F S @<ACC
para	 [para] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
rata	 [rato] ADJ F S @>N
tempore ALT xxxe	 [tempore] N F S @P<
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
tratam	 [tratar] V PR 3P IND VFIN @FMV
os	 [o] <artd> DET M P @>N
artigos	 [artigo] N M P @<ACC
20	 [20] <card> NUM M/F P @N<
e	 [e] <co-postnom> KC @CO
21	 [21] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
esta	 [este] <dem> <-sam> DET F S @>N
medida	 [medida] N F S @P<
provisória	 [provisório] ADJ F S @N<
$,
quando	 [quando] <rel> <ks> ADV @ADVL> @#FS-<ADVL
os	 [o] <artd> DET M P @>N
reajustes	 [reajuste] N M P @SUBJ>
previstos	 [prever] V PCP M P @IMV @#ICL-N<
em	 [em] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
contratos	 [contrato] N M P @P<
não	 [não] ADV @ADVL>
incidirem	 [incidir] V FUT 3P SUBJ VFIN @FMV
em	 [em] <sam-> PRP @<PIV
o	 [o] <artd> <-sam> DET M S @>N
primeiro	 [primeiro] <NUM-ord> ADJ M S @>N
dia	 [dia] N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
mês	 [mês] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
24º.	 [24º.] <NUM-ord> ADJ M/F S @NPHR
$	 [$] PU
Em	 [em] <sam-> PRP @ADVL
as	 [o] <artd> <-sam> DET F P @>N
obrigações	 [obrigação] N F P @P<
convertidas	 [converter] V PCP F P @IMV @#ICL-N<
em	 [em] PRP @<PIV
real	 [real] N M S @P<
em	 [em] <sam-> PRP @ADVL>
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
arts ALT xxxs	 [art] N M P @P<
$.	 [$.] PU <<<
20	 [20] <card> NUM M P @>N
e	 [e] <co-prenom> KC @CO
21	 [21] <card> NUM M P @>N
$,
o	 [o] <artd> DET M S @>N
cálculo	 [cálculo] N M S @SUBJ>
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
correção	 [correção] N F S @P<
monetária	 [monetário] ADJ F S @N<
a=partir=de	 [a=partir=de] PRP @N<
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
somente	 [somente] ADV @ADVL>
é	 [ser] <fmc> V PR 3S IND VFIN @FMV
válido	 [válido] ADJ M S @<SC
quando	 [quando] <rel> ADV @ADVL @#AS-<ADVL
baseado	 [baseado] ADJ M S @AS<
em	 [em] PRP @A<
índice	 [índice] N M S @P<
de	 [de] PRP @N<
preços	 [preço] N M P @P<
calculado	 [calcular] V PCP M S @IMV @#ICL-N<
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
art.	 [art.] N M S @P<
38	 [38] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
lei	 [lei] N F S @P<
nº	 [nº] N M S @<ACC
$.	 [$.] PU <<<
8.880	 [8.880] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
27	 [27] <card> NUM M/F P @P<
de	 [de] PRP @N<
maio	 [maio] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O	 [o] <artd> DET M S @>N
cálculo	 [cálculo] N M S @SUBJ>
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
índices	 [índice] N M P @P<
de	 [de] PRP @N<
correção	 [correção] N F S @P<
monetária	 [monetário] ADJ F S @N<
de	 [de] PRP @N<
obrigações	 [obrigação] N F P @P<
a	 [a] PRP @PIV>
que	 [que] KS @SUB @#FS-<ACC
se	 [se] PERS M/F 3S/P ACC @SUBJ>
refere	 [referir] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
caput ALT xxx	 [caput] N M S @<ACC
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
tomará	 [tomar] <fmc> V FUT 3S IND VFIN @FMV
por	 [por] PRP @<PIV
base	 [base] N F S @P<
preços	 [preço] N M P @<ACC
em	 [em] PRP @<ADVL
real	 [real] N M S @P<
$,
o	 [o] <artd> DET M S @>N
equivalente	 [equivalente] N M S @APP
em	 [em] PRP @N<
URV	 [uRV] <prop> N F S @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
preços	 [preço] N M P @P<
em	 [em] PRP @<ADVL
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
$,
e	 [e] <co-acc> KC @CO
os	 [o] <artd> DET M P @>N
preços	 [preço] N M P @<ACC
nominados	 [nominar] V PCP M P @IMV @#ICL-N< 
ou	 [ou] <co-postnom> KC @CO
convertidos	 [converter] V PCP M P @IMV @#ICL-N<
em	 [em] PRP @<ADVL
URV	 [uRV] <prop> N F S @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
meses	 [mês] N M P @P<
anteriores	 [anterior] ADJ M P @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @NPHR
2º.	 [2º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Observado	 [observar] V PCP M S @N<
o	 [o] <artd> DET M S @>N
disposto	 [dispor] <n> V PCP M S @NPHR
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
art.	 [art.] N M S @P<
28	 [28] <card> NUM M/F P @N<
$,
sobre	 [sobre] PRP @ADVL
o	 [o] <artd> DET M S @>N
valores	 [valor] N M P @P<
convertidos	 [converter] V PCP M P @IMV @#ICL-N<
em	 [em] PRP @<PIV
real	 [real] N M S @P<
$,
em	 [em] <sam-> PRP @ADVL
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
arts ALT xxxs	 [art] N M P @P<
$.	 [$.] PU <<<
20	 [20] <card> NUM M/F P @SUBJ>
e	 [e] <co-subj> KC @CO
21	 [21] <card> NUM M/F P @SUBJ>
$,
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
aplicados	 [aplicar] V PCP M P @IMV @#ICL-AUX<
para	 [para] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
rata	 [rato] ADJ F S @>N
tempore ALT xxxe	 [tempore] N F S @P<
$,
de	 [de] <sam-> PRP @N<PRED
a	 [o] <artd> <-sam> DET F S @>N
data	 [data] N F S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
conversão	 [conversão] N F S @P<
até	 [até] PRP @<ADVL
a	 [o] <artd> DET F S @>N
data	 [data] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
aniversário	 [aniversário] N M S @P<
$,
os	 [o] <artd> DET M P @>N
índices	 [índice] N M P @APP
de	 [de] PRP @N<
correção	 [correção] N F S @P<
monetária	 [monetário] ADJ F S @N<
a	 [a] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
estiverem	 [estar] V FUT 3P SUBJ VFIN @FMV
sujeitos	 [sujeito] N M P @<SC
$,
calculados	 [calcular] V PCP M P @N<PRED
de	 [de] PRP @<SC @N<PRED
conformidade	 [conformidade] N F S @P<
com	 [com] PRP @<SC @<PRED @<ADVL
o	 [o] <artd> DET M S @>N
art.	 [art.] N M S @P<
38	 [38] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
lei	 [lei] N F S @P<
nº	 [nº] N M S @<PRED
$.	 [$.] PU <<<
8.880	 [8.880] <card> NUM M/F P @P<
$,
de	 [de] PRP @N<PRED
27	 [27] <card> NUM M/F P @P<
de	 [de] PRP @N<
maio	 [maio] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
de=acordo	 [de=acordo] ADV @ADVL>
com	 [com] PRP @A<
as	 [o] <artd> DET F P @>N
respectivas	 [respectivo] ADJ F P @>N
disposições	 [disposição] N F P @P<
legais	 [legal] ADJ F P @N<
$,
regulamentares	 [regulamentar] ADJ M/F P @N<PRED
$,
contratuais	 [contratual] ADJ M/F P @N<PRED
$,
ou	 [ou] <co-pred> KC @CO
decisões	 [decisão] N F P @N<PRED
judiciais	 [judicial] ADJ F P @N<
com	 [com] PRP @N<
base	 [base] N F S @P<
em	 [em] <sam-> PRP @ADVL> @N<PRED
as=quais	 [o=qual] <rel> <-sam> SPEC F P @P< @#FS-N<
tiverem	 [ter] V FUT 3P SUBJ VFIN @FAUX
sido	 [ser] V PCP @IAUX @#ICL-AUX<
constituídos	 [constituir] V PCP M P @IMV @#ICL-AUX<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
3º.	 [3º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Em	 [em] <sam-> PRP @ADVL>
o	 [o] <artd> <-sam> DET M S @>N
cálculo	 [cálculo] N M S @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
índices	 [índice] N M P @P<
de	 [de] PRP @PIV>
que	 [que] KS @SUB @#FS-<ACC
trata	 [tratar] V PR 3S IND VFIN @FMV
este	 [este] <dem> DET M S @>N
artigo	 [artigo] N M S @<ACC
$,
os	 [o] <artd> DET M P @>N
preços	 [preço] N M P @SUBJ>
em	 [em] PRP @N<
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
deverão	 [dever] <fmc> V FUT 3P IND VFIN @FAUX
ser	 [ser] V INF @IAUX @#ICL-AUX<
convertidos	 [converter] V PCP M P @IMV @#ICL-AUX<
em	 [em] PRP @<PIV
URV	 [uRV] <prop> N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
dia	 [dia] N M S @P<
de	 [de] PRP @N<
sua	 [seu] <poss 3S> DET F S @>N
coleta	 [coleta] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
4º.	 [4º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Caso	 [caso] KS @SUB @#FS-ADVL>
o	 [o] <artd> DET M S @>N
índice	 [índice] N M S @SUBJ>
de	 [de] PRP @N<
preços	 [preço] N M P @P<
constante	 [constante] ADJ M S @N<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
contrato	 [contrato] N M S @P<
não	 [não] ADV @ADVL>
esteja	 [estar] V PR 3S SUBJ VFIN @FMV
disponível	 [disponível] <n> ADJ M S @<SC
em	 [em] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
caput ALT xxx	 [caput] N M S @P<
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$,
será	 [ser] <fmc> V FUT 3S IND VFIN @FAUX
utilizado	 [utilizar] V PCP M S @IMV @#ICL-AUX<
$,
para	 [para] PRP @<ADVL
os	 [o] <artd> DET M P @>N
fins	 [fim] N M P @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
disposto	 [dispor] <n> V PCP M S @IMV @#ICL-P<
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
art.	 [art.] N M S @P<
38	 [38] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
lei	 [lei] N F S @P<
nº	 [nº] N M S @<PRED
$.	 [$.] PU <<<
8.880	 [8.880] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL>
27	 [27] <card> NUM M/F P @P<
de	 [de] PRP @N<
maio	 [maio] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
e	 [e] <co-advl> KC @CO
em	 [em] <sam-> PRP @ADVL>
esta	 [este] <dem> <-sam> DET F S @>N
medida	 [medida] N F S @P<
provisória	 [provisório] ADJ F S @N<
$,
índice	 [índice] N M S @NPHR
equivalente	 [equivalente] ADJ M S @N<
substituto	 [substituto] N M S @N<
$,
em	 [em] <sam-> PRP @ADVL>
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
regulamentação	 [regulamentação] N F S @P<
a	 [a] PRP @ADVL>
ser	 [ser] V INF @IAUX @#ICL-P<
baixada	 [baixar] V PCP F S @IMV @#ICL-AUX<
por	 [por] <sam-> PRP @<PASS
o	 [o] <artd> <-sam> DET M S @>N
Poder=Executivo	 [Poder=Executivo] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
5º.	 [5º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
É	 [ser] <fmc> V PR 3S IND VFIN @FMV
nula	 [nulo] <n> ADJ F S @<SC
de	 [de] PRP @N<
pleno	 [pleno] ADJ M S @>N
direito	 [direito] N M S @P<
e	 [e] <co-vfin> <co-fmc> KC @CO
não	 [não] ADV @ADVL>
surtirá	 [surtir] <fmc> V FUT 3S IND VFIN @FMV
nenhum	 [nenhum] <quant> DET M S @>N
efeito	 [efeito] N M S @<ACC
a	 [o] <artd> DET F S @>N
aplicação	 [aplicação] N F S @PRED>
de	 [de] PRP @N<
índice	 [índice] N M S @P<
$,
para	 [para] PRP @<ADVL
fins	 [fim] N M P @P<
de	 [de] PRP @N<
correção	 [correção] N F S @P<
monetária	 [monetário] ADJ F S @N<
$,
calculado	 [calcular] V PCP M S @N<PRED
de	 [de] PRP @<ADVL
forma	 [forma] N F S @P<
diferente	 [diferente] ADJ F S @N<
de	 [de] <sam-> PRP @A<
a	 [o] <artd> <-sam> DET F S @>N
estabelecida	 [estabelecer] <n> V PCP F S @IMV @#ICL-P<
em	 [em] <sam-> PRP @<ADVL
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
25º	 [25º] <NUM-ord> ADJ M S @PRED>
$	 [$] PU
As	 [o] <artd> DET F P @>N
dotações	 [dotação] N F P @SUBJ>
constantes	 [constante] ADJ F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
proposta	 [proposta] N F S @P<
de	 [de] PRP @N<
Orçamento=Geral=da=União	 [Orçamento=Geral=da=União] PROP M S @P<
enviada	 [enviar] V PCP F S @IMV @#ICL-N<
a	 [a] <sam-> PRP @<ADVL
o	 [o] <-sam> <artd> DET M S @>N
Congresso=Nacional	 [Congresso=Nacional] PROP M S @P<
$,
com	 [com] PRP @N<PRED
as	 [o] <artd> DET F P @>N
modificações	 [modificação] N F P @P<
propostas	 [propor] V PCP F P @N<PRED
nos=termos=de	 [nos=termos=de] <sam-> PRP @N<
o	 [o] <-sam> <artd> DET M S @>N
art.	 [art.] N M S @P<
166	 [166] <card> NUM M/F P @N<
$,
parágrafo	 [parágrafo] N M S @N<PRED
5º	 [5º] <NUM-ord> ADJ M S @N<
$,
de	 [de] <sam-> PRP @N<PRED
a	 [o] <artd> <-sam> DET F S @>N
Constituição=Federal	 [Constituição=Federal] PROP F S @P<
$,
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
corrigidas	 [corrigir] V PCP F P @IMV @#ICL-AUX<
para	 [para] PRP @<ADVL
preços	 [preço] N M P @P<
médios	 [médio] ADJ M P @N<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
mediante	 [mediante] PRP @<ADVL
a	 [o] <artd> DET F S @>N
aplicação	 [aplicação] N F S @P<
$,
sobre	 [sobre] PRP @<ADVL
os	 [o] <artd> DET M P @>N
valores	 [valor] N M P @P<
expressos	 [esprimir] V PCP M P @N<
a	 [a] PRP @N<
preços	 [preço] N M P @P<
de	 [de] PRP @N<
abril	 [abril] N M S @P<
de	 [de] PRP @N<
1993	 [1993] <card> NUM M/F P @P<
$,
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
multiplicador	 [multiplicador] N M S @P<
de	 [de] PRP @N<
66,8402	 [66,8402] <card> NUM M/F P @P<
$,
sendo	 [ser] V GER @IAUX @#ICL-<ADVL
então	 [então] <kc> ADV @ADVL>
convertidos	 [converter] V PCP M P @IMV @#ICL-AUX<
em	 [em] PRP @<PIV
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
em	 [em] PRP @<ADVL
reais	 [real] N M P @P<
por	 [por] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
paridade	 [paridade] N F S @P<
fixada	 [fixar] V PCP F S @N<
para	 [para] PRP @N<
aquela	 [aquele] <dem> DET F S @>N
data	 [data] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @PRED>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
também	 [também] ADV @ADVL>
convertidos	 [converter] V PCP M P @IMV @#ICL-AUX<
em	 [em] PRP @<PIV
real	 [real] N M S @P<
em	 [em] PRP @<ADVL
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
por	 [por] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
paridade	 [paridade] N F S @P<
fixada	 [fixar] V PCP F S @IMV @#ICL-N< 
para	 [para] PRP @N<
aquela	 [aquele] <dem> DET F S @>N
data	 [data] N F S @P<
$,
todos=os	 [todo=o] <quant> DET M P @>N
valores	 [valor] N M P @APP
expressos	 [esprimir] V PCP M P @IMV @#ICL-N<
em	 [em] PRP @<ADVL
cruzeiros	 [cruzeiro] N M P @P<
reais	 [real] ADJ M P @N<
em	 [em] PRP @N<
30	 [30] <card> NUM M/F P @P<
de	 [de] PRP @N<
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
constantes	 [constante] N F P @N<PRED
de	 [de] PRP @N<
balanços	 [balanço] N M P @P<
e	 [e] <co-pred> KC @CO
de	 [de] PRP @<PRED
todos=os	 [todo=o] <quant> DET M P @>N
atos	 [ato] N M P @P<
e	 [e] <co-prparg> KC @CO
fatos	 [fato] N M P @P<
relacionados	 [relacionado] ADJ M P @N<
com	 [com] PRP @A<
a	 [o] <artd> DET F S @>N
gestão	 [gestão] N F S @P<
orçamentária	 [orçamentário] ADJ F S @N<
$,
financeira	 [financeiro] ADJ F S @N<PRED
$,
patrimonial	 [patrimonial] ADJ M/F S @N<PRED
e	 [e] <co-pred> KC @CO
contábil	 [contábil] ADJ M/F S @N<PRED
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
2º.	 [2º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
No=caso=de	 [no=caso=de] <sam-> PRP @ADVL>
o	 [o] <-sam> <artd> DET M S @>N
parágrafo	 [parágrafo] N M S @P<
anterior	 [anterior] ADJ M S @N<
$,
se	 [se] KS @SUB @#FS-ADVL>
resultarem	 [resultar] V FUT 3P SUBJ VFIN @FMV
valores	 [valor] N M P @<SUBJ
inferiores	 [inferior] <SUP> <KOMP> ADJ M P @N<
a	 [a] PRP @A<
R$	 [r$] <prop> N M S @P<
0,01	 [0,01] <card> NUM M/F P @N<
$(	 [$(] PU
um	 [um] <card> NUM M S @>N
centavo	 [centavo] N M S @N<PRED
de	 [de] PRP @N<
real	 [real] N M S @P<
$)	 [$)] PU
$,
os	 [o] <artd> DET M P @>N
mesmos	 [mesmo] <diff> <KOMP> DET M P @SUBJ>
serão	 [ser] <fmc> V FUT 3P IND VFIN @FAUX
representados	 [representar] V PCP M P @IMV @#ICL-AUX<
por	 [por] PRP @<PASS
este	 [este] <dem> DET M S @>N
valor	 [valor] N M S @P<
$(	 [$(] PU
R$	 [r$] N M S @N<PRED
0,01	 [0,01] <card> NUM M/F P @N<
$)	 [$)] PU
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
26º.	 [26º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Como	 [como] <rel> ADV @PRD @#AS-SC>
forma	 [forma] N F S @SUBJ>
de	 [de] PRP @N<
garantir	 [garantir] V INF 3S @IMV @#ICL-P<
o	 [o] <artd> DET M S @>N
equilíbrio	 [equilíbrio] N M S @<ACC
econômico-financeiro	 [econômico-financeiro] ADJ M S @N<
em	 [em] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
conversão	 [conversão] N F S @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
contratos	 [contrato] N M P @P<
relativos	 [relativo] ADJ M P @N<
a	 [a] <sam-> PRP @A<
a	 [o] <-sam> <artd> DET F S @>N
atividade	 [atividade] N F S @P<
agrícola	 [agrícola] ADJ F S @N<
$,
ficam	 [ficar] <fmc> V PR 3P IND VFIN @FMV
asseguradas	 [assegurar] V PCP F P @IMV @#ICL-<SC 
as	 [o] <artd> DET F P @>N
condições	 [condição] N F P @<SUBJ
de	 [de] PRP @N<
equivalência	 [equivalência] N F S @P<
constantes	 [constante] ADJ F P @N<
em	 [em] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
contratos	 [contrato] N M P @P<
de	 [de] PRP @N<
financiamento	 [financiamento] N M S @P<
de	 [de] PRP @N<
custeio	 [custeio] N M S @P<
e	 [e] <co-postnom> KC @CO
de	 [de] PRP @N<
comercialização	 [comercialização] N F S @P<
para	 [para] PRP @N<
produtos	 [produto] N M P @P<
contemplados	 [contemplar] V PCP M P @IMV @#ICL-N<
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
safra	 [safra] N F S @P<
1993/94	 [1993/94] <card> NUM M/F P @<SUBJ
e	 [e] KC @CO
em	 [em] <sam-> PRP @<ADVL @A<
a	 [o] <artd> <-sam> DET F S @>N
safra	 [safra] N F S @P<
1994	 [1994] <card> NUM M/F P @<SUBJ
com	 [com] PRP @<ADVL
preços	 [preço] <*1> N M P @P<
mínimos	 [pequeno] <SUP> ADJ M P @N<
de	 [de] PRP @N<
garantia	 [garantia] <*2> N F S @P<
dentro=de	 [dentro=de] <sam-> PRP @N< @<ADVL
a	 [o] <-sam> <artd> DET F S @>N
Política=de=Garantia=de=Preços=Mínimos	 [Política=de=Garantia=de=Preços=Mínimos] PROP F S @P<
$	 [$] PU
PGPM	 [PGPM] PROP M/F S @<SUBJ
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Capítulo=IV	 [Capítulo=IV] PROP M S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
Da=Correção=Monetária	 [Da=Correção=Monetária] PROP F S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
27º.	 [27º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
A	 [o] <artd> DET F S @>N
correção	 [correção] N F S @SUBJ>
$,
em=virtude=de	 [em=virtude=de] PRP @ADVL>
disposição	 [disposição] N F S @P<
legal	 [legal] ADJ F S @N<
ou	 [ou] <co-prparg> KC @CO
estipulação	 [estipulação] N F S @P< @<PRED
de	 [de] PRP @N<
negócio	 [negócio] N M S @P<
jurídico	 [jurídico] ADJ M S @N<
$,
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
expressão	 [expressão] N F S @P<
monetária	 [monetário] ADJ F S @N<
de	 [de] PRP @N<
obrigação	 [obrigação] N F S @P<
pecuniária	 [pecuniário] ADJ F S @N<
contraída	 [contrair] V PCP F S @N<
a=partir=de	 [a=partir=de] PRP @N<
1º	 [1º] <n> <NUM-ord> ADJ M S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
inclusive	 [inclusive] ADV @ADVL>
$,
somente	 [somente] ADV @ADVL>
poderá	 [poder] <fmc> V FUT 3S IND VFIN @FAUX
dar-	 [dar] <hyfen> V INF @IMV @#ICL-AUX<
se	 [se] <refl> PERS F 3S ACC @<ACC
por	 [por] <sam-> PRP @<OC
a	 [o] <artd> <-sam> DET F S @>N
variação	 [variação] N F S @P<
acumulada	 [acumular] V PCP F S @N<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
IPC-r	 [IPC-r] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O	 [o] <artd> DET M S @>N
disposto	 [dispor] <n> V PCP M S @ACC>
em	 [em] <sam-> PRP @<ADVL
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
não	 [não] ADV @ADVL>
se	 [se] <refl> PERS M/F 3S ACC @ACC>-PASS
aplica	 [aplicar] <fmc> V PR 3S IND VFIN @FMV
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
a	 [a] PRP @ADVL
$)	 [$)] PU
a	 [a] <sam-> PRP @ADVL
as	 [o] <-sam> <artd> DET F P @>N
operações	 [operação] N F P @P<
e	 [e] <co-prparg> KC @CO
contratos	 [contrato] N M P @P<
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
tratam	 [tratar] V PR 3P IND VFIN @FMV
o	 [o] <artd> DET M S @>N
decreto-lei	 [decreto-lei] N M S @<ACC
nº	 [nº] N M S @<ACC
$.	 [$.] PU <<<
857	 [857] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
11	 [11] <card> NUM M P @>N
setembro	 [setembro] N M S @P<
de	 [de] PRP @N<
1969	 [1969] <card> NUM M/F P @P<
$,
e	 [e] KC @CO
o	 [o] <artd> DET M S @>N
art.	 [art.] N M S @PRED>
6º	 [6º] <card> NUM M/F P @N<
$.	 [$.] PU <<<
de	 [de] <sam-> PRP @ADVL
a	 [o] <artd> <-sam> DET F S @>N
lei	 [lei] N F S @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.880	 [8.880] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
27	 [27] <card> NUM M/F P @P<
de	 [de] PRP @N<
maio	 [maio] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
b	 [b] N M S @NPHR
$)	 [$)] PU
a	 [a] <sam-> PRP @ADVL>
os	 [o] <-sam> <artd> DET M P @>N
contratos	 [contrato] N M P @P<
por	 [por] <sam-> PRP @ADVL>
os=quais	 [o=qual] <rel> <-sam> SPEC M P @P< @#FS-N<
a	 [o] <artd> DET F S @>N
empresa	 [empresa] N F S @SUBJ>
se	 [se] <refl> PERS M/F 3S ACC @ACC>
obrigue	 [obrigar] V PR 3S SUBJ VFIN @FMV
a	 [a] PRP @<PIV
vender	 [vender] V INF @IMV @#ICL-P<
bens	 [bem] N M P @<ACC
para	 [para] PRP @<ADVL
entrega	 [entrega] N F S @P<
futura	 [futuro] ADJ F S @N<
$,
prestar	 [prestar] V INF @IMV @#ICL-P<
ou	 [ou] <co-inf> KC @CO
fornecer	 [fornecer] V INF @IMV @#ICL-P<
serviços	 [serviço] N M P @<ACC
a	 [a] PRP @<ADVL
serem	 [ser] V INF 3P @IAUX @#ICL-P<
produzidos	 [produzir] V PCP M P @IMV @#ICL-AUX<
$,
cujo	 [cujo] <rel> DET M S @>N @#FS-N<
preço	 [preço] N M S @SUBJ>
poderá	 [poder] V FUT 3S IND VFIN @FAUX
ser	 [ser] V INF @IAUX @#ICL-AUX<
reajustado	 [reajustar] V PCP M S @IMV @#ICL-AUX<
em=função=de	 [em=função=de] <sam-> PRP @<ADVL
o	 [o] <-sam> <artd> DET M S @>N
custo	 [custo] N M S @P<
de	 [de] PRP @N<
produção	 [produção] N F S @P<
ou	 [ou] <co-postnom> KC @CO
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
variação	 [variação] N F S @P<
em	 [em] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
preço	 [preço] N M S @P<
de	 [de] PRP @N<
insumos	 [insumo] N M P @P<
utilizados	 [utilizar] V PCP M P @N<
$;	 [$;] PU <<<
e	 [e] KC @CO
$¶	 [$¶] PU <<<
</s>
<s>
c	 [c] N M S @NPHR
$)	 [$)] PU
a	 [a] <sam-> PRP @ADVL
as	 [o] <-sam> <artd> DET F P @>N
hipóteses	 [hipótese] N F P @P<
tratadas	 [tratar] V PCP F P @IMV @#ICL-N<
em	 [em] PRP @<ADVL
lei	 [lei] N F S @P<
especial	 [especial] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @PRED>
2º.	 [2º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Considerará-	 [considerar] <hyfen> <fmc> V FUT 3S IND VFIN @FMV
se-	 [se] <hyfen> PERS M/F 3S/P ACC @<SUBJ
de	 [de] PRP @<ADVL
nenhum	 [nenhum] <quant> DET M S @>N
efeito	 [efeito] N M S @P<
a	 [o] <artd> DET F S @>N
estipulação	 [estipulação] N F S @<ACC
$,
a=partir=de	 [a=partir=de] PRP @<ADVL
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
de	 [de] PRP @N<
correção	 [correção] N F S @P<
monetária	 [monetário] ADJ F S @N<
em	 [em] PRP @N<
desacordo	 [desacordo] N M S @P<
com	 [com] PRP @N<
o	 [o] <artd> DET M S @>N
estabelecido	 [estabelecer] <n> V PCP M S @P<
em	 [em] <sam-> PRP @<ADVL
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
3º.	 [3º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Em	 [em] <sam-> PRP @ADVL>
os	 [o] <artd> <-sam> DET M P @>N
contratos	 [contrato] N M P @P<
celebrados	 [celebrar] V PCP M P @IMV @#ICL-N< 
ou	 [ou] <co-postnom> KC @CO
convertidos	 [converter] V PCP M P @IMV @#ICL-N<
em	 [em] PRP @<PIV
URV	 [uRV] <prop> N F S @P<
$,
em	 [em] PRP @ADVL>
que	 [que] KS @SUB @#FS-<ACC
haja	 [haver] V PR 3S SUBJ VFIN @FMV
cláusula	 [cláusula] N F S @<ACC
de	 [de] PRP @N<
reajuste	 [reajuste] N M S @P<
de	 [de] PRP @N<
valor	 [valor] N M S @P<
por	 [por] PRP @<ADVL
índice	 [índice] N M S @P<
de	 [de] PRP @N<
preços	 [preço] N M P @P<
ou	 [ou] <co-advl> KC @CO
por	 [por] PRP @<ADVL
índice	 [índice] N M S @P<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
reflita	 [refletir] V PR 3S SUBJ VFIN @FMV
a	 [o] <artd> DET F S @>N
variação	 [variação] N F S @<ACC
ponderada	 [ponderar] V PCP F S @N<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
custos	 [custo] N M P @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
insumos	 [insumo] N M P @P<
utilizados	 [utilizar] V PCP M P @N<
$,
o	 [o] <artd> DET M S @>N
cálculo	 [cálculo] N M S @APP
de	 [de] <sam-> PRP @N<
esses	 [esse] <dem> <-sam> DET M P @>N
índices	 [índice] N M P @P<
$,
para	 [para] PRP @<ADVL
efeitos	 [efeito] N M P @P<
de	 [de] PRP @N<
reajuste	 [reajuste] N M S @P<
$,
deverá	 [dever] <fmc> V FUT 3S IND VFIN @FAUX
ser	 [ser] V INF @IMV @#ICL-AUX<
em	 [em] <sam-> PRP @<SC
esta	 [este] <dem> <-sam> DET F S @>N
moeda	 [moeda] N F S @P<
até	 [até] ADV @>N
a	 [o] <artd> DET F S @>N
emissão	 [emissão] N F S @<SUBJ
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
real	 [real] N M S @P<
e	 [e] KC @CO
$,
daí=em=diante	 [daí=em=diante] ADV @<ADVL
$,
em	 [em] PRP @<ADVL
real	 [real] N M S @P<
$,
observado	 [observar] V PCP M S @IMV @#ICL-<ADVL
o	 [o] <artd> DET M S @>N
art.	 [art.] N M S @<SUBJ
38	 [38] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
lei	 [lei] N F S @P<
nº	 [nº] N M S @<ACC
$.	 [$.] PU <<<
8.880	 [8.880] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
27.05.94	 [27.05.94] <card> NUM M/F P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
4º.	 [4º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
A=Taxa=Referencial	 [A=Taxa=Referencial] PROP F S @SUBJ>
$	 [$] PU
TR	 [TR] PROP M/F S @SUBJ>
$	 [$] PU
somente	 [somente] ADV @ADVL>
poderá	 [poder] <fmc> V FUT 3S IND VFIN @FAUX
ser	 [ser] V INF @IAUX @#ICL-AUX<
utilizada	 [utilizar] V PCP F S @IMV @#ICL-AUX<
em	 [em] <sam-> PRP @<ADVL
as	 [o] <artd> <-sam> DET F P @>N
operações	 [operação] N F P @P<
realizadas	 [realizar] V PCP F P @IMV @#ICL-N<
em	 [em] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
mercados	 [mercado] N M P @P<
financeiro	 [financeiro] ADJ M S @<PRED
$,
de	 [de] PRP @<PRED
valores	 [valor] N M P @P<
mobiliários	 [mobiliário] ADJ M P @N<
$,
de	 [de] PRP @<ADVL
seguros	 [seguro] ADJ M P @P<
$,
de	 [de] PRP @N<PRED
previdência	 [previdência] N F S @P<
privada	 [privado] ADJ F S @N<
e	 [e] <co-advl> KC @CO
de	 [de] PRP @<ADVL
futuros	 [futuro] ADJ M P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
5º.	 [5º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Continua	 [continuar] <fmc> V PR 3S IND VFIN @FMV
aplicável	 [aplicável] ADJ M S @<SC
$,
a	 [a] <sam-> PRP @<ADVL
os	 [o] <-sam> <artd> DET M P @>N
débitos	 [débito] N M P @P<
trabalhistas	 [trabalhista] ADJ M/F P @<PRED
o	 [o] <artd> DET M S @>N
disposto	 [dispor] <n> V PCP M S @IMV @#ICL-<SC
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
art.	 [art.] N M S @P<
39	 [39] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
lei	 [lei] N F S @P<
nº	 [nº] N M S @<SC
$.	 [$.] PU <<<
8.177	 [8.177] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N< @ADVL
março	 [março] N M S @P<
de	 [de] PRP @N<
1991	 [1991] <card> NUM M/F P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
28º.	 [28º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Em	 [em] <sam-> PRP @ADVL>
os	 [o] <artd> <-sam> DET M P @>N
contratos	 [contrato] N M P @P<
celebrados	 [celebrar] V PCP M P @IMV @#ICL-N< 
ou	 [ou] <co-postnom> KC @CO
convertidos	 [converter] V PCP M P @IMV @#ICL-N<
em	 [em] PRP @<PIV
real	 [real] N M S @P<
com	 [com] PRP @N<
cláusula	 [cláusula] N F S @P<
de	 [de] PRP @N<
reajuste	 [reajuste] N M S @P<
de	 [de] PRP @N<
valores	 [valor] N M P @P<
por	 [por] PRP @ADVL>
índices	 [índice] N M P @P<
de	 [de] PRP @N<
preço	 [preço] N M S @P<
ou	 [ou] <co-advl> KC @CO
por	 [por] PRP @ADVL>
índice	 [índice] N M S @P<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
reflita	 [refletir] V PR 3S SUBJ VFIN @FMV
a	 [o] <artd> DET F S @>N
variação	 [variação] N F S @<ACC
ponderada	 [ponderar] V PCP F S @N<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
custos	 [custo] N M P @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
insumos	 [insumo] N M P @P<
utilizados	 [utilizar] V PCP M P @N<
$,
a	 [o] <artd> DET F S @>N
periodicidade	 [periodicidade] N F S @SUBJ>
de	 [de] PRP @N<
aplicação	 [aplicação] N F S @P<
de	 [de] <sam-> PRP @N<
essas	 [esse] <dem> <-sam> DET F P @>N
cláusulas	 [cláusula] N F P @P<
será	 [ser] <fmc> V FUT 3S IND VFIN @FMV
anual	 [anual] ADJ F S @<SC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
É	 [ser] <fmc> V PR 3S IND VFIN @FMV
nula	 [nulo] <n> ADJ F S @<SC
de	 [de] PRP @N<
pleno	 [pleno] ADJ M S @>N
direito	 [direito] N M S @P<
e	 [e] <co-vfin> <co-fmc> KC @CO
não	 [não] ADV @ADVL>
surtirá	 [surtir] <fmc> V FUT 3S IND VFIN @FMV
nenhum	 [nenhum] <quant> DET M S @>N
efeito	 [efeito] N M S @<ACC
cláusula	 [cláusula] N F S @PRED>
de	 [de] PRP @N<
reajuste	 [reajuste] N M S @P<
de	 [de] PRP @N<
valores	 [valor] N M P @P<
cuja	 [cujo] <rel> DET F S @>N @#FS-N<
periodicidade	 [periodicidade] N F S @SUBJ>
seja	 [ser] V PR 3S SUBJ VFIN @FMV
inferior	 [inferior] <SUP> <KOMP> ADJ F S @<SC
a	 [a] PRP @A<
um	 [um] <card> NUM M S @>N
ano	 [ano] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @PRED>
único	 [único] ADJ M S @N<
$--	 [$--] PU
Os	 [o] <artd> DET M P @>N
custos	 [custo] N M P @SUBJ>
financeiros	 [financeiro] ADJ M P @N<
corresponderão	 [corresponder] <fmc> V FUT 3P IND VFIN @FMV
$,
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
mínimo	 [pequeno] <n> <SUP> ADJ M S @P<
$,
a	 [a] <sam-> PRP @<PIV
os	 [o] <dem> <-sam> DET M P @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
linha	 [linha] N F S @P<
de	 [de] PRP @N<
empréstimo	 [empréstimo] N M S @P<
de	 [de] PRP @N<
liquidez	 [liquidez] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
$(	 [$(] PU
continua	 [continuar] <fmc> V PR 3S IND VFIN @FMV
$)	 [$)] PU
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
44	 [44] <card> NUM M/F P @ACC>
$	 [$] PU
As	 [o] <artd> DET F P @>N
multas	 [multa] N F P @SUBJ>
aplicadas	 [aplicar] V PCP F P @IMV @#ICL-N<
por	 [por] <sam-> PRP @<PASS
o	 [o] <artd> <-sam> DET M S @>N
Banco=Central=do=Brasil	 [Banco=Central=do=Brasil] PROP M S @P<
$,
em	 [em] <sam-> PRP @A<
o	 [o] <artd> <-sam> DET M S @>N
exercício	 [exercício] N M S @P<
de	 [de] PRP @N<
sua	 [seu] <poss 3S> DET F S @>N
competência	 [competência] N F S @P<
legal	 [legal] ADJ F S @N<
$,
a	 [a] <sam-> PRP @A<
as	 [o] <-sam> <artd> DET F P @>N
instituições	 [instituição] N F P @P<
ficanceiras	 [ficanceiras] <DERS> <DERS> ADJ F P @N<
e	 [e] KC @CO
a	 [a] <sam-> PRP @A<
as	 [o] <dem> <-sam> DET F P @P<
por	 [por] PRP @N<
ele	 [ele] PERS M 3S NOM/PIV @P<
autorizadas	 [autorizar] V PCP F P @IMV @#ICL-<PRED
a	 [a] PRP @<PIV
funcionar	 [funcionar] V INF @IMV @#ICL-P<
$,
terão	 [ter] <fmc> V FUT 3P IND VFIN @FMV
o	 [o] <artd> DET M S @>N
valor	 [valor] N M S @<ACC
máximo	 [grande] <SUP> ADJ M S @N<
de	 [de] PRP @N<
R$	 [r$] <prop> N M S @P<
100.000,00	 [100.000,00] <card> NUM M/F P @N<
$(	 [$(] PU
cem	 [cem] <card> NUM M P @>N
mil	 [mil] <card> NUM M P @>N
reais	 [real] N M P @N<PRED
$)	 [$)] PU
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O	 [o] <artd> DET M S @>N
disposto	 [dispor] <n> V PCP M S @ACC>
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
caput ALT xxx	 [caput] N M S @P<
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
não	 [não] ADV @ADVL>
se	 [se] <refl> PERS M/F 3S ACC @ACC>-PASS
aplica	 [aplicar] <fmc> V PR 3S IND VFIN @FMV
a	 [a] <sam-> PRP @<PIV
as	 [o] <-sam> <artd> DET F P @>N
infrações	 [infração] N F P @P<
de	 [de] PRP @N<
natureza	 [natureza] N F S @P<
cambial	 [cambial] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
2.º	 [2.º] <NUM-ord> ADJ M S @N<
$	 [$] PU
O=Conselho=Monetário=Nacional	 [O=Conselho=Monetário=Nacional] PROP M S @N<
$,
regulamentará	 [regulamentar] <fmc> V FUT 3S IND VFIN @FMV
a	 [o] <artd> DET F S @>N
gradação	 [gradação] N F S @<ACC
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
multas	 [multa] N F P @P<
a	 [a] PRP @ADVL>
que	 [que] KS @SUB @#FS-<ACC
se	 [se] PERS M/F 3S/P ACC @SUBJ>
refere	 [referir] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
caput ALT xxx	 [caput] N M S @<ACC
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
45	 [45] <card> NUM M/F P @SUBJ>
$	 [$] PU
Os	 [o] <artd> DET M P @>N
depósitos	 [depósito] N M P @SUBJ>
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
instituições	 [instituição] N F P @P<
financeiras	 [financeiro] ADJ F P @N<
bancárias	 [bancário] ADJ F P @N<
mantidos	 [manter] V PCP M P @IMV @#ICL-N< 
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
Banco=Central=do=Brasil	 [Banco=Central=do=Brasil] PROP M S @P<
e	 [e] KC @CO
contabilizados	 [contabilizar] V PCP M P @SC>
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
conta	 [conta] N F S @P<
Reservas=Bancárias	 [Reservas=Bancárias] <*1> <*2> PROP F S @N<
são	 [ser] <fmc> V PR 3P IND VFIN @FMV
impenhoráveis	 [impenhorar] <DERP> <fmc> V IMPF 2P IND VFIN @FMV
e	 [e] <co-vfin> <co-fmc> KC @CO
não	 [não] ADV @ADVL>
responderão	 [responder] <fmc> V FUT 3P IND VFIN @FMV
por	 [por] PRP @<PIV
qualquer	 [qualquer] <quant> DET M S @>N
tipo	 [tipo] N M S @P<
de	 [de] PRP @N<
dívida	 [dívida] N F S @P<
civil	 [civil] ADJ F S @N<
$,
comercial	 [comercial] ADJ M/F S @N<PRED
$,
fiscal	 [fiscal] ADJ M/F S @N<PRED
$,
previdenciária	 [previdenciário] <DERS> ADJ F S @N<PRED
$,
trabalhista	 [trabalhista] ADJ M/F S @N<PRED
ou	 [ou] <co-pred> KC @CO
de	 [de] PRP @N<PRED
outra	 [outro] <KOMP> <diff> DET F S @>N
natureza	 [natureza] N F S @P<
$,
contraída	 [contrair] V PCP F S @IMV @#ICL-N<PRED @#ICL-P<
por	 [por] PRP @<PASS
essas	 [esse] <dem> DET F P @>N
instituições	 [instituição] N F P @P<
ou	 [ou] <co-prparg> KC @CO
quaisquer	 [qualquer] <quant> DET M/F P @>N
outras	 [outro] <KOMP> <diff> DET F P @P< @<ACC
a	 [a] PRP @<ADVL
elas	 [elas] PERS F 3P NOM/PIV @P<
ligadas	 [ligar] V PCP F P @<PRED
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
46	 [46] <card> NUM M/F P @P<
$	 [$] PU
A=partir=de	 [a=partir=de] PRP @ADVL>
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
fica	 [ficar] <fmc> V PR 3S IND VFIN @FMV
vedada	 [vedar] V PCP F S @<SC
a	 [o] <artd> DET F S @>N
emissão	 [emissão] N F S @<SUBJ
$,
pagamento	 [pagamento] N M S @<SC
e	 [e] <co-sc> KC @CO
compensação	 [compensação] N F S @<SC
de	 [de] PRP @N<
cheque	 [cheque] N M S @P<
de	 [de] PRP @N<
valor	 [valor] N M S @P<
superior	 [alto] <SUP> <KOMP> ADJ M S @N<
a	 [a] PRP @A<
R$	 [r$] <prop> N M S @P<
100,00	 [100,00] <card> NUM M/F P @N<
$(	 [$(] PU
cem	 [cem] <card> NUM M P @>N
reais	 [real] N M P @N<PRED
$)	 [$)] PU
$,
sem	 [sem] PRP @<ADVL @N<PRED
identificação	 [identificação] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
beneficiário	 [beneficiário] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo=Único	 [Parágrafo=Único] PROP M S @ACC>
$	 [$] PU
O=Conselho=Monetário=Nacional	 [O=Conselho=Monetário=Nacional] PROP M S @SUBJ>
regulamentará	 [regulamentar] <fmc> V FUT 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
diposto	 [diposto] <DERP> N M S @<ACC
em	 [em] <sam-> PRP @<ADVL
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
47	 [47] <card> NUM M/F P @SUBJ>
$	 [$] PU
A=partir=de	 [a=partir=de] PRP @ADVL>
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
o	 [o] <artd> DET M S @>N
reajuste	 [reajuste] N M S @SUBJ>
e	 [e] <co-subj> KC @CO
a	 [o] <artd> DET F S @>N
revisão	 [revisão] N F S @SUBJ>
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
preços	 [preço] N M P @P<
públicos	 [público] ADJ M P @N<
e	 [e] <co-postnom> KC @CO
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
tarifas	 [tarifa] N F P @P<
de	 [de] PRP @N<
serviços	 [serviço] N M P @P<
públicos	 [público] ADJ M P @N<
farão-	 [fazer] <hyfen> <fmc> V FUT 3P IND VFIN @FMV
se-	 [se] <hyfen> PERS M/F 3P ACC @<ACC-PASS
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
a	 [o] <artd> DET F S @>N
$)	 [$)] PU
conforme	 [conforme] <prp> <rel> ADV @COM @#AS-ADVL>
atos	 [ato] N M P @AS<
$,
normas	 [norma] N F P @AS<
e	 [e] KC @CO
critérios	 [critério] N M P @AS<
a	 [a] PRP @ADVL>
serem	 [ser] V INF 3P @IAUX @#ICL-P<
fixados	 [fixar] V PCP M P @IMV @#ICL-AUX<
por	 [por] <sam-> PRP @<PASS
o	 [o] <artd> <-sam> DET M S @>N
ministro=da=Fazenda	 [ministro=da=Fazenda] N M S @P<
$;	 [$;] PU <<<
e	 [e] KC @CO
$¶	 [$¶] PU <<<
</s>
<s>
b	 [b] N M S @SUBJ>
$)	 [$)] PU
os	 [o] <artd> DET M P @>N
reajustes	 [reajuste] N M P @SUBJ>
serão	 [ser] <fmc> V FUT 3P IND VFIN @FMV
anuais	 [anual] ADJ M P @<SC
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O=Poder=Executivo	 [O=Poder=Executivo] PROP M S @SUBJ>
poderá	 [poder] <fmc> V FUT 3S IND VFIN @FAUX
reduzir	 [reduzir] V INF @IMV @#ICL-AUX<
o	 [o] <artd> DET M S @>N
prazo	 [prazo] N M S @<ACC
previsto	 [prever] V PCP M S @IMV @#ICL-N<
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
alínea	 [alínea] N F S @P<
b	 [b] <*2> <*1> N M S @<ACC
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
caput ALT xxx	 [caput] N M S @P<
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
2º.	 [2º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O	 [o] <artd> DET M S @>N
disposto	 [dispor] <n> V PCP M S @ACC>
em	 [em] <sam-> PRP @<ADVL
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
aplica-	 [aplicar] <hyfen> <fmc> V PR 3S IND VFIN @FMV
se	 [se] <refl> PERS M 3S ACC @<ACC-PASS
$,
inclusive	 [inclusive] ADV @<ADVL
$,
a	 [a] <sam-> PRP @<PIV
a	 [o] <-sam> <artd> DET F S @>N
fixação	 [fixação] N F S @P<
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
níveis	 [nível] N M P @P<
de	 [de] <sam-> PRP @N<
as	 [o] <artd> <-sam> DET F P @>N
tarifas	 [tarifa] N F P @P<
para	 [para] PRP @<ADVL
o	 [o] <artd> DET M S @>N
serviço	 [serviço] N M S @P<
público	 [público] ADJ M S @N<
de	 [de] PRP @N<
energia	 [energia] N F S @P<
elétrica	 [elétrico] ADJ F S @N<
$,
reajustes	 [reajuste] N M P @P<
e	 [e] <co-prparg> KC @CO
revisões	 [revisão] N F P @P<
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
trata	 [tratar] V PR 3S IND VFIN @FMV
a	 [o] <artd> DET F S @>N
Lei	 [lei] <prop> N F S @<ACC
nº	 [nº] N M S @<ACC
$.	 [$.] PU <<<
8.631	 [8.631] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
4	 [4] <card> NUM M/F P @P<
de	 [de] PRP @N<
março	 [março] N M S @P<
de	 [de] PRP @N<
1993	 [1993] <card> NUM M/F P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
48	 [48] <card> NUM F P @SUBJ>
$	 [$] PU
A=partir=de	 [a=partir=de] <sam-> PRP @ADVL>
a	 [o] <-sam> <artd> DET F S @>N
publicação	 [publicação] N F S @P<
de	 [de] <sam-> PRP @N<
esta	 [este] <dem> <-sam> DET F S @>N
medida	 [medida] N F S @P<
provisória	 [provisório] ADJ F S @N<
$,
ficam	 [ficar] <fmc> V PR 3P IND VFIN @FMV
suspensas	 [suspender] V PCP F P @<SC
$,
por	 [por] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
prazo	 [prazo] N M S @P<
de	 [de] PRP @N<
90	 [90] <card> NUM M/F P @>N
$(	 [$(] PU
noventa	 [noventa] <card> NUM M/F P @P<
$)	 [$)] PU
dias	 [dia] N M P @<SC @N<PRED
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
I	 [i] N M S @NPHR
$--	 [$--] PU
a	 [o] <artd> DET F S @>N
concessão	 [concessão] N F S @S<
de	 [de] PRP @N<
avais	 [aval] N M P @P<
e	 [e] KC @CO
quaisquer	 [qualquer] <quant> DET F P @>N
outras	 [outro] <KOMP> <diff> DET F P @>N
garantias	 [garantia] N F P @NPHR
$,
para	 [para] PRP @ADVL
qualquer	 [qualquer] <quant> DET M S @>N
fim	 [fim] N M S @P<
$,
por	 [por] <sam-> PRP @ADVL
o	 [o] <artd> <-sam> DET M S @>N
Tesouro=Nacional	 [Tesouro=Nacional] PROP M S @P<
ou	 [ou] KC @CO
em	 [em] PRP @ADVL
seu	 [seu] <poss 3S> DET M S @>N
nome	 [nome] N M S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
II	 [II] <NUM-ord> ADJ M/F S @PRED>
$--	 [$--] PU
a	 [o] <artd> DET F S @>N
aprovação	 [aprovação] N F S @S<
de	 [de] PRP @N<
novos	 [novo] ADJ M P @>N
projetos	 [projeto] N M P @P<
a	 [a] PRP @ADVL>
serem	 [ser] V INF 3P @IAUX @#ICL-P<
financiados	 [financiar] V PCP M P @IMV @#ICL-AUX<
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
âmbito	 [âmbito] N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Cofiex	 [Cofiex] PROP M S @P<
$,
de	 [de] PRP @ADVL>
que	 [que] KS @SUB @#FS-<ACC
trata	 [tratar] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
Decreto	 [decreto] <prop> N M S @<ACC
nº	 [nº] N M S @<ACC
$.	 [$.] PU <<<
688	 [688] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
26	 [26] <card> NUM M/F P @P<
de	 [de] PRP @N<
novembro	 [novembro] N M S @P<
de	 [de] PRP @N<
1992	 [1992] <card> NUM M/F P @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
III	 [III] <NUM-ord> ADJ M/F S @NPHR
$--	 [$--] PU
a	 [o] <artd> DET F S @>N
abertura	 [abertura] N F S @S<
de	 [de] PRP @N<
créditos	 [crédito] N M P @P<
especiais	 [especial] ADJ M P @N<
em	 [em] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Orçamento=Geral=da=União	 [Orçamento=Geral=da=União] PROP M S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
IV	 [IV] <NUM-ord> ADJ M/F S @PRED>
$--	 [$--] PU
a	 [o] <artd> DET F S @>N
colocação	 [colocação] N F S @S<
$,
por=parte=de	 [por=parte=de] <sam-> PRP @ADVL
os	 [o] <-sam> <artd> DET M P @>N
órgãos	 [órgão] N M P @P<
autônomos	 [autônomo] ADJ M P @N<
$,
autarquias	 [autarquia] N F P @P<
$,
empresas	 [empresa] N F P @P<
públicas	 [público] ADJ F P @N<
$,
sociedades	 [sociedade] N F P @P<
de	 [de] PRP @N<
economia	 [economia] N F S @P<
mista	 [misturar] V PCP F S @N<
e	 [e] <co-prparg> KC @CO
fundações	 [fundação] N F P @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
União	 [união] <prop> N F S @P<
de	 [de] PRP @N<
qualquer	 [qualquer] <quant> DET M S @>N
título	 [título] N M S @P<
ou	 [ou] <co-prparg> KC @CO
obrigação	 [obrigação] N F S @P<
em	 [em] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
exterior	 [exterior] N M S @P<
$,
exceto	 [exceto] PRP @ADVL
quando	 [quando] <rel> ADV @ADVL @#AS-ADVL
vinculado	 [vincular] V PCP M S @AS<
a	 [a] <sam-> PRP @<PIV
a	 [o] <-sam> <artd> DET F S @>N
amortização	 [amortização] N F S @P<
de	 [de] PRP @N<
principal	 [principal] N M S @P<
corrigido	 [corrigir] V PCP M S @N<
de	 [de] PRP @N<
dívida	 [dívida] N F S @P<
interna	 [interno] ADJ F S @N<
ou	 [ou] <co-postnom> KC @CO
externa	 [externo] ADJ F S @N<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
V	 [v] N M S @NPHR
$--	 [$--] PU
a	 [o] <artd> DET F S @>N
contratação	 [contratação] N F S @S<
$,
por=parte=de	 [por=parte=de] <sam-> PRP @ADVL
os	 [o] <-sam> <artd> DET M P @>N
órgãos	 [órgão] N M P @P<
e	 [e] <co-prparg> KC @CO
entidades	 [entidade] N F P @P<
mencionados	 [mencionar] V PCP M P @IMV @#ICL-N<
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
inciso	 [inciso] N M S @P<
anterior	 [anterior] ADJ M S @N<
$,
de	 [de] PRP @ADVL
novas	 [novo] ADJ F P @>N
operações	 [operação] N F P @P<
de	 [de] PRP @N<
crédito	 [crédito] N M S @P<
interno	 [interno] ADJ M S @N<
ou	 [ou] <co-postnom> KC @CO
externo	 [externo] ADJ M S @N<
$,
exceto	 [exceto] PRP @ADVL
quando	 [quando] <rel> ADV @ADVL @#AS-ADVL
vinculada	 [vincular] V PCP F S @AS<
a	 [a] <sam-> PRP @<PIV
a	 [o] <-sam> <artd> DET F S @>N
amortização	 [amortização] N F S @P<
de	 [de] PRP @N<
principal	 [principal] N M S @P<
corrigido	 [corrigir] V PCP M S @N<
de	 [de] PRP @N<
dívida	 [dívida] N F S @P<
interna	 [interno] ADJ F S @N<
ou	 [ou] <co-postnom> KC @CO
externa	 [externo] ADJ F S @N<
ou	 [ou] <co-postnom> KC @CO
referente=a	 [referente=a] PRP @ADVL @N<
operações	 [operação] N F P @P<
mercantis	 [mercantil] ADJ F P @N<
$;	 [$;] PU <<<
e	 [e] KC @CO
$¶	 [$¶] PU <<<
</s>
<s>
VI	 [VI] <NUM-ord> ADJ M/F S @PRED>
$--	 [$--] PU
a	 [o] <artd> DET F S @>N
conversão	 [conversão] N F S @S<
em	 [em] PRP @ADVL
títulos	 [título] N M P @P<
públicos	 [público] ADJ M P @N<
federais	 [federal] ADJ M P @N<
de	 [de] PRP @N<
créditos	 [crédito] N M P @P<
oriundos	 [oriundo] ADJ M P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Conta=de=Resultados	 [Conta=de=Resultados] PROP F S @P<
a	 [a] PRP @ADVL
Compensar	 [compensar] V INF @IMV @#ICL-P<
$	 [$] PU
CRC	 [CRC] PROP M/F S @<ACC
$	 [$] PU
$,
objeto	 [objeto] N M S @<ACC
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @<PRED
$.	 [$.] PU <<<
8.631	 [8.631] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
4	 [4] <card> NUM M/F P @P<
de	 [de] PRP @N<
março	 [março] N M S @P<
de	 [de] PRP @N<
1993	 [1993] <card> NUM M/F P @P<
$,
com	 [com] PRP @ADVL
as	 [o] <artd> DET F P @>N
alterações	 [alteração] N F P @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.724	 [8.724] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
28	 [28] <card> NUM M/F P @P<
de	 [de] PRP @N<
outubro	 [outubro] N M S @P<
de	 [de] PRP @N<
1993	 [1993] <card> NUM M/F P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O=Poder=Executivo	 [O=Poder=Executivo] PROP M S @SUBJ>
poderá	 [poder] <fmc> V FUT 3S IND VFIN @FAUX
prorrogar	 [prorrogar] V INF @IMV @#ICL-AUX<
por=igual	 [por=igual] ADV @<ADVL
período	 [período] N M S @<ACC
o	 [o] <artd> DET M S @>N
prazo	 [prazo] N M S @PRED>
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
trata	 [tratar] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
caput ALT xxx	 [caput] N M S @<ACC
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
2º.	 [2º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Durante	 [durante] PRP @ADVL>
o	 [o] <artd> DET M S @>N
prazo	 [prazo] N M S @P<
de	 [de] PRP @PIV>
que	 [que] KS @SUB @#FS-<ACC
trata	 [tratar] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
caput ALT xxx	 [caput] N M S @<ACC
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
$,
qualquer	 [qualquer] <quant> DET M S @>N
pedido	 [pedido] N M S @<SUBJ
de	 [de] PRP @N<
crédito	 [crédito] N M S @P<
adicional	 [adicional] ADJ M S @N<
suplementar	 [suplementar] ADJ M S @N<
a	 [a] <sam-> PRP @<ADVL
o	 [o] <-sam> <artd> DET M S @>N
Orçamento=Geral=da=União	 [Orçamento=Geral=da=União] PROP M S @P<
deverá	 [dever] <fmc> V FUT 3S IND VFIN @FAUX
ser	 [ser] V INF @IAUX @#ICL-AUX<
previamente	 [previamente] ADV @<ADVL
apreciado	 [apreciar] V PCP M S @IMV @#ICL-AUX<
por	 [por] <sam-> PRP @<PASS
a	 [o] <artd> <-sam> DET F S @>N
Junta=de=Conciliação=Orçamentária	 [Junta=de=Conciliação=Orçamentária] PROP F S @P<
e	 [e] <co-prparg> KC @CO
Financeira	 [Financeira] PROP M/F S @P<
de	 [de] PRP @ADVL>
que	 [que] KS @SUB @#FS-<ACC
trata	 [tratar] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
Decreto	 [decreto] <prop> N M S @<ACC
nº	 [nº] N M S @<ACC
$.	 [$.] PU <<<
19	 [19] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
19	 [19] <card> NUM M/F P @P<
de	 [de] PRP @N<
março	 [março] N M S @P<
de	 [de] PRP @N<
1933	 [1933] <card> NUM M/F P @P<
$,
para	 [para] PRP @ADVL
fins	 [fim] N M P @P<
de	 [de] PRP @N<
compatibilização	 [compatibilização] N F S @P<
com	 [com] PRP @N<
os	 [o] <artd> DET M P @>N
recursos	 [recurso] N M P @P<
orçamentários	 [orçamentário] ADJ M P @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
3º.	 [3º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
O	 [o] <artd> DET M S @>N
disposto	 [dispor] V PCP M S @IMV @#ICL-<PRED
em	 [em] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
incisos	 [inciso] ADJ M P @>N
I	 [i] <prop> N M S @P<
$,
IV	 [IV] <NUM-ord> ADJ M/F S @N<PRED
e	 [e] <co-subj> KC @CO
V	 [V] <prop> <n> <NUM-ord> ADJ M/F S @SUBJ>
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
não	 [não] ADV @ADVL>
se	 [se] <refl> PERS M/F 3S ACC @ACC>-PASS
aplica	 [aplicar] <fmc> V PR 3S IND VFIN @FMV
a	 [a] <sam-> PRP @<PIV
o	 [o] <-sam> <artd> DET M S @>N
Banco=Central=do=Brasil	 [Banco=Central=do=Brasil] PROP M S @P<
e	 [e] <co-piv> KC @CO
a	 [a] <sam-> PRP @<PIV
as	 [o] <-sam> <artd> DET F P @>N
instituições	 [instituição] N F P @P<
financeiras	 [financeiro] ADJ F P @N<
públicas	 [público] ADJ F P @N<
federais	 [federal] ADJ F P @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @NPHR
4º.	 [4º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Em	 [em] PRP @ADVL>
casos	 [caso] N M P @P<
excepcionais	 [excepcional] ADJ M P @N<
$,
e	 [e] KC @CO
desde=que	 [desde=que] KS @SUB
de=acordo	 [de=acordo] ADV @ADVL>
com	 [com] PRP @A<
as	 [o] <artd> DET F P @>N
metas	 [meta] N F P @P<
de	 [de] PRP @N<
emissão	 [emissão] N F S @P<
de	 [de] PRP @N<
moeda	 [moeda] N F S @P<
constantes	 [constante] N F P @PRED>
de	 [de] <sam-> PRP @N<
esta	 [este] <dem> <-sam> DET F S @>N
medida	 [medida] N F S @P<
provisória	 [provisório] ADJ F S @N<
$,
o	 [o] <artd> DET M S @>N
presidente	 [presidente] N M S @SUBJ>
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
República	 [república] <prop> N F S @P<
$,
por	 [por] PRP @ADVL>
proposta	 [proposta] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
ministro=da=Fazenda	 [ministro=da=Fazenda] N M S @P<
$,
poderá	 [poder] <fmc> V FUT 3S IND VFIN @FAUX
afastar	 [afastar] V INF @IMV @#ICL-AUX<
a	 [o] <artd> DET F S @>N
suspensão	 [suspensão] N F S @<ACC
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
trata	 [tratar] V PR 3S IND VFIN @FMV
este	 [este] <dem> DET M S @>N
artigo	 [artigo] N M S @<ACC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
49	 [49] <card> NUM M/F P @SUBJ>
$	 [$] PU
O	 [o] <artd> DET M S @>N
resultado	 [resultado] N M S @SUBJ>
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Banco=Central=do=Brasil	 [Banco=Central=do=Brasil] PROP M S @P<
$,
quando	 [quando] <rel> <ks> ADV @ADVL> @#FS-ADVL>
positivo	 [positivar] V PR 1S IND VFIN @FMV
$,
será	 [ser] <fmc> V FUT 3S IND VFIN @FAUX
utilizado	 [utilizar] V PCP M S @IMV @#ICL-AUX<
para	 [para] PRP @<ADVL
amortização	 [amortização] N F S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
dívida=pública	 [dívida=pública] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Tesouro=Nacional	 [Tesouro=Nacional] PROP M S @P<
$,
devendo	 [dever] V GER @IAUX @#ICL-<ADVL
ser	 [ser] V INF @IAUX @#ICL-AUX<
amortizada	 [amortizar] <DERS> <DERS> V PCP F S @IMV @#ICL-AUX<
prioritariamente	 [prioritário] ADV @<ADVL
a	 [o] <artd> DET F S @>N
dívida	 [dívida] N F S @<ACC
em	 [em] PRP @<ADVL
poder	 [poder] N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Banco=Cental=do=Brasil	 [Banco=Cental=do=Brasil] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
50	 [50] <card> NUM M/F P @NPHR
$	 [$] PU
O	 [o] <artd> DET M S @>N
art.	 [art.] N M S @NPHR
1º	 [1º] <card> NUM M/F P @N<
$.	 [$.] PU <<<
de	 [de] <sam-> PRP @ADVL
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.392	 [8.392] <card> NUM M/F S @SUBJ>
$,
de	 [de] PRP @ADVL>
30	 [30] <card> NUM M/F P @P<
de	 [de] PRP @N<
dezembro	 [dezembro] N M S @P<
de	 [de] PRP @N<
1991	 [1991] <card> NUM M/F P @P<
$,
passa	 [passar] <fmc> V PR 3S IND VFIN @FAUX
a	 [a] PRP @PRT-AUX<
vigorar	 [vigorar] V INF @IMV @#ICL-AUX<
com	 [com] PRP @<ADVL
a	 [o] <artd> DET F S @>N
seguinte	 [seguinte] ADJ F S @>N
redação	 [redação] N F S @P<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] <*1> PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
1º.	 [1º.] <NUM-ord> ADJ M/F S @SUBJ>
$	 [$] PU
É	 [ser] <fmc> V PR 3S IND VFIN @FAUX
prorrogado	 [prorrogar] V PCP M S @IMV @#ICL-AUX<
$,
até	 [até] PRP @<ADVL
a	 [o] <artd> DET F S @>N
data	 [data] N F S @P<
de	 [de] PRP @N<
promulgação	 [promulgação] N F S @P<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
lei	 [lei] N F S @P<
complementar	 [complementar] ADJ F S @N<
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
trata	 [tratar] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
art.	 [art.] N M S @<ACC
192	 [192] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Constituição=Federal	 [Constituição=Federal] PROP F S @P<
$,
o	 [o] <artd> DET M S @>N
prazo	 [prazo] N M S @APP
a	 [a] PRP @ADVL>
que	 [que] KS @SUB @#FS-<ACC
se	 [se] PERS M/F 3S/P ACC @SUBJ>
refere	 [referir] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
art.	 [art.] N M S @<SUBJ
1º	 [1º] <card> NUM M/F P @N< @<ACC
$.	 [$.] PU <<<
de	 [de] <sam-> PRP @ADVL
as	 [o] <artd> <-sam> DET F P @>N
Leis	 [lei] <prop> N F P @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.056	 [8.056] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
28	 [28] <card> NUM M/F P @P<
de	 [de] PRP @N<
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1990	 [1990] <card> NUM M/F P @P<
$,
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.127	 [8.127] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
20	 [20] <card> NUM M/F P @P<
de	 [de] PRP @N<
dezembro	 [dezembro] N M S @P<
de	 [de] PRP @N<
1990	 [1990] <card> NUM M/F P @P<
$,
e	 [e] KC @CO
nº	 [nº] N M S @PRED>
8.201	 [8.201] <card> NUM M/F P @N<
$,
de	 [de] PRP @ADVL
29	 [29] <card> NUM M/F P @P<
de	 [de] PRP @N<
julho	 [julho] N M S @P<
de	 [de] PRP @N<
1991	 [1991] <card> NUM M/F P @P<
$,
exceto	 [exceto] PRP @ADVL
no=que=se=refere	 [no=que=se=refere] ADV @ADVL
a	 [a] <sam-> PRP @A<
o	 [o] <-sam> <artd> DET M S @>N
disposto	 [dispor] <n> V PCP M S @IMV @#ICL-P<
em	 [em] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
arts ALT xxxs	 [art] N M P @P<
$.	 [$.] PU <<<
4º.	 [4º.] <NUM-ord> ADJ M/F S @PRED>
$,
inciso	 [inciso] ADJ M S @>N
I	 [i] <prop> N M S @NPHR
$,
6º.	 [6º.] <NUM-ord> ADJ M/F S @NPHR
e	 [e] KC @CO
7º.	 [7º.] <NUM-ord> ADJ M/F S @NPHR
$,
todos	 [todo] <quant> DET M P @NPHR
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
4.495	 [4.495] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
31	 [31] <card> NUM M/F P @P<
de	 [de] PRP @N<
dezembro	 [dezembro] N M S @P<
de	 [de] PRP @N<
1964	 [1964] <card> NUM M/F P @P<
$.	 [$.] PU <<<
$"	 [$"] PU
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
51	 [51] <card> NUM M/F P @NPHR
$	 [$] PU
O=Art	 [O=Art] PROP M S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
4º.	 [4º.] <n> <NUM-ord> ADJ M/F S @NPHR
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @<PRED @NPHR
$.	 [$.] PU <<<
5.991	 [5.991] <card> NUM M/F S @SUBJ>
$,
de	 [de] PRP @ADVL>
17	 [17] <card> NUM M/F P @P<
de	 [de] PRP @N<
dezembro	 [dezembro] N M S @P<
de	 [de] PRP @N<
1993	 [1993] <card> NUM M/F P @P<
$,
passa	 [passar] <fmc> V PR 3S IND VFIN @FAUX
a	 [a] PRP @PRT-AUX<
vigorar	 [vigorar] V INF @IMV @#ICL-AUX<
acrescido	 [acrescer] <n> V PCP M S @<ACC
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
seguintes	 [seguinte] ADJ M P @>N
incisos	 [inciso] N M P @P<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
XVIII	 [XVIII] <NUM-ord> <*1> ADJ M/F S @NPHR
$	 [$] PU
Supermercado	 [supermercado] N M S @NPHR
$	 [$] PU
estabelecimento	 [estabelecimento] N M S @NPHR
que	 [que] <rel> SPEC M S @ACC> @#FS-N<
comercializa	 [comercializar] V PR 3S IND VFIN @FMV
mediante	 [mediante] PRP @<ADVL
auto-serviço	 [auto-serviço] N M S @P<
$,
grande	 [grande] ADJ F S @>N
variedade	 [variedade] N F S @N<PRED
de	 [de] PRP @N<
mercadorias	 [mercadoria] N F P @P<
$,
em	 [em] PRP @<ADVL
especial	 [especial] ADJ M S @>N
produtos	 [produto] N M P @P<
alimentícios	 [alimentício] ADJ M P @N<
em=geral	 [em=geral] ADV @<ADVL
$,
e	 [e] KC @CO
produtos	 [produto] N M P @P<
de	 [de] PRP @N<
higiene	 [higiene] N F S @P<
e	 [e] <co-prparg> KC @CO
limpeza	 [limpeza] N F S @P<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
XIX	 [XIX] <NUM-ord> ADJ M/F S @NPHR
$	 [$] PU
Armazém	 [armazém] N M S @NPHR
e	 [e] KC @CO
empório	 [empório] N M S @NPHR
$	 [$] PU
estabelecimento	 [estabelecimento] N M S @NPHR
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
comercializa	 [comercializar] V PR 3S IND VFIN @FMV
$,
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
atacado	 [atacar] <n> V PCP M S @P<
ou	 [ou] <co-advl> KC @CO
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
varejo	 [varejo] N M S @P<
$,
grande	 [grande] ADJ F S @>N
variedade	 [variedade] N F S @<ACC
de	 [de] PRP @N<
mercadorias	 [mercadoria] N F P @P<
e	 [e] <co-acc> KC @CO
$,
de	 [de] PRP @N<PRED
modo	 [modo] N M S @P<
especial	 [especial] ADJ M S @N<
$,
gêneros=alimentícios	 [gêneros=alimentícios] N M P @<ACC @P<
e	 [e] <co-prparg> KC @CO
produtos	 [produto] N M P @<ACC @P<
de	 [de] PRP @N<
higiene	 [higiene] N F S @P<
e	 [e] <co-prparg> KC @CO
limpeza	 [limpeza] N F S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
XX	 [XX] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Loja	 [loja] N F S @NPHR
de	 [de] PRP @N<
conveniência	 [conveniência] N F S @P<
e	 [e] <co-prparg> KC @CO
$'	 [$'] PU
drugstore ALT xxxe	 [drugstore] N M S @P<
$'	 [$'] PU
$	 [$] PU
estabelecimento	 [estabelecimento] N M S @NPHR
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
$,
mediante	 [mediante] PRP @ADVL>
auto-serviço	 [auto-serviço] N M S @P<
ou	 [ou] <co-advl> KC @CO
não	 [não] ADV @ADVL>
$,
comercializa	 [comercializar] V PR 3S IND VFIN @FMV
diversas	 [diverso] ADJ F P @>N
mercadorias	 [mercadoria] N F P @<ACC
$,
com	 [com] PRP @<ADVL
ênfase	 [ênfase] N F S @P<
para	 [para] PRP @<ADVL
aquelas	 [aquele] <dem> DET F P @P<
de=primeira=necessidade	 [de=primeira=necessidade] ADJ @<SC
$,
de	 [de] <sam-> PRP @<ADVL
entre	 [entre] <-sam> PRP @P<
as=quais	 [o=qual] <rel> SPEC F P @P< @#FS-N<
alimentos	 [alimento] N M P @PRED>
em=geral	 [em=geral] ADV @ADVL>
$,
produtos	 [produto] N M P @N<PRED
de	 [de] PRP @N<
limpeza	 [limpeza] N F S @P<
e	 [e] <co-prparg> KC @CO
apetrechos	 [apetrechos] N M P @P<
domésticos	 [doméstico] ADJ M P @N<
$,
podendo	 [poder] V GER @IAUX @#ICL-<ADVL
funcionar	 [funcionar] V INF @IMV @#ICL-AUX<
em	 [em] PRP @<ADVL
qualquer	 [qualquer] <quant> DET M S @>N
período	 [período] N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
dia	 [dia] N M S @P<
e	 [e] <co-postnom> KC @CO
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
noite	 [noite] N F S @P<
$,
iclusive ALT xxxe	 [iclusivar] V PR 3S SUBJ VFIN @FMV
em	 [em] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
domingos	 [domingo] N M P @P<
e	 [e] KC @CO
feriados	 [feriado] <*2> ADJ M P @PRED>
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
52	 [52] <card> NUM M/F P @NPHR
$	 [$] PU
O	 [o] <artd> DET M S @>N
art.	 [art.] N M S @NPHR
6º	 [6º] <card> NUM M/F P @N<
$.	 [$.] PU <<<
de	 [de] <sam-> PRP @ADVL
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
5.991	 [5.991] <card> NUM M/F S @SUBJ>
$,
de	 [de] PRP @ADVL>
17	 [17] <card> NUM M/F P @P<
de	 [de] PRP @N<
dezembro	 [dezembro] N M S @P<
de	 [de] PRP @N<
1973	 [1973] <card> NUM M/F P @P<
$,
passa	 [passar] <fmc> V PR 3S IND VFIN @FAUX
a	 [a] PRP @PRT-AUX<
vigorar	 [vigorar] V INF @IMV @#ICL-AUX<
com	 [com] PRP @<ADVL
seguinte	 [seguinte] ADJ F S @>N
redação	 [redação] N F S @P<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] <*1> PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
6º.	 [6º.] <NUM-ord> ADJ F S @SUBJ>
$	 [$] PU
A	 [o] <artd> DET F S @>N
dispensação	 [dispensação] <DERS> N F S @SUBJ>
de	 [de] PRP @N<
medicamentos	 [medicamento] N M P @P<
é	 [ser] <fmc> V PR 3S IND VFIN @FMV
privativa	 [privativo] ADJ F S @<SC
de	 [de] PRP @A<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
a	 [a] PRP @ADVL
$)	 [$)] PU
farmácia	 [farmácia] N F S @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
b	 [b] N M S @NPHR
$)	 [$)] PU
drogaria	 [drogaria] N F S @NPHR
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
c	 [c] N M S @NPHR
$)	 [$)] PU
posto	 [pôr] V PCP M S @NPHR
de	 [de] PRP @<ADVS
medicamento	 [medicamento] N M S @P<
e	 [e] <co-prparg> KC @CO
unidade	 [unidade] N F S @P<
volante	 [volante] ADJ F S @N<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
d	 [d] N M S @NPHR
$)	 [$)] PU
dispensário	 [dispensário] N M S @NPHR
de	 [de] PRP @N<
medicamentos	 [medicamento] N M P @P<
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
e	 [e] KC @CO
$)	 [$)] PU
supermercado	 [supermercado] N M S @NPHR
$;	 [$;] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
f	 [f] N M S @NPHR
$)	 [$)] PU
armazém	 [armazém] N M S @NPHR
ou	 [ou] KC @CO
empório	 [empório] N M S @NPHR
$;	 [$;] PU <<<
e	 [e] KC @CO
$¶	 [$¶] PU <<<
</s>
<s>
g	 [g] N M S @SUBJ>
$)	 [$)] PU
loja	 [loja] N F S @SUBJ>
de	 [de] PRP @N<
conveniência	 [conveniência] N F S @P<
e	 [e] KC @CO
$'	 [$'] PU
drugstore ALT xxxe	 [drugstorer] <fmc> V PR 3S IND VFIN @FMV
$'	 [$'] PU
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @NPHR
1º.	 [1º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
A	 [o] <artd> DET F S @>N
dispensação	 [dispensação] <DERS> N F S @NPHR
de	 [de] PRP @N<
medicamentos	 [medicamento] N M P @P<
em	 [em] PRP @N<
supermercados	 [supermercado] N M P @P<
$,
armazém	 [armazém] N M S @P< @N<PRED
e	 [e] <co-prparg> KC @CO
empório	 [empório] N M S @P< @<PRED
$;	 [$;] PU <<<
loja	 [loja] N F S @SUBJ>
de	 [de] PRP @N<
conveniência	 [conveniência] N F S @P<
e	 [e] <co-prparg> KC @CO
$'	 [$'] PU
drugstore ALT xxxe	 [drugstore] N M S @P<
$'	 [$'] PU
é	 [ser] <fmc> V PR 3S IND VFIN @FAUX
limitada	 [limitar] V PCP F S @IMV @#ICL-AUX<
a	 [a] <sam-> PRP @<ADVL
o	 [o] <-sam> <artd> DET M S @>N
fornecimento	 [fornecimento] N M S @P<
de	 [de] PRP @N<
drogas	 [droga] N F P @P<
e	 [e] <co-prparg> KC @CO
medicamentos	 [medicamento] N M P @P<
anódinos	 [anódino] ADJ M P @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
não	 [não] ADV @ADVL>
dependem	 [depender] V PR 3P IND VFIN @FMV
de	 [de] PRP @<PIV
receita	 [receita] N F S @P<
médica	 [médico] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
2º	 [2º] <NUM-ord> ADJ M S @N<
$	 [$] PU
Para	 [para] PRP @ADVL>
atendimento	 [atendimento] N M S @P<
exclusivo	 [exclusivo] ADJ M S @N<
a	 [a] PRP @N<
seus	 [seu] <poss 3S> DET M P @>N
usuários	 [usuário] N M P @P<
$,
os	 [o] <artd> DET M P @>N
estabelecimentos	 [estabelecimento] N M P @SUBJ>
hoteleiros	 [hoteleiro] N M P @N<
e	 [e] <co-subj> KC @CO
similares	 [similar] N M P @SUBJ>
poderão	 [poder] <fmc> V FUT 3P IND VFIN @FAUX
dispor	 [dispor] V INF @IMV @#ICL-AUX<
de	 [de] PRP @<PIV
medicamentos	 [medicamento] N M P @P<
anódinos	 [anódino] ADJ M P @N<
$,
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
não	 [não] ADV @ADVL>
dependam	 [depender] V PR 3P SUBJ VFIN @FMV
de	 [de] PRP @<PIV
receita	 [receita] N F S @P<
médica	 [médico] ADJ F S @N<
$,
observada	 [observar] V PCP F S @IMV @#ICL-<ADVL
a	 [o] <artd> DET F S @>N
relação	 [relação] N F S @<SUBJ
elaborada	 [elaborar] V PCP F S @IMV @#ICL-N<
por	 [por] <sam-> PRP @<PASS
o	 [o] <artd> <-sam> DET M S @>N
órgão	 [órgão] N M S @P<
sanitário	 [sanitário] ADJ M S @N<
federal	 [federal] <*2> ADJ M S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
53	 [53] <card> NUM M/F P @NPHR
$	 [$] PU
O	 [o] <artd> DET M S @>N
art.	 [art.] N M S @NPHR
19	 [19] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @<PRED @NPHR
$.	 [$.] PU <<<
5.991	 [5.991] <card> NUM M/F S @SUBJ>
$,
de	 [de] PRP @ADVL>
17	 [17] <card> NUM M/F P @P<
de	 [de] PRP @N<
dezembro	 [dezembro] N M S @P<
de	 [de] PRP @N<
1973	 [1973] <card> NUM M/F P @P<
$,
passa	 [passar] <fmc> V PR 3S IND VFIN @FAUX
a	 [a] PRP @PRT-AUX<
vigorar	 [vigorar] V INF @IMV @#ICL-AUX<
com	 [com] PRP @<ADVL
a	 [o] <artd> DET F S @>N
seguinte	 [seguinte] ADJ F S @>N
redação	 [redação] N F S @P<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] <*1> PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
19	 [19] <card> NUM M/F P @SUBJ>
$	 [$] PU
Não	 [não] ADV @ADVL>
dependerão	 [depender] <fmc> V FUT 3P IND VFIN @FMV
de	 [de] PRP @<PIV
assistência	 [assistência] N F S @P<
técnica	 [técnico] ADJ F S @N<
e	 [e] <co-prparg> KC @CO
responsablidade ALT xxxidade	 [responsablidade] <DERS> N F S @P<
profissional	 [profissional] ADJ M/F S @<PRED
o	 [o] <artd> DET M S @>N
posto	 [posto] N M S @PRED>
de	 [de] PRP @N<
medicamentos	 [medicamento] N M P @P<
$,
a	 [o] <artd> DET F S @>N
unidade	 [unidade] N F S @APP
volante	 [volante] ADJ F S @N<
e	 [e] <co-app> KC @CO
o	 [o] <artd> DET M S @>N
supermercado	 [supermercado] N M S @APP
$,
o	 [o] <artd> DET M S @>N
armazém	 [armazém] N M S @APP
e	 [e] <co-app> KC @CO
o	 [o] <artd> DET M S @>N
empório	 [empório] N M S @APP
$,
a	 [o] <artd> DET F S @>N
loja	 [loja] N F S @APP
de	 [de] PRP @N<
conveniência	 [conveniência] N F S @P<
e	 [e] <co-app> KC @CO
a	 [o] <artd> DET F S @>N
$'	 [$'] PU
drugstore ALT xxxe	 [drugstore] N F S @APP
$'	 [$'] PU
$"	 [$"] PU
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
54	 [54] <card> NUM M/F P @P<
$	 [$] PU
O	 [o] <artd> DET M S @>N
art.	 [art.] N M S @SUBJ>
17	 [17] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @SUBJ>
8.880	 [8.880] <card> NUM M/F P @N<
$,
de	 [de] PRP @ADVL>
27	 [27] <card> NUM M/F P @P<
de	 [de] PRP @N<
maio	 [maio] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
passa	 [passar] <fmc> V PR 3S IND VFIN @FAUX
a	 [a] PRP @PRT-AUX<
vigorar	 [vigorar] V INF @IMV @#ICL-AUX<
acrescido	 [acrescer] <n> V PCP M S @<ACC
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
seguintes	 [seguinte] ADJ M P @>N
parágrafos	 [parágrafo] N M P @P<
renumerando-	 [renumerar] <hyfen> <DERP> V GER @IMV @#ICL-<ADVL
se	 [se] PERS M/F 3S/P ACC @<SUBJ
os=demais	 [os=demais] DET M P @<ACC
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] <*1> PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
17...	 [17...] <NUM-ord> ADJ M/F S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @PRED>
2º.	 [2º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Interrompida	 [interromper] V PCP F S @N<
a	 [o] <artd> DET F S @>N
apuração	 [apuração] N F S @PRED>
ou	 [ou] <co-pred> KC @CO
divulgação	 [divulgação] N F S @PRED>
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
IPC-r	 [IPC-r] PROP M S @P<
$,
caberá	 [caber] <fmc> V FUT 3S IND VFIN @FMV
a	 [a] <sam-> PRP @<PIV
o	 [o] <-sam> <artd> DET M S @>N
ministro=da=Fazenda	 [ministro=da=Fazenda] N M S @SUBJ>
fixar-	 [fixar] <hyfen> V INF 3S @IMV @#ICL-P<
lo	 [ele] PERS M 3S ACC @<ACC
com	 [com] PRP @<ADVL
base	 [base] N F S @P<
em	 [em] <sam-> PRP @N<PRED
os	 [o] <artd> <-sam> DET M P @>N
indicadores	 [indicador] N M P @P<
disponíveis	 [disponível] ADJ M P @N<
$,
observada	 [observar] V PCP F S @>N
precedência	 [precedência] N F S @N<PRED
em=relação=a	 [em=relação=a] <sam-> PRP @<ADVL
aqueles	 [aquele] <-sam> <dem> DET M P @>N
apurados	 [apurar] <n> V PCP M P @IMV @#ICL-P<
por	 [por] PRP @<PASS
instituições	 [instituição] N F P @P<
oficiais	 [oficial] ADJ F P @N<
de	 [de] PRP @N<
pesquisa	 [pesquisa] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
3º.	 [3º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
No=caso=de	 [no=caso=de] <sam-> PRP @ADVL>
o	 [o] <-sam> <artd> DET M S @>N
parágrafo	 [parágrafo] N M S @P<
anterior	 [anterior] ADJ M S @N<
$,
o	 [o] <artd> DET M S @>N
ministro=da=Fazenda	 [ministro=da=Fazenda] N M S @SUBJ>
divulgará	 [divulgar] <fmc> V FUT 3S IND VFIN @FMV
a	 [o] <artd> DET F S @>N
metodologia	 [metodologia] N F S @<ACC
adotada	 [adotar] V PCP F S @N<
para	 [para] PRP @<ADVL
a	 [o] <artd> DET F S @>N
determinação	 [determinação] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
IPC-r	 [IPC-r] <*2> PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
55	 [55] <card> NUM M/F P @NPHR
$	 [$] PU
A=Lei	 [A=Lei] PROP F S @NPHR
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.884	 [8.884] <card> NUM M/F S @SUBJ>
$,
de	 [de] PRP @ADVL>
11	 [11] <card> NUM M/F P @P<
de	 [de] PRP @N<
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
passa	 [passar] <fmc> V PR 3S IND VFIN @FAUX
a	 [a] PRP @PRT-AUX<
vigorar	 [vigorar] V INF @IMV @#ICL-AUX<
com	 [com] PRP @<ADVL
as	 [o] <artd> DET F P @>N
seguintes	 [seguinte] ADJ F P @>N
alterações	 [alteração] N F P @P<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] <*1> PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
17...	 [17...] <NUM-ord> ADJ M/F S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
XXII	 [XXII] PROP M/F S @NPHR
$--	 [$--] PU
indicar	 [indicar] V INF @IMV
o	 [o] <artd> DET M S @>N
substituto	 [substituto] N M S @<SUBJ
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
procurador-geral	 [procurador-geral] N M S @P<
em	 [em] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
casos	 [caso] N M P @P<
de	 [de] PRP @N<
afastamento	 [afastamento] N M S @P<
ou	 [ou] <co-prparg> KC @CO
impedimento	 [impedimento] N M S @<ACC @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
11º...	 [11º...] <NUM-ord> ADJ M/F S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
3º.	 [3º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Em	 [em] <sam-> PRP @ADVL>
os	 [o] <artd> <-sam> DET M P @>N
casos	 [caso] N M P @P<
e	 [e] <co-subj> KC @CO
afastamento	 [afastamento] N M S @SUBJ>
temporário	 [temporário] ADJ M S @N<
ou	 [ou] <co-subj> KC @CO
impedimento	 [impedimento] N M S @SUBJ>
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
procurador-geral	 [procurador-geral] N M S @P<
$,
o	 [o] <artd> DET M S @>N
plenário	 [plenário] N M S @SUBJ>
indicará	 [indicar] <fmc> V FUT 3S IND VFIN @FMV
e	 [e] <co-vfin> <co-fmc> KC @CO
o	 [o] <artd> DET M S @>N
presidente	 [presidente] N M S @<ACC
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Cade	 [cade] <prop> N M S @P<
nomeará	 [nomear] <fmc> V FUT 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
substituto	 [substituto] N M S @<ACC
$,
dispensada	 [dispensar] V PCP F S @IMV @#ICL-<ADVL
a	 [o] <artd> DET F S @>N
aprovação	 [aprovação] N F S @<SUBJ
por	 [por] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
Senado=Federal	 [Senado=Federal] PROP M S @P<
$,
fazendo	 [fazer] V GER @IMV @#ICL-<ADVL
ele	 [ele] PERS M 3S NOM @<SUBJ
jus	 [jus] N M S @<ACC
a	 [a] <sam-> PRP @<ADVL
a	 [o] <-sam> <artd> DET F S @>N
remuneração	 [remuneração] N F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
cargo	 [cargo] N M S @P<
enquanto	 [enquanto] <ks> <rel> ADV @ADVL> @#FS-<ADVL @#FS-N<
durar	 [durar] V FUT 3S SUBJ VFIN @FMV
a	 [o] <artd> DET F S @>N
substituição	 [substituição] N F S @<SUBJ
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
20º....	 [20º....] <NUM-ord> ADJ M/F S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @SUBJ>
3º.	 [3º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
A	 [o] <artd> DET F S @>N
posição	 [posição] N F S @SUBJ>
dominante	 [dominante] ADJ F S @N<
a	 [a] PRP @N<
que	 [que] <rel> SPEC M S @ACC> @#FS-P<
se	 [se] PERS M/F 3S/P ACC @SUBJ>
refere	 [referir] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
parágrafo	 [parágrafo] N M S @SUBJ>
anterior	 [anterior] ADJ M S @N<
é	 [ser] <fmc> V PR 3S IND VFIN @FAUX
presumida	 [presumir] V PCP F S @IMV @#ICL-AUX<
quando	 [quando] <rel> <ks> ADV @ADVL> @#FS-<ADVL
a	 [o] <artd> DET F S @>N
empresa	 [empresa] N F S @SUBJ>
ou	 [ou] <co-subj> KC @CO
grupo	 [grupo] N M S @SUBJ>
de	 [de] PRP @N<
empresas	 [empresa] N F P @P<
controla	 [controlar] V PR 3S IND VFIN @FMV
20	 [20] <card> NUM M/F P @>N
$%	 [%] N M P @<ACC	 [$%] PU
$(	 [$(] PU
vinte	 [vinte] <card> NUM M P @>N
por=cento	 [por=cento] N M P @N<PRED
$)	 [$)] PU
de	 [de] PRP @<ADVL
mercado	 [mercado] N M S @P<
relevante	 [relevante] ADJ M S @N<
$,
podendo	 [poder] V GER @IAUX @#ICL-<ADVL
este	 [este] <dem> DET M S @>N
percentual	 [percentual] <n> ADJ M S @<ACC
ser	 [ser] V INF @IMV @#ICL-AUX<
alterado	 [alterar] V PCP M S @IMV
por	 [por] <sam-> PRP @<PASS
o	 [o] <artd> <-sam> DET M S @>N
Cade	 [cade] <prop> N M S @P<
para	 [para] PRP @<ADVL
setores	 [setor] N M P @P<
específicos	 [específico] ADJ M P @N<
de	 [de] PRP @N<
economia	 [economia] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
23º....	 [23º....] <NUM-ord> ADJ M/F S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
III	 [III] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
No=caso=de	 [no=caso=de] <sam-> PRP @ADVL>
as	 [elas] <-sam> PERS F 3P ACC @ACC>
demais	 [demais] <quant> ADV @>A
pessoas=físicas	 [pessoa=física] N F P @SUBJ>
jurídicas	 [jurídico] ADJ F P @N<
de=direito	 [de=direito] ADV @ADVL>
público	 [público] ADJ M S @SUBJ> @N<
ou	 [ou] <co-postnom> KC @CO
privado	 [privado] ADJ M S @N<
$,
bem=como	 [bem=como] <rel> ADV @ADVL> @#AS-ADVL>
quaisquer	 [qualquer] <quant> DET F P @>N
associações	 [associação] N F P @AS<
de	 [de] PRP @N<
entidades	 [entidade] N F P @P<
ou	 [ou] <co-prparg> KC @CO
pessoas	 [pessoa] N F P @P<
constituídas	 [constituído] ADJ F P @N<
de=fato	 [de=fato] ADJ @N<
ou	 [ou] KC @CO
de=direito	 [de=direito] ADV @ADVL>
$,
ainda=que	 [ainda=que] KS @SUB @#AS-ADVL>
temporariamente	 [temporário] ADV @ADVL>
$,
com	 [com] PRP @N<PRED @ADVL>
ou	 [ou] <co-advl> KC @CO
sem	 [sem] PRP @N<PRED @ADVL>
personalidade	 [personalidade] N F S @P<
jurídica	 [jurídico] ADJ F S @N<
$,
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
não	 [não] ADV @ADVL>
exerçam	 [exercer] V PR 3P SUBJ VFIN @FMV
atividade	 [atividade] N F S @<ACC
empresarial	 [empresarial] ADJ F S @N<
$,
não	 [não] ADV @ADVL>
sendo	 [ser] V GER @IMV @#ICL-<ADVL
possível	 [possível] ADJ M S @<SC
utilizar-	 [utilizar] <hyfen> V INF @IMV
se	 [se] PERS M 3S/P ACC @<ACC-PASS
o	 [o] <artd> DET M S @>N
critério	 [critério] N M S @<SUBJ
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
valor	 [valor] N M S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
faturamento	 [faturamento] N M S @P<
bruto	 [bruto] ADJ M S @N<
$,
a	 [o] <artd> DET F S @>N
multa	 [multa] N F S @SUBJ>
será	 [ser] <fmc> V FUT 3S IND VFIN @FMV
de	 [de] PRP @<SC
6.000	 [6.000] <card> NUM M/F P @P<
$(	 [$(] PU
seis=mil	 [seis=mil] <card> NUM M/F P @NUM<
$)	 [$)] PU
a	 [a] PRP @<ADVL
6.000.000	 [6.000.000] <card> NUM M/F P @P<
$(	 [$(] PU
seis	 [seis] <card> NUM M P @>N
milhões	 [milhão] N M P @P<
$)	 [$)] PU
de	 [de] PRP @N<
Unidades=Fiscais=de=Referência	 [Unidades=Fiscais=de=Referência] PROP M/F S @P<
$	 [$] PU
Ufir	 [Ufir] PROP F S @<SC
$	 [$] PU
$,
ou	 [ou] KC @CO
padrão	 [padrão] N M S @P<
superveniente	 [superveniente] ADJ M S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
42º.	 [42º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Recebido	 [recebido] ADJ M S @PRED>
o	 [o] <artd> DET M S @>N
processo	 [processo] N M S @SUBJ>
$,
o	 [o] <artd> DET M S @>N
presidente	 [presidente] N M S @SUBJ>
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Cade	 [cade] <prop> N M S @P<
o	 [ele] PERS M 3S ACC @ACC>
distribuirá	 [distribuir] <fmc> V FUT 3S IND VFIN @FMV
$,
mediante	 [mediante] PRP @<ADVL
sorteio	 [sorteio] N M S @P<
$,
a	 [a] <sam-> PRP @<PIV
o	 [o] <-sam> <artd> DET M S @>N
conselheiro-redator	 [conselheiro-redator] N M S @P<
$,
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
abrirá	 [abrir] V FUT 3S IND VFIN @FMV
vistas	 [vista] N F P @<ACC
a	 [a] <sam-> PRP @<ADVL
a	 [o] <-sam> <artd> DET F S @>N
Procuradoria	 [procuradoria] <prop> N F S @P<
para	 [para] PRP @<ADVL
manifestar-	 [manifestar] <hyfen> V INF @IMV @#ICL-P<
se	 [se] <refl> PERS M 3S ACC @<ACC
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
prazo	 [prazo] N M S @P<
de	 [de] PRP @N<
vinte	 [vinte] <card> NUM M P @>N
dias	 [dia] N M P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
47º.	 [47º.] <NUM-ord> ADJ M/F S @ACC>
$	 [$] PU
O=Cade	 [O=Cade] PROP M S @SUBJ>
fiscalizará	 [fiscalizar] <fmc> V FUT 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
cumprimento	 [cumprimento] N M S @<ACC
de	 [de] PRP @N<
suas	 [seu] <poss 3S> DET F P @>N
decisões	 [decisão] N F P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
54º....	 [54º....] <NUM-ord> ADJ M/F S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] N M S @PRED>
3º.	 [3º.] <NUM-ord> ADJ M S @N<
$	 [$] PU
Incluem-	 [incluir] <hyfen> <fmc> V PR 3P IND VFIN @FMV
se	 [se] <refl> PERS M/F 3P ACC @<ACC-PASS
em	 [em] <sam-> PRP @<ADVL
os	 [o] <artd> <-sam> DET M P @>N
atos	 [ato] N M P @P<
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
trata	 [tratar] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
caput ALT xxx	 [caput] N M S @<ACC
aqueles	 [aquele] <dem> DET M P @SUBJ>
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
visem	 [visar] V PR 3P SUBJ VFIN @FMV
a	 [a] PRP @<PIV
qualquer	 [qualquer] <quant> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] PRP @N<
concentração	 [concentração] N F S @P<
econômica	 [econômico] ADJ F S @N<
$,
seja	 [ser] <fmc> V PR 3S SUBJ VFIN @FMV
através	 [através] ADV @<ADVL
de	 [de] PRP @<SC
fusão	 [fusão] N F S @P<
ou	 [ou] <co-prparg> KC @CO
incorporação	 [incorporação] N F S @P<
de	 [de] PRP @N<
empresas	 [empresa] N F P @P<
$,
constituição	 [constituição] N F S @N<PRED
de	 [de] PRP @N<
sociedade	 [sociedade] N F S @P<
para	 [para] PRP @<ADVL
exercer	 [exercer] V INF @IMV @#ICL-P<
o	 [o] <artd> DET M S @>N
controle	 [controle] N M S @<ACC
de	 [de] PRP @N<
empresas	 [empresa] N F P @P<
ou	 [ou] <co-acc> KC @CO
qualquer	 [qualquer] <quant> DET F S @>N
forma	 [forma] N F S @<ACC
de	 [de] PRP @N<
agrupamento	 [agrupamento] N M S @P<
societário	 [societário] ADJ M S @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-N<
implique	 [implicar] V PR 3S SUBJ VFIN @FMV
participação	 [participação] N F S @<ACC
de	 [de] PRP @N<
empresas	 [empresa] N F P @P<
resultante	 [resultante] ADJ F S @N<
em	 [em] PRP @N<
20	 [20] <card> NUM M/F P @>N
$%	 [%] N M P @P<	 [$%] PU
$(	 [$(] PU
vinte	 [vinte] <card> NUM M P @>N
por=cento	 [por=cento] N M P @N<PRED
$)	 [$)] PU
de	 [de] PRP @<ADVL
um	 [um] <arti> DET M S @>N
mercado	 [mercado] N M S @P<
relevante	 [relevante] ADJ M S @N<
$,
ou	 [ou] <co-advl> KC @CO
em	 [em] PRP @<ADVL
que	 [que] KS @SUB @#FS-P<
qualquer	 [qualquer] <quant> DET M/F S @SUBJ>
de	 [de] <sam-> PRP @N<
os	 [o] <artd> <-sam> DET M P @>N
participantes	 [participante] N M P @P<
tenha	 [ter] V PR 3S SUBJ VFIN @FAUX
registrado	 [registrar] V PCP @IMV @#ICL-AUX<
faturamento	 [faturamento] N M S @<ACC
bruto	 [bruto] ADJ M S @N<
anual	 [anual] ADJ M S @N<
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
último	 [último] <NUM-ord> ADJ M S @>N
balanço	 [balanço] N M S @P<
equivalente	 [equivalente] ADJ M S @N<
a	 [a] PRP @A<
100.000.000	 [100.000.000] <card> NUM M/F P @P<
$(	 [$(] PU
cem	 [cem] <card> NUM M P @>N
milhões	 [milhão] N M P @N<PRED
$)	 [$)] PU
de	 [de] PRP @N<
Ufir	 [Ufir] PROP M/F S @P<
$,
ou	 [ou] <co-acc> KC @CO
unidade	 [unidade] N F S @<ACC
de	 [de] PRP @N<
valor	 [valor] N M S @P<
superveniente	 [superveniente] ADJ M S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
$...	 [$...] PU
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
59º.	 [59º.] <NUM-ord> ADJ M/F S @SUBJ>
$	 [$] PU
O=Cade	 [O=Cade] PROP M S @SUBJ>
podrá ALT xxx	 [podrá] N M S @NPHR
responder	 [responder] V INF 0/1/3S @IMV @#ICL-ACC>
a	 [a] PRP @<PIV
consultas	 [consulta] N F P @P<
sobre	 [sobre] PRP @N<
acordos	 [acordo] N M P @P<
que	 [que] KS @SUB @#FS-<ACC
importem	 [importar] V PR 3P SUBJ VFIN @FMV
em	 [em] PRP @<PIV
concentração	 [concentração] N F S @P<
econômica	 [econômico] ADJ F S @N<
$,
em	 [em] <sam-> PRP @<ADVL
a	 [o] <artd> <-sam> DET F S @>N
forma	 [forma] N F S @P<
de	 [de] PRP @N<
que	 [que] <rel> SPEC M S @SUBJ> @#FS-P<
dispuser	 [dispor] V FUT 3S SUBJ VFIN @FMV
seu	 [seu] <poss 3S> DET M S @>N
regimento	 [regimento] N M S @<ACC
interno	 [interno] ADJ M S @N<
$.	 [$.] PU <<<
$"	 [$"] PU
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
56	 [56] <card> NUM M/F P @NPHR
$	 [$] PU
O	 [o] <artd> DET M S @>N
parágrafo	 [parágrafo] N M S @NPHR
2º	 [2º] <NUM-ord> ADJ M S @N<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
art.	 [art.] N M S @P<
36	 [36] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @<PRED @NPHR
$.	 [$.] PU <<<
8.880	 [8.880] <card> NUM M/F S @SUBJ>
$,
de	 [de] PRP @ADVL>
27	 [27] <card> NUM M/F P @P<
de	 [de] PRP @N<
maio	 [maio] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
passa	 [passar] <fmc> V PR 3S IND VFIN @FAUX
a	 [a] PRP @PRT-AUX<
vigorar	 [vigorar] V INF @IMV @#ICL-AUX<
com	 [com] PRP @<ADVL
a	 [o] <artd> DET F S @>N
seguinte	 [seguinte] ADJ F S @>N
redação	 [redação] N F S @P<
$:	 [$:] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Parágrafo	 [parágrafo] <*1> N M S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
2º	 [2º] <NUM-ord> ADJ M S @SUBJ>
$	 [$] PU
A	 [o] <artd> DET F S @>N
justificação	 [justificação] N F S @SUBJ>
a	 [a] PRP @PIV>
que	 [que] KS @SUB @#FS-<ACC
se	 [se] PERS M/F 3S/P ACC @SUBJ>
refere	 [referir] V PR 3S IND VFIN @FMV
o	 [o] <artd> DET M S @>N
caput ALT xxx	 [caput] N M S @<ACC
de	 [de] <sam-> PRP @N<
este	 [este] <dem> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
fará-	 [fazer] <hyfen> <fmc> V FUT 3S IND VFIN @FMV
se-	 [se] <hyfen> PERS M/F 3S ACC @<ACC-PASS
perante	 [perante] PRP @<ADVL
a	 [o] <artd> DET F S @>N
Secretaria=de=Política=Econômica	 [Secretaria=de=Política=Econômica] PROP F S @P<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
Ministério=da=Fazenda	 [Ministério=da=Fazenda] <*2> PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Capítulo=VIII	 [Capítulo=VIII] PROP M S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
De	 [de] <sam-> PRP @ADVL
as	 [o] <artd> <-sam> DET F P @>N
Disposições=Finais	 [Disposições=Finais] PROP F P @P<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
57º.	 [57º.] <NUM-ord> ADJ M/F S @PRED>
$	 [$] PU
Observado	 [observar] V PCP M S @SUBJ>
o	 [o] <artd> DET M S @>N
disposto	 [dispor] V PCP M S @IMV @#ICL-<PRED
em	 [em] <sam-> PRP @<ADVL
o	 [o] <artd> <-sam> DET M S @>N
art.	 [art.] N M S @P<
23	 [23] <card> NUM M/F P @N<
$,
parágrafo	 [parágrafo] N M S @N<PRED
3º	 [3º] <NUM-ord> ADJ M S @N<
$,
ficam	 [ficar] <fmc> V PR 3P IND VFIN @FMV
revogadas	 [revogar] V PCP F P @<SC
as	 [o] <artd> DET F P @>N
Leis	 [lei] <prop> N F P @PRED>
nº	 [nº] N M S @PRED>
6.601	 [6.601] <card> NUM M/F P @N<
$,
de	 [de] PRP @N<PRED
26	 [26] <card> NUM M/F P @P<
de	 [de] PRP @N<
agosto	 [agosto] N M S @P<
de	 [de] PRP @N<
1970	 [1970] <card> NUM M/F P @P<
$,
e	 [e] KC @CO
nº	 [nº] N M S @P<
$.	 [$.] PU <<<
8.646	 [8.646] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
7	 [7] <card> NUM M/F P @P<
de	 [de] PRP @N<
abril	 [abril] N M S @P<
de	 [de] PRP @N<
1993	 [1993] <card> NUM M/F P @P<
$,
o	 [o] <artd> DET M S @>N
inciso	 [inciso] N M S @NPHR
II	 [II] <prop> <NUM-ord> ADJ M S @N<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
art.	 [art.] N M S @P<
2º	 [2º] <card> NUM M/F P @N<
$.	 [$.] PU <<<
de	 [de] <sam-> PRP @ADVL
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.021	 [8.021] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
12	 [12] <card> NUM M/F P @P<
de	 [de] PRP @N<
abril	 [abril] N M S @P<
de	 [de] PRP @N<
1990	 [1990] <card> NUM M/F P @P<
$,
o	 [o] <artd> DET M S @>N
parágrafo	 [parágrafo] N M S @NPHR
único	 [único] ADJ M S @N<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
artigo	 [artigo] N M S @P<
10	 [10] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.177	 [8.177] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N< @ADVL
março	 [março] N M S @P<
de	 [de] PRP @N<
1991	 [1991] <card> NUM M/F P @P<
$,
o	 [o] <artd> DET M S @>N
art.	 [art.] N M S @NPHR
16	 [16] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.178	 [8.178] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
1º.	 [1º.] <n> <NUM-ord> ADJ M/F S @P<
de	 [de] PRP @N< @ADVL
março	 [março] N M S @P<
de	 [de] PRP @N<
1991	 [1991] <card> NUM M/F P @P<
$,
alínea	 [alínea] N F S @NPHR
a	 [a] <*1> <*2> PRP @N<
de	 [de] <sam-> PRP @N<
o	 [o] <artd> <-sam> DET M S @>N
art.	 [art.] N M S @P<
24	 [24] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @NPHR
8.541	 [8.541] <card> NUM M/F P @N<
$,
de	 [de] PRP @ADVL
23	 [23] <card> NUM M/F P @P<
de	 [de] PRP @N<
dezembro	 [dezembro] N M S @P<
de	 [de] PRP @N<
1992	 [1992] <card> NUM M/F P @P<
$,
art.	 [art.] N M S @P<
11	 [11] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.631	 [8.631] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
4	 [4] <card> NUM M/F P @P<
de	 [de] PRP @N<
março	 [março] N M S @P<
de	 [de] PRP @N<
1993	 [1993] <card> NUM M/F P @P<
$,
o	 [o] <artd> DET M S @>N
art.	 [art.] N M S @NPHR
11	 [11] <card> NUM M/F P @N<
de	 [de] <sam-> PRP @N<
a	 [o] <artd> <-sam> DET F S @>N
Lei	 [lei] <prop> N F S @P<
nº	 [nº] N M S @NPHR
$.	 [$.] PU <<<
8.880	 [8.880] <card> NUM M/F P @NPHR
$,
de	 [de] PRP @ADVL
27	 [27] <card> NUM M/F P @P<
de	 [de] PRP @N<
maio	 [maio] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$,
e	 [e] KC @CO
demais	 [demais] <quant> ADV @ADVL
disposições	 [disposição] N F P @NPHR
em=contrário	 [em=contrário] ADV @ADVL
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Art	 [Art] PROP M/F S @NPHR
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
58º.	 [58º.] <NUM-ord> ADJ M/F S @SUBJ>
Esta	 [este] <dem> DET F S @>N
medida	 [medida] N F S @SUBJ>
provisória	 [provisório] ADJ F S @N<
entra	 [entrar] <fmc> V PR 3S IND VFIN @FMV
em=vigor	 [em=vigor] ADV @<ADVL
em	 [em] <sam-> PRP @<ADVS
a	 [o] <artd> <-sam> DET F S @>N
data	 [data] N F S @P<
de	 [de] PRP @N<
sua	 [seu] <poss 3S> DET F S @>N
publicação	 [publicação] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Brasília	 [Brasília] PROP F S @NPHR
$,
30	 [30] <card> NUM M/F P @ADVL
de	 [de] PRP @N<
junho	 [junho] N M S @P<
de	 [de] PRP @N<
1994	 [1994] <card> NUM M/F P @P<
$;	 [$;] PU <<<
173º	 [173º] <card> NUM M/F P @NPHR
$.	 [$.] PU <<<
de	 [de] <sam-> PRP @ADVL
a	 [o] <artd> <-sam> DET F S @>N
Independência	 [independência] <prop> N F S @P<
e	 [e] KC @CO
106º	 [106º] <card> NUM M/F P @NPHR
$.	 [$.] PU <<<
de	 [de] <sam-> PRP @ADVL
a	 [o] <artd> <-sam> DET F S @>N
República	 [república] <prop> N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
</TEXT>
$¶	 [$¶] PU <<<
</DOC>
