<DOC>
<DOCNO.valor=FSP940101-005>
<DOCID.valor=FSP940101-005>
<DATE.valor=940101>
<TEXT>
<s>
Clóvis=Rossi	 [Clóvis=Rossi] PROP M/F S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
São=Paulo	 [São=Paulo] PROP M S @SUBJ>
$	 [$] PU
A	 [o] DET F S <artd> @>N
CPI	 [cPI] <prop> N F S @SUBJ>
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
Orçamento	 [orçamento] <prop> N M S @P<
parece	 [parecer] V PR 3S IND VFIN <fmc> @FAUX
estar	 [estar] V INF @IMV @#ICL-AUX<
se	 [se] PERS M/F 3S ACC <refl> @ACC>
afogando	 [afogar] V GER @IMV @#ICL-<ADVL
em	 [em] PRP @<ADVL
pouca	 [pouco] DET F S <quant> @>N
água	 [água] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Começa	 [começar] V PR 3S IND VFIN <fmc> @FMV
por	 [por] PRP <sam-> @<ADVL
as	 [o] DET F P <artd> <-sam> @>N
divergências	 [divergência] N F P @P<
em=torno=de	 [em=torno=de] PRP <sam-> @<ADVL
a	 [o] DET F S <-sam> <artd> @>N
convocação	 [convocação] N F S @P<
ou	 [ou] KC @CO
não	 [não] ADV @>P
de	 [de] PRP @N<
três	 [três] NUM M P <card> @>N
governadores	 [governador] N M P @P<
para	 [para] PRP @<ADVL
prestar	 [prestar] V INF @IMV @#ICL-P<
depoimento	 [depoimento] N M S @<ACC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Não	 [não] ADV @ADVL>
há	 [haver] V PR 3S IND VFIN <fmc> @FMV
a	 [o] DET F S <artd> @>N
menor	 [pequeno] ADJ F S <KOMP> @>N
lógica	 [lógica] N F S @<ACC
em	 [em] PRP @<ADVL
se	 [se] PERS M/F 3S DAT <refl> @DAT>
hesitar	 [hesitar] V INF @IMV @#ICL-P<
em	 [em] PRP @<PIV
fazer-	 [fazer] V INF @IMV <hyfen> @#ICL-P<
lo	 [ele] PERS M 3S ACC @<ACC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Convocar-	 [convocar] V INF @IMV <hyfen> @#ICL-SUBJ>
los	 [eles] PERS M 3P ACC @<ACC
não	 [não] ADV @ADVL>
significa	 [significar] V PR 3S IND VFIN <fmc> @FMV
que	 [que] KS @SUB @#FS-<ACC
sejam	 [ser] V PR 3P SUBJ VFIN @FAUX
culpados	 [culpar] V PCP M P @IMV @#ICL-AUX<
$,
como	 [como] ADV @#FS-<ADVL <ks> <rel> @ADVL>
aliás	 [aliás] ADV <kc> @ADVL>
ocorreu	 [ocorrer] V PS 3S IND VFIN @FMV
no=caso=de	 [no=caso=de] PRP @<ADVL
todos=os	 [todo=o] DET M P <quant> @>N
demais	 [demais] ADV <quant> @>A
depoentes	 [depoente] N M/F P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
É	 [é] ADV <foc> @FOC>
verdade	 [verdade] N F S @SUBJ>
que	 [que] ADV <foc> @<FOC
a	 [o] DET F S <artd> @>N
simples	 [simples] ADJ F S @>N
presença	 [presença] N F S @SUBJ>
em	 [em] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
CPI	 [cPI] <prop> N F S @P<
pode	 [poder] V PR 3S IND VFIN <fmc> @FAUX
passar	 [passar] V INF @IMV @#ICL-AUX<
a	 [a] PRP <sam-> @<ADVL
o	 [o] DET M S <artd> <-sam> @>N
público	 [público] <n> ADJ M S @P<
a	 [o] DET F S <artd> @>N
impressão	 [impressão] N F S @<ACC
de	 [de] PRP @N<
que	 [que] KS @SUB @#FS-P<
o	 [o] DET M S <artd> @>N
depoente	 [depoente] N M S @SUBJ>
é	 [ser] V PR 3S IND VFIN @FAUX
culpado	 [culpar] V PCP M S @IMV @#ICL-AUX<
e	 [e] <co-fmc> <co-vfin> KC @CO
não	 [não] ADV @ADVL>
apenas	 [apenas] ADV @ADVL>
suspeito	 [suspeitar] V PR 1S IND VFIN <fmc> @FMV
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Mas	 [mas] KC @CO
esse	 [esse] DET M S <dem> @>N
tipo	 [tipo] N M S @SUBJ>
de	 [de] PRP @N<
preocupação	 [preocupação] N F S @P<
não	 [não] ADV @ADVL>
pode	 [poder] V PR 3S IND VFIN <fmc> @FAUX
manietar	 [manietar] V INF @IMV @#ICL-AUX<
a	 [o] DET F S <artd> @>N
CPI	 [cPI] <prop> N F S @<ACC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Até	 [até] ADV @ADVL
porque	 [porque] KS @#FS-ADVL> @SUB
político	 [político] N M S @SUBJ>
$,
em=geral	 [em=geral] ADV @ADVL>
$,
culpado	 [culpado] ADJ M S @N<PRED
ou	 [ou] KC @CO
inocente	 [inocente] ADJ M/F S @N<PRED
$,
mencionado	 [mencionar] V PCP M S @N<PRED
ou	 [ou] KC @CO
não	 [não] ADV @>P
em	 [em] PRP <sam-> @ADVL>
o	 [o] DET M S <artd> <-sam> @>N
escandalo	 [cândicândi] V PR 1S IND VFIN <DERS> <DERS> <DERP> @P<
de	 [de] PRP <sam-> @N<PRED
o	 [o] DET M S <artd> <-sam> @>N
Orçamento	 [orçamento] <prop> N M S @P<
$,
é	 [ser] V PR 3S IND VFIN <fmc> @FMV
hoje	 [hoje] ADV @<ADVL
em	 [em] PRP <sam-> @<SC
o	 [o] DET M S <artd> <-sam> @>N
mínimo	 [pequeno] ADJ M S <SUP> @>N
suspeito	 [suspeito] N M S @P<
aos=olhos=de	 [aos=olhos=de] PRP @<ADVL
boa	 [bom] ADJ F S @>N
parte	 [parte] N F S @P<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
público	 [público] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Se	 [se] KS @#FS-ADVL> @SUB
a	 [o] DET F S <artd> @>N
CPI	 [cPI] <prop> N F S @SUBJ>
passar	 [passar] V FUT 3S SUBJ VFIN @FMV
a	 [o] DET F S <artd> @>N
impressão	 [impressão] N F S @<ACC
de	 [de] PRP @N< @PIV>
que	 [que] KS @SUB @#FS-P<
está	 [estar] V PR 3S IND VFIN @FAUX
protegendo	 [proteger] V GER @#ICL-AUX< @IMV
um	 [um] NUM M S <card> @>N
ou	 [ou] <co-vfin> KC @CO
outro	 [outro] DET M S <KOMP> <diff> @>N
político	 [político] N M S @<ACC
$,
essa	 [esse] DET F S <dem> @>N
injusta	 [injusto] ADJ F S @>N
suspeição	 [suspeição] N F S @SUBJ>
disseminada	 [disseminar] V PCP F S @N<
sobre	 [sobre] PRP @N<
os	 [o] DET M P <artd> @>N
políticos	 [político] N M P @P<
acabará	 [acabar] V FUT 3S IND VFIN <fmc> @FAUX
se	 [se] PERS M/F 3S ACC @SUBJ>
justificando	 [justificar] V GER @#ICL-AUX< @IMV
a=posteriori	 [a=posteriori] ADV @<ADVL
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Além=de	 [além=de] PRP <sam-> @ADVL>
isso	 [isso] SPEC M S <-sam> <dem> @P<
$,
a	 [o] DET F S <artd> @>N
CPI	 [cPI] <prop> N F S @SUBJ>
não	 [não] ADV @ADVL>
pode	 [poder] V PR 3S IND VFIN <fmc> @FAUX
ficar	 [ficar] V INF @IMV @#ICL-AUX<
presa	 [prender] V PCP F S @IMV @#ICL-<SC
a	 [a] PRP <sam-> @<PIV
o	 [o] DET M S <artd> <-sam> @>N
17	 [17] NUM M P <card> @<ADVL
de	 [de] PRP @N<
janeiro	 [janeiro] N M S @P<
como	 [como] ADV @COM <prp> <rel> @#AS-<ADVL
prazo	 [prazo] N M S @AS<
para	 [para] PRP @N<
encerramento	 [encerramento] N M S @P<
de	 [de] PRP @N<
seus	 [seu] DET M P <poss 3S> @>N
trabalhos	 [trabalho] N M P @P<
$,
como=se	 [como=se] KS @SUB @#FS-<ADVL
fosse	 [ser] V IMPF 3S SUBJ VFIN @FMV
uma	 [um] DET F S <arti> @>N
data	 [data] N F S @<SC
cabalística	 [cabalístico] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> @>N
importante	 [importante] <n> ADJ M S @SC>
não	 [não] ADV @ADVL>
é	 [ser] V PR 3S IND VFIN <fmc> @FMV
quando	 [quando] ADV @#FS-<ADVL <ks> <rel> @ADVL>
a	 [o] DET F S <artd> @>N
CPI	 [cPI] <prop> N F S @SUBJ>
vai	 [ir] V PR 3S IND VFIN @FAUX
terminar	 [terminar] V INF @IMV @#ICL-AUX<
$,
mas	 [mas] <co-vfin> KC @CO
como	 [como] ADV @#FS-<ADVL <ks> <rel> @ADVL>
vai	 [ir] V PR 3S IND VFIN @FAUX
terminar	 [terminar] V INF @IMV @#ICL-AUX<
$,
se	 [se] KS @#AS-N< @#AS-<ADVL @SUB
em	 [em] PRP @<ADVL
pizza	 [pizza] N F S @P<
ou	 [ou] <co-vfin> KC @CO
em	 [em] PRP @<ADVL
uma	 [um] DET F S <arti> @>N
apuração	 [apuração] N F S @P<
que	 [que] SPEC M/F S @ACC> <rel> @#FS-N<
a	 [o] DET F S <artd> @>N
sociedade	 [sociedade] N F S @SUBJ>
possa	 [poder] V PR 3S SUBJ VFIN @FAUX
tomar	 [tomar] V INF @IMV @#ICL-AUX<
em	 [em] PRP <sam-> @<ADVL
o	 [o] DET M S <artd> <-sam> @>N
mínimo	 [pequeno] <n> ADJ M S <SUP> @P<
como	 [como] ADV @#AS-<ADVL <prp> <rel> @ADVL
aceitável	 [aceitável] ADJ M/F S @AS<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> @>N
argumento	 [argumento] N M S @SUBJ>
de	 [de] PRP @N<
que	 [que] KS @SUB @#FS-P<
a	 [o] DET F S <artd> @>N
prorrogação	 [prorrogação] N F S @SUBJ>
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
prazo	 [prazo] N M S @P<
pode	 [poder] V PR 3S IND VFIN @FAUX
impedir	 [impedir] V INF @IMV @#ICL-AUX<
a	 [o] DET F S <artd> @>N
revisão	 [revisão] N F S @<ACC
constitucional	 [constitucional] ADJ F S @N<
é	 [ser] V PR 3S IND VFIN <fmc> @FMV
confissão	 [confissão] N F S @<SC
de	 [de] PRP @N<
despreparo	 [despreparo] N M S @P<
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
instituição	 [instituição] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> @>N
número	 [número] N M S @SUBJ>
de	 [de] PRP @N<
parlamentares	 [parlamentar] N M P @P<
envolvidos	 [envolver] V PCP M P @IMV @#ICL-N<
em	 [em] PRP <sam-> @<ADVL
a	 [o] DET F S <artd> <-sam> @>N
CPI	 [cPI] <prop> N F S @P<
$(	 [$(] PU
como	 [como] ADV @COM <prp> <rel> @#AS-ADVL>
investigadores	 [investigador] N M P @AS<
ou	 [ou] KC @CO
como	 [como] ADV <rel> @ADVL>
suspeitos	 [suspeito] N M P @SUBJ>
$)	 [$)] PU
é	 [ser] V PR 3S IND VFIN <fmc> @FAUX
relativamente	 [relativamente] ADV @ADVL>
reduzido	 [reduzir] V PCP M S @IMV @#ICL-AUX<
e	 [e] <co-fmc> <co-vfin> KC @CO
$,
por	 [por] PRP @ADVL>
isso	 [isso] SPEC M S <dem> @P<
$,
não	 [não] ADV @ADVL>
pode	 [poder] V PR 3S IND VFIN <fmc> @FAUX
servir	 [servir] V INF @IMV @#ICL-AUX<
de	 [de] PRP @<SC
pretexto	 [pretexto] N M S @P<
para	 [para] PRP @<ADVL
que	 [que] KS @SUB @#FS-P<
fiquem	 [ficar] V PR 3P SUBJ VFIN @FMV
bloqueados	 [bloquear] V PCP M P @<SC
os=demais	 [os=demais] DET M P @>N
trabalhos	 [trabalho] N M P @<SUBJ
próprios	 [próprio] ADJ M P @N<
de	 [de] PRP <sam-> @A<
o	 [o] DET M S <artd> <-sam> @>N
Parlamento	 [parlamento] <prop> N M S @P<
$,
revisão	 [revisão] N F S @<ACC
incluída	 [incluído] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Se	 [se] KS @#FS-<ADVL @SUB
o	 [o] DET M S <artd> @>N
Congresso	 [congresso] <prop> N M S @SUBJ>
achar-	 [achar] V FUT 3S SUBJ VFIN <hyfen> @FMV
se	 [se] PERS M 3S ACC @<ACC-PASS
$,
mesmo	 [mesmo] ADV <quant> @<ADVL
$,
impossibilitado	 [impossibilitado] ADJ M S @<OC
de	 [de] PRP @A<
tocar	 [tocar] V INF @IMV @#ICL-P<
a	 [o] DET F S <artd> @>N
revisão	 [revisão] N F S @<ACC
$,
que	 [que] KS @SUB @#FS-<ADVL
tenha	 [ter] V PR 3S SUBJ VFIN @FMV
a	 [o] DET F S <artd> @>N
grandeza	 [grandeza] N F S @<ACC
de	 [de] PRP @N<
convocar	 [convocar] V INF @IMV @#ICL-P<
um	 [um] DET M S <arti> @>N
Congresso=Revisor	 [Congresso=Revisor] PROP M S @<ACC
exclusivo	 [exclusivo] ADJ M S @N<
$,
conforme	 [conforme] ADV @#AS-<ADVL <prp> <rel> @COM
$,
aliás	 [aliás] ADV <kc> @<ADVL
$,
proposta	 [propor] V PCP F S @N<PRED
de	 [de] PRP <sam-> @<ADVL
o	 [o] DET M S <artd> <-sam> @>N
deputado	 [deputado] N M S @P<
Gonzaga=Motta	 [Gonzaga=Motta] PROP M S @N<
$(	 [$(] PU
PMDB-CE	 [PMDB-CE] PROP M/F S @N<PRED
$)	 [$)] PU
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> @>N
que	 [que] SPEC M/F S @SUBJ> @#FS-SUBJ> <rel>
não	 [não] ADV @ADVL>
seria	 [ser] V COND 3S VFIN @FMV
tolerável	 [tolerável] ADJ M/F S @<SC
é	 [ser] V PR 3S IND VFIN <fmc> @FMV
deixar-	 [deixar] V INF @IMV <hyfen> @#ICL-<SC
se	 [se] PERS M/F 3S ACC @<ACC-PASS
a	 [o] DET F S <artd> @>N
revisão	 [revisão] N F S @<SC
para	 [para] PRP @N<
1995	 [1995] NUM M/F P <card> @P<
$,
porque	 [porque] KS @SUB @#FS-<ADVL
o	 [o] DET M S <artd> @>N
presidente	 [presidente] N M S @SUBJ>
a	 [a] PRP @N<
ser	 [ser] V INF 3S @IAUX @#ICL-P<
eleito	 [eleger] V PCP M S @IMV @#ICL-AUX<
em	 [em] PRP @<ADVL
1994	 [1994] NUM M/F S <card> @P<
precisa	 [precisar] V PR 3S IND VFIN @FMV
começar	 [começar] V INF @IMV @#ICL-<ACC
sua	 [seu] DET F S <poss 3S> @>N
gestão	 [gestão] N F S @<SUBJ
com	 [com] PRP @<ADVL
a	 [o] DET F S <artd> @>N
questão	 [questão] N F S @P<
resolvida	 [resolvido] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Chega	 [chegar] V PR 3S IND VFIN <fmc> @FMV
de	 [de] PRP @<ADVL
transição	 [transição] N F S @P<
$,
de	 [de] PRP @N<PRED
interinidade	 [interinidade] N F S @P<
$,
de	 [de] PRP @N<PRED
provisoriedade	 [provisoriedade] N F S <DERS> @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> @>N
país	 [país] N M S @SUBJ>
já	 [já] ADV @ADVL>
está	 [estar] V PR 3S IND VFIN <fmc> @FMV
grandinho	 [grandinho] ADJ M S <DERS> @<SC
o	 [o] DET M S <artd> @>N
suficiente	 [suficiente] ADJ M S <quant> @N<PRED
para	 [para] PRP @A<
tentar	 [tentar] V INF @IMV @#ICL-P<
ser	 [ser] V INF @IMV @#ICL-<ACC
gente	 [gente] N F S @<SC
em=vez=de	 [em=vez=de] PRP @<ADVL
apenas	 [apenas] ADV @ADVL>
projeto	 [projetar] V PR 1S IND VFIN <fmc> @FMV
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
</TEXT>
$¶	 [$¶] PU <<<
</DOC>
