<DOC>
<DOCNO.valor=FSP940101-069>
<DOCID.valor=FSP940101-069>
<DATE.valor=940101>
<TEXT>
<s>
O	 [o] DET M S <artd> @>N
prefeito	 [prefeito] N M S @SUBJ>
de	 [de] PRP @N<
Belém	 [Belém] PROP M S @P<
$,
Hélio=Gueiros	 [Hélio=Gueiros] PROP M S @APP
$(	 [$(] PU
PFL	 [PFL] PROP M/F S @N<PRED
$)	 [$)] PU
$,
vai	 [ir] V PR 3S IND VFIN <fmc> @FAUX
transferir	 [transferir] V INF @IMV @#ICL-AUX<
ainda	 [ainda] ADV @>P
em	 [em] PRP <sam-> @<ADVL
o	 [o] DET M S <artd> <-sam> @>N
início	 [início] N M S @P<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
mês	 [mês] N M S @P<
seu	 [seu] DET M S <si> <poss 3S> @>N
gabinete	 [gabinete] N M S @<ACC
para	 [para] PRP @<ADVL
o	 [o] DET M S <artd> @>N
Palácio	 [palácio] <prop> N M S @P<
Antônio=Lemos	 [Antônio=Lemos] PROP M S @N<
$,
em	 [em] PRP <sam-> @<ADVL
o	 [o] DET M S <artd> <-sam> @>N
centro	 [centro] N M S @P<
comercial	 [comercial] ADJ M S @N<
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
cidade	 [cidade] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> @>N
Departamento=de=Trânsito	 [Departamento=de=Trânsito] PROP M S @SUBJ>
prevê	 [prever] V PR 3S IND VFIN <fmc> @FMV
congestionamento	 [congestionamento] N M S @<ACC
em	 [em] PRP <sam-> @<ADVL
a	 [o] DET F S <artd> <-sam> @>N
área	 [área] N F S @P<
por	 [por] PRP @<ADVL
falta	 [falta] N F S @P<
de	 [de] PRP @N<
vagas	 [vaga] N F P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Em	 [em] PRP <sam-> @ADVL>
esta	 [este] DET F S <dem> <-sam> @>N
parte	 [parte] N F S @P<
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
cidade	 [cidade] N F S @P<
$,
os	 [o] DET M P <artd> @>N
carros	 [carro] N M P @SUBJ>
estacionados	 [estacionar] V PCP M P @N<
fazem	 [fazer] V PR 3P IND VFIN <fmc> @FMV
fila	 [fila] N F S @<ACC
dupla	 [duplo] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Pará	 [pará] N M S @NPHR
2	 [2] NUM M/F P <card> @N<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> @>N
vereador	 [vereador] N M S @SUBJ>
Arnaldo=Jordy	 [Arnaldo=Jordy] PROP M S @N<
$(	 [$(] PU
PPS	 [PPS] PROP M/F S @N<PRED
$)	 [$)] PU
disse	 [dizer] V PS 3S IND VFIN <fmc> @FMV
que	 [que] KS @SUB @#FS-<ACC
é	 [ser] V PR 3S IND VFIN @FMV
passível	 [passível] ADJ F S @<SC
de	 [de] PRP @A<
ação	 [ação] N F S @P<
judicial	 [judicial] ADJ F S @N<
a	 [o] DET F S <artd> @>N
cobrança	 [cobrança] N F S @<SUBJ
de	 [de] PRP @N<
Contribuição=Urbanística	 [Contribuição=Urbanística] PROP F S @P<
$,
recém-aprovada	 [recém-aprovar] V PCP F S @IMV @#ICL-N<PRED
em	 [em] PRP <sam-> @<ADVL
a	 [o] DET F S <artd> <-sam> @>N
Câmara=Municipal	 [Câmara=Municipal] PROP F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
A	 [o] DET F S <artd> @>N
contribuição	 [contribuição] N F S @SUBJ>
tributa	 [tributar] V PR 3S IND VFIN <fmc> @FMV
os	 [o] DET M P <artd> @>N
proprietários	 [proprietário] N M P @<ACC
de	 [de] PRP @N<
imóveis	 [imóvel] ADJ M/F P @P<
por	 [por] PRP @<ADVL
serviços	 [serviço] N M P @P<
urbanos	 [urbano] ADJ M P @N<
$,
como	 [como] ADV @PRD @#AS-<SC <rel> @#AS-SC>
saneamento	 [saneamento] N M S @AS<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Jordy	 [Jordy] PROP M/F S @SUBJ>
diz	 [dizer] V PR 3S IND VFIN <fmc> @FMV
que	 [que] KS @SUB @#FS-<ACC
a	 [o] DET F S <artd> @>N
lei	 [lei] N F S @SUBJ>
fere	 [ferir] V PR 3S IND VFIN @FMV
a	 [o] DET F S <artd> @>N
Constituição	 [constituição] <prop> N F S @<ACC
$,
pois	 [pois] KS @ADVL>
saneamento	 [saneamento] N M S @SUBJ>
é	 [ser] V PR 3S IND VFIN <fmc> @FMV
saúde	 [saúde] N F S @<SC
$,
cuja	 [cujo] DET F S @>N <rel> @#FS-N<
responsabilidade	 [responsabilidade] N F S @SUBJ>
constitucional	 [constitucional] ADJ F S @N<
é	 [ser] V PR 3S IND VFIN @FMV
de	 [de] PRP <sam-> @<SC
o	 [o] DET M S <artd> <-sam> @>N
Estado	 [estado] <prop> N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Acre	 [acre] N M S @NPHR
1	 [1] NUM M/F S <card> @N<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> @>N
balaaço ALT balaço	 [balaaço] N M S @SUBJ>
anual	 [anual] ADJ M S @N<
de	 [de] PRP <sam-> @N<
as	 [o] DET F P <artd> <-sam> @>N
atividades	 [atividade] N F P @P<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
Ibama	 [Ibama] PROP M S @P<
em	 [em] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
Acre	 [Acre] PROP M S @P<
em	 [em] PRP @N<
1993	 [1993] NUM M/F P <card> @P<
revela	 [revelar] V PR 3S IND VFIN <fmc> @FMV
o	 [o] DET M S <artd> @>N
desmatamento	 [desmatamento] N M S @<ACC
de	 [de] PRP @N<
23.600	 [23.600] NUM M P <card> @>N
hectares	 [hectare] N M P @P<
e	 [e] KC @CO
a	 [o] DET F S <artd> @>N
queima	 [queima] N F S @<ACC
de	 [de] PRP @N<
outros	 [outro] DET M P <KOMP> <diff> @>N
47.926	 [47.926] NUM M P <card> @>N
hectares	 [hectare] N M P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> @>N
órgão	 [órgão] N M S @SUBJ>
multou	 [multar] V PS 3S IND VFIN <fmc> @FMV
152	 [152] NUM M P <card> @>N
madeireiros	 [madeireiro] N M P @<ACC
arrecadando	 [arrecadar] V GER @#ICL-<ADVL @IMV
Cr$	 [cr$] <prop> N M S @<ACC
6,8	 [6,8] NUM M P <card> @>N
milhões	 [milhão] N M P @PRED>
em	 [em] PRP @N<
multas	 [multa] N F P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Foram	 [ser] V PS/MQP 3P IND VFIN <fmc> @FAUX
apreendidos	 [apreender] V PCP M P @IMV @#ICL-AUX<
3.900	 [3.900] NUM M P <card> @>N
metros=cúbicos	 [metro=cúbico] N M P @<SUBJ
de	 [de] PRP @N<
madeira	 [madeira] N F S @P<
e	 [e] KC @CO
1.476	 [1.476] NUM M P <card> @>N
quilos	 [quilo] N M P @<SUBJ
de	 [de] PRP @N<
carne	 [carne] N F S @P<
de	 [de] PRP @N<
caça	 [caça] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Acre	 [acre] N M S @NPHR
2	 [2] NUM M/F P <card> @N<
$¶	 [$¶] PU <<<
</s>
<s>
Estudantes	 [estudante] N M/F P @SUBJ>
estão	 [estar] V PR 3P IND VFIN <fmc> @FAUX
pedindo	 [pedir] V GER @#ICL-AUX< @IMV
a	 [o] DET F S <artd> @>N
abertura	 [abertura] N F S @<ACC
de	 [de] PRP @N<
um	 [um] DET M S <arti> @>N
consulado	 [consulado] N M S @P<
brasileiro	 [brasileiro] ADJ M S @N<
em	 [em] PRP @N<
Puerto=Suarez	 [Puerto=Suarez] PROP M S @P<
$,
em	 [em] PRP <sam-> @<ADVL
a	 [o] DET F S <artd> <-sam> @>N
Bolívia	 [Bolívia] PROP F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
80	 [80] NUM M/F P <card> @>N
jovens	 [jovem] ADJ M/F P @>N
acreanos	 [acreano] <n> ADJ M P @SUBJ>
que	 [que] SPEC M/F S @SUBJ> <rel> @#FS-N<
estudam	 [estudar] V PR 3P IND VFIN @FMV
medicina	 [medicina] N F S @<ACC
e	 [e] <co-vfin> KC @CO
odontologia	 [odontologia] N F S @<ACC
em	 [em] PRP @<ADVL
Puerto=Suarez	 [Puerto=Suarez] PROP M S @P<
estão	 [estar] V PR 3P IND VFIN <fmc> @FAUX
passando	 [passar] V GER @#ICL-AUX< @IMV
férias	 [féria] N F P @<ACC
em	 [em] PRP @<ADVL
Rio=Branco	 [Rio=Branco] PROP M S @P<
e	 [e] <co-fmc> <co-vfin> KC @CO
a	 [o] DET F S <artd> @>N
maioria	 [maioria] N F S @SUBJ>
se	 [se] PERS M/F 3S ACC <refl> @ACC>
queixa	 [queixar] V PR 3S IND VFIN <fmc> @FMV
de	 [de] PRP @<PIV
dificuldades	 [dificuldade] N F P @P<
e	 [e] KC @CO
preconceito	 [preconceito] N M S @P<
de	 [de] PRP @N<
autoridades	 [autoridade] N F P @P<
$,
professores	 [professor] N M P @N<PRED @P<
e	 [e] KC @CO
colegas	 [colega] N M/F P @N<PRED @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Somos	 [ser] V PR 1P IND VFIN @FAUX <*1> @#FS-ACC>>
perseguidos	 [perseguir] V PCP M P @IMV @#ICL-AUX<
por	 [por] PRP <sam-> @<PASS
a	 [o] DET F S <artd> <-sam> @>N
Interpol	 [Interpol] PROP F S @P<
e	 [e] <co-pcv> KC @CO
tratados	 [tratar] V PCP M P @#ICL-AUX< @P< @IMV
como	 [como] ADV @#AS-<SC <rel> @PRD
marginais	 [marginal] ADJ M/F P <*2> @AS<
$,
afirma	 [afirmar] V PR 3S IND VFIN <fmc> @FMV
Henrique=Pinedo=Uchoa	 [Henrique=Pinedo=Uchoa] PROP F S @<SUBJ
$,
22	 [22] NUM M/F P <card> @<ACC
$,
estudante	 [estudante] N M/F S @N<PRED
de	 [de] PRP @N<
medicina	 [medicina] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Acre	 [acre] N M S @NPHR
3	 [3] NUM M/F P <card> @N<
$¶	 [$¶] PU <<<
</s>
<s>
Uma	 [um] DET F S <arti> @>N
delegação	 [delegação] N F S @SUBJ>
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
Federação=de=Agricultura=do=Estado	 [Federação=de=Agricultura=do=Estado] PROP F S @P<
viaja	 [viajar] V PR 3S IND VFIN <fmc> @FMV
em	 [em] PRP <sam-> @<ADVL
a	 [o] DET F S <artd> <-sam> @>N
próxima	 [próximo] ADJ F S @>N
semana	 [semana] N F S @P<
para	 [para] PRP @<ADVL
Lima	 [Lima] PROP M S @P<
$,
em	 [em] PRP <sam-> @<ADVL
o	 [o] DET M S <artd> <-sam> @>N
Peru	 [Peru] PROP M S @P<
$,
para	 [para] PRP @<ADVL
negociar	 [negociar] V INF @IMV @#ICL-P<
a	 [o] DET F S <artd> @>N
venda	 [venda] N F S @<ACC
de	 [de] PRP @N<
20	 [20] NUM F P <card> @>N
toneladas	 [tonelada] N F P @P<
de	 [de] PRP @N<
carne	 [carne] N F S @P<
bovina	 [bovino] ADJ F S @N<
a	 [a] PRP <sam-> @N<
os	 [o] DET M P <artd> <-sam> @>N
peruanos	 [peruano] N M P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Segundo	 [segundo] ADV @COM <prp> <rel> @#AS-ADVL>
a	 [o] DET F S <artd> @>N
federação	 [federação] N F S @AS<
$,
a	 [o] DET F S <artd> @>N
medida	 [medida] N F S @SUBJ>
é	 [ser] V PR 3S IND VFIN <fmc> @FMV
consequência ALT conseqüência	 [consequência] N F S @<SC
de	 [de] PRP @N<
uma	 [um] DET F S <arti> @>N
sobretaxa	 [sobretaxa] N F S @P<
de	 [de] PRP @N<
40	 [40] NUM M/F P <card> @>N
$%	 [%] N M P @P<	 [$%] PU
imposta	 [impor] V PCP F S @IMV @#ICL-N<
por	 [por] PRP <sam-> @<PASS
o	 [o] DET M S <artd> <-sam> @>N
governo	 [governo] N M S @P<
de	 [de] PRP @N<
Rondônia	 [Rondônia] PROP F S @P<
a	 [a] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
carne	 [carne] N F S @P<
vendida	 [vender] V PCP F S @IMV @#ICL-N<
por	 [por] PRP <sam-> @<PASS
o	 [o] DET M S <artd> <-sam> @>N
Acre	 [Acre] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Amazonas	 [amazona] N F P @NPHR
1	 [1] NUM M/F S <card> @N<
$¶	 [$¶] PU <<<
</s>
<s>
A	 [o] DET F S <artd> @>N
empresa	 [empresa] N F S @SUBJ>
de	 [de] PRP @N<
consultoria	 [consultoria] N F S @P<
Rede	 [rede] <prop> N F S @N<
foi	 [ser] V PS 3S IND VFIN <fmc> @FMV
a	 [o] DET F S <artd> @>N
vencedora	 [vencedora] N F S @<SC
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
licitação	 [licitação] N F S @P<
para	 [para] PRP @<ADVL
apresentação	 [apresentação] N F S @P<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
projeto	 [projeto] N M S @P<
de	 [de] PRP @N<
construção	 [construção] N F S @P<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
complexo	 [complexo] N M S @P<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
Entreposto=Internacional=da=Zona=Franca=de=Manaus	 [Entreposto=Internacional=da=Zona=Franca=de=Manaus] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
A	 [o] DET F S <artd> @>N
previsão	 [previsão] N F S @SUBJ>
é	 [ser] V PR 3S IND VFIN <fmc> @FMV
de	 [de] PRP @<SC
que	 [que] KS @SUB @#FS-P<
até	 [até] ADV @>N
o	 [o] DET M S <artd> @>N
segundo	 [segundo] ADJ M S <NUM-ord> @>N
semestre	 [semestre] N M S @SUBJ>
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
próximo	 [próximo] ADJ M S @>N
ano	 [ano] N M S @P<
as	 [o] DET F P <artd> @>N
obras	 [obra] N F P @SUBJ>
estejam	 [estar] V PR 3P SUBJ VFIN @FMV
conculídas ALT xxxas	 [conculído] ADJ F P @<SC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> @>N
faturamento	 [faturamento] N M S @SUBJ>
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
entreposto	 [entreposto] N M S @P<
provisório	 [provisório] ADJ M S @N<
$,
este	 [este] DET M S <dem> @>N
ano	 [ano] N M S @ADVL>
$,
foi	 [ser] V PS 3S IND VFIN <fmc> @FMV
de	 [de] PRP @<SC
US$	 [US$] PROP M/F S @P<
200	 [200] NUM M P <card> @>N
milhões	 [milhão] N M P @PRED>
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Amazonas	 [amazona] N F P @NPHR
2	 [2] NUM M/F P <card> @N<
$¶	 [$¶] PU <<<
</s>
<s>
A	 [o] DET F S <artd> @>N
Federação=das=Indústrias=do=Estado=do=Amazonas	 [Federação=das=Indústrias=do=Estado=do=Amazonas] PROP F S @SUBJ>
vai	 [ir] V PR 3S IND VFIN <fmc> @FAUX
recolher	 [recolher] V INF @IMV @#ICL-AUX<
$,
de	 [de] PRP @<ADVL
3=a=31	 [3=a=31] NUM M/F P @P<
de	 [de] PRP @N<
janeiro	 [janeiro] N M S @P<
$,
a	 [o] DET F S <artd> @>N
contribuição	 [contribuição] N F S @<ACC
sindical	 [sindical] ADJ F S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
A	 [o] DET F S <artd> @>N
taxa	 [taxa] N F S @SUBJ>
pode	 [poder] V PR 3S IND VFIN <fmc> @FAUX
ser	 [ser] V INF @IAUX @#ICL-AUX<
paga	 [pagar] V PCP F S @IMV @#ICL-AUX<
sem	 [sem] PRP @<ADVL
acréscimo	 [acréscimo] N M S @P<
por	 [por] PRP <sam-> @<ADVL
as	 [o] DET F P <artd> <-sam> @>N
empresas	 [empresa] N F P @P<
integrantes	 [integrante] ADJ F P @N<
de	 [de] PRP <sam-> @N<
os	 [o] DET M P <artd> <-sam> @>N
grupos	 [grupo] N M P @P<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
Plano=Básico=da=Confederação=Nacional=das=Indústrias	 [Plano=Básico=da=Confederação=Nacional=das=Indústrias] PROP M S @P<
que	 [que] SPEC M/F S @ACC> <rel> @#FS-<SUBJ
não	 [não] ADV @ADVL>
constituíram	 [constituir] V PS/MQP 3P IND VFIN @FMV
sindicatos	 [sindicato] N M P @<ACC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Amazonas	 [amazona] N F P @NPHR
3	 [3] NUM M/F P <card> @N<
$¶	 [$¶] PU <<<
</s>
<s>
Moçambique	 [Moçambique] PROP M S @SUBJ>
pode	 [poder] V PR 3S IND VFIN <fmc> @FAUX
realizar	 [realizar] V INF @IMV @#ICL-AUX<
este	 [este] DET M S <dem> @>N
ano	 [ano] N M S @<ADVL
convênios	 [convênio] N M P @<ACC
de	 [de] PRP @N<
cooperação	 [cooperação] N F S @P<
técnica	 [técnico] ADJ F S @N<
com	 [com] PRP @N<
o	 [o] DET M S <artd> @>N
Amazonas	 [Amazonas] PROP M S @P<
para	 [para] PRP @<ADVL
o	 [o] DET M S <artd> @>N
desenvolvimento	 [desenvolvimento] N M S @P<
de	 [de] PRP <sam-> @N<
os	 [o] DET M P <artd> <-sam> @>N
municípios	 [município] N M P @P<
de	 [de] PRP <sam-> @N<
aquele	 [aquele] DET M S <dem> <-sam> @>N
país	 [país] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
A	 [o] DET F S <artd> @>N
informação	 [informação] N F S @SUBJ>
é	 [ser] V PR 3S IND VFIN <fmc> @FMV
de	 [de] PRP <sam-> @<SC
o	 [o] DET M S <artd> <-sam> @>N
ministro	 [ministro] N M S @P<
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
Administração=Estatal	 [Administração=Estatal] PROP F S @P<
$,
Aguiar=Jonassane=Reginaldo=Mazula	 [Aguiar=Jonassane=Reginaldo=Mazula] PROP M S @APP
$,
que	 [que] SPEC M/F S @SUBJ> <rel> @#FS-N<
esteve	 [estar] V PS 3S IND VFIN @FMV
em	 [em] PRP @<ADVS
Manaus	 [Manaus] PROP M S @P<
e	 [e] <co-fmc> <co-vfin> KC @CO
conversou	 [conversar] V PS 3S IND VFIN <fmc> @FMV
com	 [com] PRP @<PIV
o	 [o] DET M S <artd> @>N
vice-governador	 [vice-governador] N M S @P<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
Amazonas	 [Amazonas] PROP M S @P<
$,
Francisco=Garcia	 [Francisco=Garcia] PROP M S @<SC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Mazula	 [Mazula] PROP M/F S @SUBJ>
disse	 [dizer] V PS 3S IND VFIN <fmc> @FMV
que	 [que] KS @SUB @#FS-<ACC
a	 [o] DET F S <artd> @>N
organização	 [organização] N F S @SUBJ>
municipal	 [municipal] ADJ F S @N<
brasileira	 [brasileiro] ADJ F S @N<
é	 [ser] V PR 3S IND VFIN @FMV
de	 [de] PRP @<SC
interesse	 [interesse] N M S @P<
para	 [para] PRP @<ADVL
Moçambique	 [Moçambique] PROP M S @P<
porque	 [porque] KS @SUB <*1> @#FS-<ADVL
apresenta	 [apresentar] V PR 3S IND VFIN @FMV
soluções	 [solução] N F P @<ACC
ágeis	 [ágil] ADJ M/F P @N<PRED
de	 [de] PRP @<ADVL
administração	 [administração] N F S <*2> @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
</TEXT>
$¶	 [$¶] PU <<<
</DOC>
