<DOC>
<DOCNO.valor=FSP940101-087>
<DOCID.valor=FSP940101-087>
<DATE.valor=940101>
<TEXT>
<s>
Fernando=Rossetti	 [Fernando=Rossetti] PROP M S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
Da=Reportagem=Local	 [Da=Reportagem=Local] PROP F S @NPHR
$¶	 [$¶] PU <<<
</s>
<s>
A	 [o] DET F S <artd> @>N
previsão	 [previsão] N F S @PRED>
feita	 [fazer] V PCP F S @IMV @#ICL-N<
por	 [por] PRP @<ADVL
pais	 [pai] N M P @P<
durante	 [durante] PRP @ADVL>
os	 [o] DET M P <artd> @>N
79	 [79] NUM M P <card> @>N
dias	 [dia] N M P @P<
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
greve	 [greve] N F S @P<
em	 [em] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
rede	 [rede] N F S @P<
estadual	 [estadual] ADJ F S @N<
de	 [de] PRP @N<
ensino	 [ensino] N M S @P<
de	 [de] PRP @N<
São=Paulo	 [São=Paulo] PROP M S @P<
se	 [se] PERS M/F 3S ACC @SUBJ>
realizou	 [realizar] V PS 3S IND VFIN <fmc> @FMV
$:	 [$:] PU <<<
a	 [o] DET F S <artd> @>N
reposição	 [reposição] N F S @SUBJ>
de	 [de] PRP @N<
aulas	 [aula] N F P @P<
foi	 [ser] V PS 3S IND VFIN <fmc> @FMV
fraca	 [fraco] ADJ F S @<SC
$,
curta	 [curto] ADJ F S @SUBJ>
e	 [e] <co-fmc> <co-vfin> KC @CO
os	 [o] DET M P <artd> @>N
prejuízos	 [prejuízo] N M P @SUBJ>
em	 [em] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
aprendizado	 [aprendizado] N M S @P<
acompanharão	 [acompanhar] V FUT 3P IND VFIN <fmc> @FMV
os	 [o] DET M P <artd> @>N
alunos	 [aluno] N M P @<ACC
$,
em	 [em] PRP <sam-> @<ADVL
o	 [o] DET M S <artd> <-sam> @>N
mínimo	 [pequeno] <n> ADJ M S <SUP> @P<
$,
durante	 [durante] PRP @<ADVL
todo=o	 [todo=o] DET M S <quant> @>N
próximo	 [próximo] ADJ M S @>N
ano=letivo	 [ano=letivo] N M S @P<
$	 [$] PU
que	 [que] SPEC M/F S @SUBJ> <rel> @#FS-N<
vai	 [ir] V PR 3S IND VFIN @FAUX
começar	 [começar] V INF @IMV @#ICL-AUX<
com	 [com] PRP @<ADVL
um	 [um] NUM M S <card> @>N
mês	 [mês] N M S @P<
de	 [de] PRP @N<
atraso	 [atraso] N M S @P<
$,
dia	 [dia] N M S @<ADVL
1º	 [1º] NUM M/F P @N< <card> @<ACC
$.	 [$.] PU <<<
de	 [de] PRP @ADVL
março	 [março] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Em	 [em] PRP @ADVL>
31	 [31] NUM M/F S <card> @P<
de	 [de] PRP @N<
dezembro	 [dezembro] N M S @P<
$,
cerca=de	 [cerca=de] ADV @>A
80	 [80] NUM M/F P <card> @>N
$%	 [%] N M P @SUBJ>	 [$%] PU
de	 [de] PRP <sam-> @N<
as	 [o] DET F P <artd> <-sam> @>N
6.682	 [6.682] NUM F P <card> @>N
escolas	 [escola] N F P @P<
administradas	 [administrar] V PCP F P @IMV @#ICL-N<
por	 [por] PRP <sam-> @<PASS
o	 [o] DET M S <artd> <-sam> @>N
governo	 [governo] N M S @P<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
Estado	 [estado] <prop> N M S @P<
já	 [já] ADV @ADVL>
tinham	 [ter] V IMPF 3P IND VFIN <fmc> @FAUX
concluído	 [concluir] V PCP @IMV @#ICL-AUX<
a	 [o] DET F S <artd> @>N
reposição	 [reposição] N F S @<ACC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Como	 [como] KS @SUB @#FS-<ADVL
a	 [o] DET F S <artd> @>N
greve	 [greve] N F S @SUBJ>
começou	 [começar] V PS 3S IND VFIN @FMV
em	 [em] PRP <sam-> @<ADVL
o	 [o] DET M S <artd> <-sam> @>N
dia	 [dia] N M S @P<
18	 [18] NUM M/F P <card> @N<
de	 [de] PRP @N<
agosto	 [agosto] N M S @P<
e	 [e] <co-vfin> KC @CO
terminou	 [terminar] V PS 3S IND VFIN <fmc> @FMV
em	 [em] PRP <sam-> @<PIV
o	 [o] DET M S <artd> <-sam> @>N
dia	 [dia] N M S @P<
5	 [5] NUM M/F P <card> @N<
de	 [de] PRP @N<
novembro	 [novembro] N M S @P<
$,
quem	 [quem] SPEC M S <rel> @SUBJ>
ficou	 [ficar] V PS 3S IND VFIN <fmc> @FMV
paralisado	 [paralisar] V PCP M S @IMV @#ICL-<SC
em	 [em] PRP <sam-> @<ADVL
esse	 [esse] DET M S <dem> <-sam> @>N
período	 [período] N M S @P<
teve	 [ter] V PS 3S IND VFIN <fmc> @FMV
os	 [o] DET M P <artd> @>N
56	 [56] NUM M P <card> @>N
dias	 [dia] N M P @<ACC
restantes	 [restante] ADJ M P @N<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
ano	 [ano] N M S @P<
para	 [para] PRP @<ADVL
praticamente	 [prático] ADV @ADVL>
todo=o	 [todo=o] DET M S <quant> @>N
conteúdo	 [conteúdo] N M S @P<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
semestre	 [semestre] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Apenas	 [apenas] ADV @>A
20	 [20] NUM M/F P <card> @>N
$%	 [%] N M P @SUBJ>	 [$%] PU
de	 [de] PRP <sam-> @N<
as	 [o] DET F P <artd> <-sam> @>N
escolas	 [escola] N F P @P<
terão	 [ter] V FUT 3P IND VFIN <fmc> @FMV
aulas	 [aula] N F P @<ACC
em	 [em] PRP @<ADVL
fevereiro	 [fevereiro] N M S @P<
$	 [$] PU
já=que	 [já=que] KS @SUB @#FS-<ADVL
a	 [o] DET F S <artd> @>N
Secretaria=da=Educação	 [Secretaria=da=Educação] PROP F S @SUBJ>
decidiu	 [decidir] V PS 3S IND VFIN @FMV
manter	 [manter] V INF @IMV @#ICL-<ACC
as	 [o] DET F P <artd> @>N
férias	 [féria] N F P @<ACC
de	 [de] PRP @N<
janeiro	 [janeiro] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
A	 [o] DET F S <artd> @>N
própria	 [próprio] <n> ADJ F S @SUBJ>
portaria	 [portar] V COND 3S VFIN <fmc> @FMV
que	 [que] KS @SUB @#FS-<SUBJ
regulamentou	 [regulamentar] V PS 3S IND VFIN @FMV
a	 [o] DET F S <artd> @>N
reposição	 [reposição] N F S @<ACC
diminiu ALT xxxiu	 [diminir] V PS 3S IND VFIN <fmc> @FMV
o	 [o] DET M S <artd> @>N
ano=letivo	 [ano=letivo] N M S @<ACC
de	 [de] PRP @N<
200=para=180	 [200=para=180] NUM M P @>N
dias	 [dia] N M P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
De	 [de] PRP <sam-> @ADVL>
os	 [o] DET M P <artd> <-sam> @>N
52	 [52] NUM M P <card> @>N
dias	 [dia] N M P @P<
perdidos	 [perdido] ADJ M P @N<
de	 [de] PRP @A<
aula	 [aula] N F S @P<
$	 [$] PU
79	 [79] NUM M/F P <card> @P<
é	 [ser] V PR 3S IND VFIN <fmc> @FMV
o	 [o] DET M S <artd> @>N
número	 [número] N M S @<SC
de	 [de] PRP @N<
dias	 [dia] N M P @P<
corridos	 [correr] V PCP M P @N<
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
greve	 [greve] N F S @P<
$	 [$] PU
$,
32	 [32] NUM M/F P <card> @SUBJ>
tiveram	 [ter] V PS/MQP 3P IND VFIN <fmc> @FAUX
de	 [de] PRP @PRT-AUX<
ser	 [ser] V INF @IAUX @#ICL-AUX<
repostos	 [repor] V PCP M P @IMV @#ICL-AUX<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Os	 [o] DET M P <artd> @>N
pais	 [pai] N M P @SUBJ>
reclamam	 [reclamar] V PR 3P IND VFIN <fmc> @FMV
não	 [não] IN @<ACC
só	 [só] ADV @>P
de	 [de] PRP <sam-> @<ADVL
a	 [o] DET F S <artd> <-sam> @>N
brevidade	 [brevidade] N F S @P<
como	 [como] ADV @#AS-<ADVL <prp> <rel> @ADVL
de	 [de] PRP <sam-> @AS<
a	 [o] DET F S <artd> <-sam> @>N
qualidade	 [qualidade] N F S @P<
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
reposição	 [reposição] N F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Exemplo	 [exemplo] N M S @SUBJ>
de	 [de] PRP <sam-> @N<
isso	 [isso] SPEC M S <dem> <-sam> @P<
ocorreu	 [ocorrer] V PS 3S IND VFIN <fmc> @FMV
em	 [em] PRP @<ADVL
uma	 [um] DET F S <arti> @>N
8.ª	 [8.ª] ADJ F S <NUM-ord> @>N
série	 [série] N F S @P<
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
Escola	 [escola] <prop> N F S @P<
Estadual=Simione	 [Estadual=Simione] PROP F S @N<
$,
em	 [em] PRP <sam-> @<ADVL
o	 [o] DET M S <artd> <-sam> @>N
Jardim=Prudência	 [Jardim=Prudência] PROP M S @P<
$(	 [$(] PU
zona	 [zona] N F S @N<PRED
sul	 [sul] N M S @N<
de	 [de] PRP @N<
São=Paulo	 [São=Paulo] PROP M S @P<
$)	 [$)] PU
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Em	 [em] PRP <sam-> @ADVL>
a	 [o] DET F S <artd> <-sam> @>N
reposição	 [reposição] N F S @P<
de	 [de] PRP @N<
aulas	 [aula] N F P @P<
de	 [de] PRP @N<
português	 [português] N M S @P<
$,
a	 [o] DET F S <artd> @>N
professora	 [professora] N F S @SUBJ>
deu	 [dar] V PS 3S IND VFIN <fmc> @FMV
exercícios	 [exercício] N M P @<ACC
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
tipo	 [tipo] N M S @P<
sete	 [sete] N M S <*1> @N<
erros	 [erro] N M P <*2> @PRED>
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
A	 [o] DET F S <artd> @>N
mãe	 [mãe] N F S @SUBJ>
$	 [$] PU
que	 [que] SPEC M/F S @SUBJ> <rel> @#FS-N<
prefere	 [preferir] V PR 3S IND VFIN @FMV
não	 [não] ADV @ADVL>
se	 [se] PERS M/F 3S ACC @ACC>-PASS
identificar	 [identificar] V INF @IMV @#ICL-<ACC
para	 [para] PRP @<ADVL
não	 [não] ADV @ADVL>
ter	 [ter] V INF @IMV @#ICL-P<
o	 [o] DET M S <artd> @>N
filho	 [filho] N M S @<ACC
perseguido	 [perseguir] V PCP M S @N<
$	 [$] PU
denunciou	 [denunciar] V PS 3S IND VFIN <fmc> @FMV
a	 [a] PRP <sam-> @<ADVL
a	 [o] DET F S <artd> <-sam> @>N
diretoria	 [diretoria] N F S @P<
e	 [e] <co-fmc> <co-vfin> KC @CO
a	 [o] DET F S <artd> @>N
questão	 [questão] N F S @SUBJ>
foi	 [ser] V PS 3S IND VFIN <fmc> @FMV
parar	 [parar] V INF @IMV @#ICL-<SC
em	 [em] PRP <sam-> @<PIV
a	 [o] DET F S <artd> <-sam> @>N
Delegacia=de=Ensino	 [Delegacia=de=Ensino] PROP F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Não	 [não] ADV <*1> @ADVL>
tem	 [ter] V PR 3S IND VFIN <fmc> @FMV
como	 [como] ADV <rel> @ADVL>
repor	 [repor] V INF @IMV <*2> @#ICL-<ACC
$,
diz	 [dizer] V PR 3S IND VFIN <fmc> @FMV
Herbert=Tsuji=da=Silva	 [Herbert=Tsuji=da=Silva] PROP M/F S @<SUBJ
$,
19	 [19] NUM M/F P <card> @N<PRED
$,
que	 [que] SPEC M/F S @SUBJ> <rel> @#FS-N<
passou	 [passar] V PS 3S IND VFIN @FMV
para	 [para] PRP @<PIV
o	 [o] DET M S <artd> @>N
3º.	 [3º.] ADJ M S <NUM-ord> @>N
ano	 [ano] N M S @P<
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
disputada	 [disputar] <n> V PCP F S @P<
Escola=Estadual=de=Segundo=Grau=Brasílio=Machado	 [Escola=Estadual=de=Segundo=Grau=Brasílio=Machado] PROP F S @P<
$,
em	 [em] PRP <sam-> @<ADVL
a	 [o] DET F S <artd> <-sam> @>N
Vila=Mariana	 [Vila=Mariana] PROP F S @P<
$(	 [$(] PU
zona	 [zona] N F S @N<PRED
sul	 [sul] N M S @N<
$)	 [$)] PU
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> <*1> @>N
quarto	 [quarto] ADJ M S <NUM-ord> @>N
bimestre	 [bimestre] N M S @SUBJ>
foi	 [ser] V PS 3S IND VFIN <fmc> @FAUX
dado	 [dar] V PCP M S @IMV @#ICL-AUX<
em	 [em] PRP @<PIV
uma	 [uma] NUM F S <card> @>N
semana	 [semana] N F S @P<
e	 [e] KC @CO
dois	 [dois] NUM M P <card> @>N
dias	 [dia] N M P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Teve	 [ter] V PS 3S IND VFIN <fmc> @FMV
um	 [um] NUM M S <card> @>N
dia	 [dia] N M S @<ACC
em	 [em] PRP @ADVL>
que	 [que] KS @SUB @#FS-<ACC
fizemos	 [fazer] V PS 1P IND VFIN @FMV
três	 [três] NUM F P <card> @>N
provas	 [prova] N F P @<ACC
e	 [e] <co-fmc> <co-vfin> KC @CO
entregamos	 [entregar] V PS 1P IND VFIN <fmc> @FMV
dois	 [dois] NUM M P <card> @>N
trabalhos	 [trabalho] N M P <*2> @<ACC
$,
afirma	 [afirmar] V PR 3S IND VFIN <fmc> @FMV
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Houve	 [haver] V PS 1/3S IND VFIN <fmc> @FMV
alunos	 [aluno] N M P @<ACC
que	 [que] KS @SUB @#FS-<ACC
se	 [se] PERS M/F 3S ACC <refl> @ACC>
sentiram	 [sentir] V PS/MQP 3P IND VFIN @FMV
prejudicados	 [prejudicar] V PCP M P @<OC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Glauco=Buchaim=Regos	 [Glauco=Buchaim=Regos] PROP M S @SUBJ>
$,
20	 [20] NUM M/F P <card> @P<
$,
estava	 [estar] V IMPF 3S IND VFIN <fmc> @FMV
com	 [com] PRP @<SC
nota	 [nota] N F S @P<
vermelha	 [vermelho] ADJ F S @N<
$(	 [$(] PU
abaixo=de	 [abaixo=de] PRP <sam-> @<ADVL
a	 [o] DET F S <-sam> <artd> @>N
média	 [média] N F S @P<
$)	 [$)] PU
em	 [em] PRP <sam-> @<ADVL
os	 [o] DET M P <artd> <-sam> @>N
dois	 [dois] NUM M P <card> @>N
primeiros	 [primeiro] ADJ M P <NUM-ord> @>N
bimestres	 [bimestre] N M P @P<
e	 [e] <co-fmc> <co-vfin> KC @CO
acabou	 [acabar] V PS 3S IND VFIN <fmc> @FMV
reprovado	 [reprovar] V PCP M S @IMV @#ICL-<SC
em	 [em] PRP <sam-> @<ADVL
a	 [o] DET F S <artd> <-sam> @>N
2.ª	 [2.ª] ADJ F S <NUM-ord> @>N
série	 [série] N F S @P<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
Brasílio=Machado	 [Brasílio=Machado] PROP M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Vou	 [ir] V PR 1S IND VFIN <fmc> <*1> @FAUX
entrar	 [entrar] V INF @IMV @#ICL-AUX<
com	 [com] PRP @<PIV
recurso	 [recurso] N M S @P<
em	 [em] PRP <sam-> @<ADVL
a	 [o] DET F S <artd> <-sam> @>N
Delegacia=de=Ensino	 [Delegacia=de=Ensino] PROP F S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Achei	 [achar] V PS 1S IND VFIN <fmc> @FMV
uma	 [um] DET F S <arti> @>N
sacanagem	 [sacanagem] N F S <*2> @<ACC
$,
afirma	 [afirmar] V PR 3S IND VFIN <fmc> @FMV
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Em	 [em] PRP <sam-> @ADVL>
a	 [o] DET F S <artd> <-sam> @>N
última	 [último] ADJ F S <NUM-ord> @>N
quinta-feira	 [quinta-feira] N F S @P<
a	 [a] PRP <sam-> @ADVL>
a	 [o] DET F S <artd> <-sam> @>N
tarde	 [tarde] N F S @P<
$,
as	 [o] DET F P <artd> @>N
turmas	 [turma] N F P @APP
de	 [de] PRP @N<
reposição	 [reposição] N F S @P<
de=primeiro	 [de=primeiro] ADV @ADVL>
grau	 [grau] N M S @SUBJ>
de	 [de] PRP <sam-> @N<
a	 [o] DET F S <artd> <-sam> @>N
Escola=Estadual=Gualter=da=Silva	 [Escola=Estadual=Gualter=da=Silva] PROP F S @P<
$,
em	 [em] PRP <sam-> @ADVL>
o	 [o] DET M S <artd> <-sam> @>N
Sacomã	 [Sacomã] PROP M S @P<
$(	 [$(] PU
zona	 [zona] N F S @N<PRED
sul	 [sul] N M S @N<
$)	 [$)] PU
$,
tinham	 [ter] V IMPF 3P IND VFIN <fmc> @FMV
cerca=de	 [cerca=de] ADV @>A
um	 [um] NUM M S <card> @>N
terço	 [terço] N M S @<ACC
de	 [de] PRP <sam-> @N<
os	 [o] DET M P <artd> <-sam> @>N
alunos	 [aluno] N M P @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
O	 [o] DET M S <artd> @>N
colégio	 [colégio] N M S @SUBJ>
ficou	 [ficar] V PS 3S IND VFIN <fmc> @FMV
os	 [o] DET M P <artd> @>N
79	 [79] NUM M P <card> @>N
dias	 [dia] N M P @PRED>
em	 [em] PRP @N<
greve	 [greve] N F S @P<
e	 [e] <co-fmc> <co-vfin> KC @CO
$,
inclusive	 [inclusive] ADV @>N
a	 [o] DET F S <artd> @>N
3.ª	 [3.ª] ADJ F S <NUM-ord> @>N
série	 [série] N F S @A<
de	 [de] PRP <sam-> @N<
o	 [o] DET M S <artd> <-sam> @>N
2º.	 [2º.] ADJ M S <NUM-ord> @>N
grau	 [grau] N M S @P<
$,
terá	 [ter] V FUT 3S IND VFIN <fmc> @FMV
reposição	 [reposição] N F S @<ACC
em	 [em] PRP @<ADVL
fevereiro	 [fevereiro] N M S @P<
$	 [$] PU
apesar=de	 [apesar=de] PRP <sam-> @<ADVL
os	 [o] DET M P <artd> <-sam> @>N
principais	 [principal] ADJ M P <SUP> @>N
vestibulares	 [vestibular] N M P @P<
ocorrerem	 [ocorrer] V INF 3P @IMV
em	 [em] PRP @<ADVL
janeiro	 [janeiro] N M S @P<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Está	 [estar] V PR 3S IND VFIN <fmc> <*1> @FMV
todo=mundo	 [todo=mundo] SPEC M S @<SC
insatisfeito	 [insatisfeito] ADJ M S @N<PRED
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Os	 [o] DET M P <artd> @>N
alunos	 [aluno] N M P @SUBJ>
por	 [por] PRP @N<
terem	 [ter] V INF 3P @IAUX @#ICL-P<
ficado	 [ficar] V PCP @IMV @#ICL-AUX<
prejudicados	 [prejudicar] V PCP M P @<SC
e	 [e] KC @CO
os	 [o] DET M P <artd> @>N
professores	 [professor] N M P @<SC
com	 [com] PRP @N<
os	 [o] DET M P <artd> @>N
salários	 [salário] N M P @P<
baixos	 [baixo] ADJ M P <*2> @N<
$,
comentou	 [comentar] V PS 3S IND VFIN <fmc> @FMV
uma	 [um] DET F S <arti> @>N
professora	 [professora] N F S @<ACC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Para	 [para] PRP <*1> @ADVL>
mim	 [eu] PERS M/F 1S PIV @P<
não	 [não] ADV @ADVL>
houve	 [haver] V PS 1/3S IND VFIN <fmc> @FMV
reposição	 [reposição] N F S @<ACC
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
Não	 [não] ADV @>P
por	 [por] PRP <sam-> @ADVL>
a	 [o] DET F S <artd> <-sam> @>N
má=vontade	 [má=vontade] N F S @P<
de	 [de] PRP <sam-> @N<
os	 [o] DET M P <artd> <-sam> @>N
professores	 [professor] N M P @P<
$,
mas	 [mas] KC @CO
por	 [por] PRP <sam-> @ADVL>
o	 [o] DET M S <artd> <-sam> @>N
tempo	 [tempo] N M S @P<
disponível	 [disponível] ADJ M S <*2> @N<
$,
afirma	 [afirmar] V PR 3S IND VFIN <fmc> @FMV
Elisa=Toneto	 [Elisa=Toneto] PROP F S @<SUBJ
$,
de	 [de] PRP <sam-> @N<PRED
o	 [o] DET M S <artd> <-sam> @>N
Movimento	 [movimento] <prop> N M S @P<
Pró-Educação	 [Pró-Educação] PROP M S @N<
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
<s>
A	 [o] DET F S <artd> <*1> @>N
greve	 [greve] N F S @SUBJ>
deveria	 [dever] V COND 3S VFIN <fmc> @FAUX
deixar	 [deixar] V INF @IAUX @#ICL-AUX<
de	 [de] PRP @PRT-AUX<
acontecer	 [acontecer] V INF @IMV @#ICL-AUX<
em	 [em] PRP <sam-> @<ADVL
a	 [o] DET F S <artd> <-sam> @>N
educação	 [educação] N F S <*2> @P<
$,
defende	 [defender] V PR 3S IND VFIN <fmc> @FMV
$.	 [$.] PU <<<
$¶	 [$¶] PU <<<
</s>
</TEXT>
$¶	 [$¶] PU <<<
</DOC>
